In [1]:
import pandas as pd

In [2]:
!ls ../dataset_kraken/

family_name_ids.csv  genus_name_ids.csv  species_name_ids.csv
family_seqs.csv      genus_seqs.csv	 species_seqs.csv

In [2]:
species_labels = pd.read_csv("../dataset_kraken/species_name_ids.csv")
genus_labels = pd.read_csv("../dataset_kraken/genus_name_ids.csv")

In [3]:
species_labels.head()

                          species  id
0   Alphafusarivirus rutstroemiae   1
1  Alphafusarivirus macrophominae   2
2      Alphafusarivirus ioaponiae   3
3   Alphafusarivirus auriculariae   4
4      Alphafusarivirus penicilli   5

In [5]:
genus_labels.head()

               genus  id
0   Alphafusarivirus   1
1    Betafusarivirus   2
2   Gammafusarivirus   3
3   Betapartitivirus   4
4  Gammapartitivirus   5

In [6]:
import pandas as pd
from Bio import Entrez, SeqIO
from tqdm import tqdm
import time

# 2. CONFIGURATION
Entrez.email = "matheuslimaaa13@gmail.com"  # <--- REPLACE THIS

def fetch_ncbi_sequences(species_name, max_results=3):
    """
    Searches NCBI Nucleotide for a species and returns a list of sequences.
    """
    try:
        search_term = f"{species_name}[Organism] AND biomol_genomic[PROP]"
        search_handle = Entrez.esearch(db="nucleotide", term=search_term, retmax=max_results)
        search_results = Entrez.read(search_handle)
        search_handle.close()
        
        id_list = search_results['IdList']
        
        if not id_list:
            return []

        fetch_handle = Entrez.efetch(db="nucleotide", id=id_list, rettype="fasta", retmode="text")
        sequences = [str(record.seq) for record in SeqIO.parse(fetch_handle, "fasta")]
        fetch_handle.close()
        
        return sequences

    except Exception as e:
        print(f"Error fetching {species_name}: {e}")
        return []

# 3. MAIN PROCESSING
final_data = []

# Using tqdm for the progress bar
# We wrap species_labels.iterrows() (or just the index) with tqdm
print("Starting processing...")
for index, row in tqdm(species_labels.iterrows(), total=species_labels.shape[0], desc="Fetching Species"):
    
    species_name = row['species']
    species_id = row['id']
    
    # 1. Derive Genus
    derived_genus_name = species_name.split()[0]
    
    # 2. Check and Update Genus DataFrame
    # Check if genus exists in the genus_labels DataFrame
    genus_match = genus_labels[genus_labels['genus'] == derived_genus_name]
    
    if genus_match.empty:
        # Create a new unique ID (max id + 1, or 1 if empty)
        if genus_labels.empty:
            new_genus_id = 1
        else:
            new_genus_id = genus_labels['id'].max() + 1
            
        # Add new row to genus_labels
        new_row = pd.DataFrame([{'genus': derived_genus_name, 'id': new_genus_id}])
        genus_labels = pd.concat([genus_labels, new_row], ignore_index=True)
        
        genus_id = new_genus_id
        # Optional: Print a small message (tqdm.write works better with progress bars)
        tqdm.write(f"Added new genus: {derived_genus_name} (ID: {genus_id})")
    else:
        # Get existing ID
        genus_id = genus_match.iloc[0]['id']
    
    # 3. Fetch from NCBI
    sequences = fetch_ncbi_sequences(species_name)
    
    # 4. Append Data
    for seq in sequences:
        final_data.append({
            'sequence': seq,
            'species_id': species_id,
            'genus_id': genus_id
        })
    
    # Sleep to respect NCBI rate limits
    time.sleep(1)

# 4. OUTPUT RESULTS
final_df = pd.DataFrame(final_data)

print("\nProcessing Complete!")
print("Updated Genus Table:")
print(genus_labels)
print("\nFinal Sequence Table:")
print(final_df.head())

Starting processing...

Fetching Species:   0%|          | 34/13683 [01:19<8:48:13,  2.32s/it]

Added new genus: Nigrospora (ID: 2703)

Fetching Species:   0%|          | 35/13683 [01:22<8:47:02,  2.32s/it]

Added new genus: Sodiomyces (ID: 2704)

Fetching Species:   0%|          | 36/13683 [01:24<8:44:49,  2.31s/it]

Added new genus: Heterobasidion (ID: 2705)

Fetching Species:   0%|          | 37/13683 [01:26<8:34:41,  2.26s/it]

Added new genus: Atkinsonella (ID: 2706)

Fetching Species:   0%|          | 39/13683 [01:30<8:21:32,  2.21s/it]

Added new genus: Crimson (ID: 2707)

Fetching Species:   0%|          | 40/13683 [01:33<9:02:47,  2.39s/it]

Added new genus: Ceratocystis (ID: 2708)

Fetching Species:   0%|          | 41/13683 [01:35<8:46:34,  2.32s/it]

Added new genus: Hop (ID: 2709)

Fetching Species:   0%|          | 42/13683 [01:38<8:34:46,  2.26s/it]

Added new genus: Cannabis (ID: 2710)

Fetching Species:   0%|          | 44/13683 [01:42<8:26:41,  2.23s/it]

Added new genus: Rhizoctonia (ID: 2711)

Fetching Species:   0%|          | 45/13683 [01:44<8:40:06,  2.29s/it]

Added new genus: Fusarium (ID: 2712)

Fetching Species:   0%|          | 46/13683 [01:47<8:30:02,  2.24s/it]

Added new genus: Rosellinia (ID: 2713)

Fetching Species:   0%|          | 48/13683 [01:51<8:32:25,  2.25s/it]

Added new genus: Primula (ID: 2714)

Fetching Species:   0%|          | 50/13683 [01:56<8:43:05,  2.30s/it]

Added new genus: Pleurotus (ID: 2715)

Fetching Species:   0%|          | 51/13683 [01:58<8:31:42,  2.25s/it]

Added new genus: Dill (ID: 2716)

Fetching Species:   0%|          | 52/13683 [02:00<8:26:41,  2.23s/it]

Added new genus: Red (ID: 2717)

Fetching Species:   0%|          | 53/13683 [02:02<8:21:51,  2.21s/it]

Added new genus: White (ID: 2718)

Fetching Species:   0%|          | 54/13683 [02:04<8:17:51,  2.19s/it]

Added new genus: Verticillium (ID: 2719)

Fetching Species:   0%|          | 55/13683 [02:07<8:15:16,  2.18s/it]

Added new genus: Spinach (ID: 2720)

Fetching Species:   0%|          | 58/13683 [02:13<8:19:11,  2.20s/it]

Added new genus: Discula (ID: 2721)

Fetching Species:   0%|          | 59/13683 [02:15<8:16:07,  2.18s/it]

Added new genus: Ophiostoma (ID: 2722)

Fetching Species:   0%|          | 61/13683 [02:20<8:20:24,  2.20s/it]

Added new genus: Aspergillus (ID: 2723)

Fetching Species:   0%|          | 62/13683 [02:22<8:19:37,  2.20s/it]

Added new genus: Pythium (ID: 2724)

Fetching Species:   0%|          | 64/13683 [02:26<8:23:31,  2.22s/it]

Added new genus: Gremmeniella (ID: 2725)

Fetching Species:   0%|          | 65/13683 [02:29<8:19:42,  2.20s/it]

Added new genus: Penicillium (ID: 2726)

Fetching Species:   0%|          | 67/13683 [02:33<8:12:20,  2.17s/it]

Added new genus: Chondrostereum (ID: 2727)

Fetching Species:   0%|          | 68/13683 [02:35<8:21:47,  2.21s/it]

Added new genus: Flammulina (ID: 2728)

Fetching Species:   1%|          | 70/13683 [02:40<8:34:25,  2.27s/it]

Added new genus: Beet (ID: 2729)

Fetching Species:   1%|          | 71/13683 [02:42<8:36:16,  2.28s/it]

Added new genus: Helicobasidium (ID: 2730)

Fetching Species:   1%|          | 73/13683 [02:46<8:21:14,  2.21s/it]

Added new genus: Carrot (ID: 2731)

Fetching Species:   1%|          | 77/13683 [02:55<8:19:38,  2.20s/it]

Added new genus: Vicia (ID: 2732)

Fetching Species:   1%|          | 78/13683 [02:57<8:25:07,  2.23s/it]

Added new genus: Medicago (ID: 2733)

Fetching Species:   1%|          | 81/13683 [03:04<8:43:04,  2.31s/it]

Added new genus: Cherry (ID: 2734)

Fetching Species:   1%|          | 85/13683 [03:15<9:04:58,  2.40s/it]

Added new genus: Fig (ID: 2735)

Fetching Species:   1%|          | 86/13683 [03:17<8:56:08,  2.37s/it]

Added new genus: Pepper (ID: 2736)

Fetching Species:   1%|          | 88/13683 [03:21<8:30:20,  2.25s/it]

Added new genus: Pseudogymnoascus (ID: 2737)

Fetching Species:   1%|          | 89/13683 [03:23<8:23:33,  2.22s/it]

Added new genus: Fragaria (ID: 2738)

Fetching Species:   1%|          | 90/13683 [03:26<8:28:44,  2.25s/it]

Added new genus: Raphanus (ID: 2739)

Fetching Species:   1%|          | 91/13683 [03:28<8:22:17,  2.22s/it]

Added new genus: Sclerotinia (ID: 2740)

Fetching Species:   1%|          | 92/13683 [03:30<8:17:17,  2.20s/it]

Added new genus: Botryotinia (ID: 2741)

Fetching Species:   1%|          | 93/13683 [03:32<8:21:49,  2.22s/it]

Added new genus: Bipolaris (ID: 2742)

Fetching Species:   1%|          | 95/13683 [03:37<8:34:50,  2.27s/it]

Added new genus: Ustilaginoidea (ID: 2743)

Fetching Species:   1%|          | 96/13683 [03:39<8:39:23,  2.29s/it]

Added new genus: Sophora (ID: 2744)

Fetching Species:   1%|          | 97/13683 [03:41<8:28:59,  2.25s/it]

Added new genus: Sinapis (ID: 2745)

Fetching Species:   1%|          | 101/13683 [03:50<8:09:48,  2.16s/it]

Added new genus: Rose (ID: 2746)

Fetching Species:   1%|          | 103/13683 [03:54<8:24:42,  2.23s/it]

Added new genus: Melon (ID: 2747)

Fetching Species:   1%|          | 104/13683 [03:57<8:19:39,  2.21s/it]

Added new genus: Persimmon (ID: 2748)

Fetching Species:   1%|          | 105/13683 [03:59<9:00:52,  2.39s/it]

Added new genus: Carnation (ID: 2749)

Fetching Species:   1%|          | 110/13683 [04:10<8:14:45,  2.19s/it]

Added new genus: Cryptosporidium (ID: 2750)

Fetching Species:   1%|          | 111/13683 [04:12<8:11:09,  2.17s/it]

Added new genus: Arabidopsis (ID: 2751)

Fetching Species:   1%|          | 136/13683 [05:11<8:38:21,  2.30s/it]

Added new genus: Setosphaeria (ID: 2752)

Fetching Species:   1%|          | 137/13683 [05:14<8:47:16,  2.34s/it]

Added new genus: Sclerotium (ID: 2753)

Fetching Species:   1%|          | 143/13683 [05:29<9:46:44,  2.60s/it]

Added new genus: Phomopsis (ID: 2754)

Fetching Species:   1%|          | 152/13683 [05:50<8:42:34,  2.32s/it]

Added new genus: Trichoderma (ID: 2755)

Fetching Species:   1%|          | 155/13683 [05:57<8:18:15,  2.21s/it]

Added new genus: Curvularia (ID: 2756)

Fetching Species:   1%|          | 156/13683 [05:59<8:22:47,  2.23s/it]

Added new genus: Porcine (ID: 2757)

Fetching Species:   1%|          | 159/13683 [06:06<8:14:49,  2.20s/it]

Added new genus: 2015 (ID: 2758)

Fetching Species:   1%|          | 160/13683 [06:07<7:26:54,  1.98s/it]

Added new genus: Otarine (ID: 2759)

Fetching Species:   1%|          | 161/13683 [06:09<7:47:20,  2.07s/it]

Added new genus: Rabbit (ID: 2760)

Fetching Species:   1%|          | 162/13683 [06:12<8:04:54,  2.15s/it]

Added new genus: Chicken (ID: 2761)

Fetching Species:   1%|          | 165/13683 [06:18<7:43:40,  2.06s/it]

Added new genus: Festuca (ID: 2762)

Fetching Species:   1%|▏         | 175/13683 [06:40<8:27:04,  2.25s/it]

Added new genus: Camellia (ID: 2763)

Fetching Species:   1%|▏         | 176/13683 [06:42<8:20:32,  2.22s/it]

Added new genus: Capsicum (ID: 2764)

Fetching Species:   1%|▏         | 178/13683 [06:47<8:21:05,  2.23s/it]

Added new genus: Salvia (ID: 2765)

Fetching Species:   1%|▏         | 179/13683 [06:49<8:34:36,  2.29s/it]

Added new genus: Erigeron (ID: 2766)

Fetching Species:   1%|▏         | 180/13683 [06:51<8:35:32,  2.29s/it]

Added new genus: Anthoxanthum (ID: 2767)

Fetching Species:   1%|▏         | 181/13683 [06:54<8:36:49,  2.30s/it]

Added new genus: Phalaenopsis (ID: 2768)

Fetching Species:   1%|▏         | 183/13683 [06:58<8:27:02,  2.25s/it]

Added new genus: Antonospora (ID: 2769)

Fetching Species:   1%|▏         | 186/13683 [07:05<8:12:22,  2.19s/it]

Added new genus: Cleome (ID: 2770)

Fetching Species:   1%|▏         | 187/13683 [07:08<9:29:17,  2.53s/it]

Added new genus: Sanxia (ID: 2771)

Fetching Species:   1%|▏         | 188/13683 [07:10<9:13:15,  2.46s/it]

Added new genus: Sapporo (ID: 2772)

Fetching Species:   1%|▏         | 189/13683 [07:13<9:03:54,  2.42s/it]

Added new genus: Bat (ID: 2773)

Fetching Species:   1%|▏         | 190/13683 [07:15<8:57:12,  2.39s/it]

Added new genus: HK (ID: 2774)

Fetching Species:   1%|▏         | 191/13683 [07:16<7:57:07,  2.12s/it]

Added new genus: Norwalk (ID: 2775)

Fetching Species:   1%|▏         | 192/13683 [07:19<8:08:15,  2.17s/it]

Added new genus: Primate (ID: 2776)

Fetching Species:   1%|▏         | 193/13683 [07:21<8:15:24,  2.20s/it]

Added new genus: Marmot (ID: 2777)

Fetching Species:   1%|▏         | 194/13683 [07:23<8:33:08,  2.28s/it]

Added new genus: Mink (ID: 2778)

Fetching Species:   1%|▏         | 195/13683 [07:26<9:10:40,  2.45s/it]

Added new genus: Canine (ID: 2779)

Fetching Species:   1%|▏         | 196/13683 [07:29<8:59:08,  2.40s/it]

Added new genus: 2012 (ID: 2780)

Fetching Species:   1%|▏         | 197/13683 [07:30<8:15:35,  2.20s/it]

Added new genus: San (ID: 2781)

Fetching Species:   1%|▏         | 198/13683 [07:33<8:21:10,  2.23s/it]

Added new genus: Hom-1 (ID: 2782)

Fetching Species:   1%|▏         | 199/13683 [07:35<8:23:40,  2.24s/it]

Added new genus: Feline (ID: 2783)

Fetching Species:   1%|▏         | 200/13683 [07:37<8:17:11,  2.21s/it]

Added new genus: Vesicular (ID: 2784)

Fetching Species:   1%|▏         | 201/13683 [07:39<8:25:11,  2.25s/it]

Added new genus: Steller (ID: 2785)

Fetching Species:   1%|▏         | 204/13683 [07:46<8:30:42,  2.27s/it]

Added new genus: Goose (ID: 2786)

Fetching Species:   1%|▏         | 205/13683 [07:49<8:40:41,  2.32s/it]

Added new genus: Bovine (ID: 2787)

Fetching Species:   2%|▏         | 206/13683 [07:51<8:51:44,  2.37s/it]

Added new genus: Newbury (ID: 2788)

Fetching Species:   2%|▏         | 208/13683 [07:57<9:47:21,  2.62s/it]

Added new genus: Calicivirus (ID: 2789)

Fetching Species:   2%|▏         | 210/13683 [08:01<9:11:58,  2.46s/it]

Added new genus: European (ID: 2790)

Fetching Species:   2%|▏         | 212/13683 [08:06<8:58:51,  2.40s/it]

Added new genus: 2004 (ID: 2791)

Fetching Species:   2%|▏         | 213/13683 [08:07<7:57:41,  2.13s/it]

Added new genus: Nordland (ID: 2792)

Fetching Species:   2%|▏         | 215/13683 [08:13<9:03:40,  2.42s/it]

Added new genus: St-Valerien (ID: 2793)

Fetching Species:   2%|▏         | 216/13683 [08:15<8:54:07,  2.38s/it]

Added new genus: Bavaria (ID: 2794)

Fetching Species:   2%|▏         | 217/13683 [08:18<9:36:14,  2.57s/it]

Added new genus: Tomato (ID: 2795)

Fetching Species:   2%|▏         | 223/13683 [08:32<8:43:58,  2.34s/it]

Added new genus: Cassava (ID: 2796)

Fetching Species:   2%|▏         | 248/13683 [09:31<8:39:01,  2.32s/it]

Added new genus: Anemone (ID: 2797)

Fetching Species:   2%|▏         | 254/13683 [09:44<8:33:34,  2.29s/it]

Added new genus: Petunia (ID: 2798)

Fetching Species:   2%|▏         | 276/13683 [10:36<9:31:34,  2.56s/it]

Added new genus: Turnip (ID: 2799)

Fetching Species:   2%|▏         | 299/13683 [11:28<8:28:56,  2.28s/it]

Added new genus: Sweetbriar (ID: 2800)

Fetching Species:   2%|▏         | 319/13683 [12:15<8:38:20,  2.33s/it]

Added new genus: Melegrivirus (ID: 2801)

Fetching Species:   2%|▏         | 325/13683 [12:29<8:16:01,  2.23s/it]

Added new genus: Rhinovirus (ID: 2802)

Fetching Species:   2%|▏         | 329/13683 [12:38<8:10:05,  2.20s/it]

Added new genus: Sichuan (ID: 2803)

Fetching Species:   2%|▏         | 335/13683 [12:51<8:35:32,  2.32s/it]

Added new genus: JL14 (ID: 2804)

Fetching Species:   2%|▏         | 338/13683 [12:58<8:15:44,  2.23s/it]

Added new genus: Yak (ID: 2805)

Fetching Species:   3%|▎         | 354/13683 [13:35<8:39:22,  2.34s/it]

Added new genus: 2010 (ID: 2806)

Fetching Species:   3%|▎         | 360/13683 [13:48<8:45:27,  2.37s/it]

Added new genus: Human (ID: 2807)

Fetching Species:   3%|▎         | 380/13683 [14:34<8:19:43,  2.25s/it]

Added new genus: Ovine (ID: 2808)

Fetching Species:   3%|▎         | 381/13683 [14:36<8:21:09,  2.26s/it]

Added new genus: Aimelvirus (ID: 2809)

Fetching Species:   3%|▎         | 382/13683 [14:39<9:30:27,  2.57s/it]

Added new genus: Cadicivirus (ID: 2810)

Fetching Species:   3%|▎         | 390/13683 [14:58<9:10:05,  2.48s/it]

Added new genus: Tupaia (ID: 2811)

Fetching Species:   3%|▎         | 401/13683 [15:24<8:53:37,  2.41s/it]

Added new genus: GV (ID: 2812)

Fetching Species:   3%|▎         | 417/13683 [16:02<8:56:13,  2.43s/it]

Added new genus: Foot-and-mouth (ID: 2813)

Fetching Species:   3%|▎         | 418/13683 [16:05<8:56:38,  2.43s/it]

Added new genus: Equine (ID: 2814)

Fetching Species:   3%|▎         | 436/13683 [16:46<8:35:13,  2.33s/it]

Added new genus: AsV (ID: 2815)

Fetching Species:   3%|▎         | 439/13683 [16:52<7:48:32,  2.12s/it]

Added new genus: Washington (ID: 2816)

Fetching Species:   3%|▎         | 446/13683 [17:07<7:51:36,  2.14s/it]

Added new genus: Rhimavirus (ID: 2817)

Fetching Species:   3%|▎         | 447/13683 [17:09<7:50:50,  2.13s/it]

Added new genus: Tortoise (ID: 2818)

Fetching Species:   3%|▎         | 450/13683 [17:16<7:57:24,  2.16s/it]

Added new genus: Falcon (ID: 2819)

Fetching Species:   3%|▎         | 458/13683 [17:34<8:18:48,  2.26s/it]

Added new genus: Fur (ID: 2820)

Fetching Species:   3%|▎         | 477/13683 [18:18<8:28:39,  2.31s/it]

Added new genus: Pigeon (ID: 2821)

Fetching Species:   4%|▎         | 481/13683 [18:27<8:24:23,  2.29s/it]

Added new genus: Cyprivirus (ID: 2822)

Fetching Species:   4%|▎         | 484/13683 [18:34<8:24:44,  2.29s/it]

Added new genus: Picornaviridae (ID: 2823)

Fetching Species:   4%|▎         | 487/13683 [18:41<8:44:57,  2.39s/it]

Added new genus: Heliconius (ID: 2824)

Fetching Species:   4%|▎         | 488/13683 [18:43<8:37:46,  2.35s/it]

Added new genus: Varroa (ID: 2825)

Fetching Species:   4%|▎         | 494/13683 [18:58<9:16:55,  2.53s/it]

Added new genus: Armigeres (ID: 2826)

Fetching Species:   4%|▎         | 497/13683 [19:05<8:39:38,  2.36s/it]

Added new genus: Diamondback (ID: 2827)

Fetching Species:   4%|▎         | 499/13683 [19:10<8:39:33,  2.36s/it]

Added new genus: Psammotettix (ID: 2828)

Fetching Species:   4%|▎         | 500/13683 [19:12<8:43:10,  2.38s/it]

Added new genus: Bombyx (ID: 2829)

Fetching Species:   4%|▎         | 503/13683 [19:19<8:28:46,  2.32s/it]

Added new genus: Moku (ID: 2830)

Fetching Species:   4%|▎         | 505/13683 [19:24<8:24:10,  2.30s/it]

Added new genus: Helicoverpa (ID: 2831)

Fetching Species:   4%|▎         | 509/13683 [19:33<9:05:17,  2.48s/it]

Added new genus: Formica (ID: 2832)

Fetching Species:   4%|▎         | 513/13683 [19:43<8:36:53,  2.35s/it]

Added new genus: Halyomorpha (ID: 2833)

Fetching Species:   4%|▍         | 514/13683 [19:45<8:31:36,  2.33s/it]

Added new genus: Chequa (ID: 2834)

Fetching Species:   4%|▍         | 515/13683 [19:47<8:28:19,  2.32s/it]

Added new genus: Culex (ID: 2835)

Fetching Species:   4%|▍         | 516/13683 [19:50<8:26:06,  2.31s/it]

Added new genus: Euscelidius (ID: 2836)

Fetching Species:   4%|▍         | 518/13683 [19:54<8:37:08,  2.36s/it]

Added new genus: Thaumetopoea (ID: 2837)

Fetching Species:   4%|▍         | 519/13683 [19:57<8:33:16,  2.34s/it]

Added new genus: King (ID: 2838)

Fetching Species:   4%|▍         | 520/13683 [19:59<8:29:36,  2.32s/it]

Added new genus: La (ID: 2839)

Fetching Species:   4%|▍         | 521/13683 [20:01<8:27:01,  2.31s/it]

Added new genus: Laodelphax (ID: 2840)

Fetching Species:   4%|▍         | 522/13683 [20:04<8:29:40,  2.32s/it]

Added new genus: Nesidiocoris (ID: 2841)

Fetching Species:   4%|▍         | 524/13683 [20:08<8:33:59,  2.34s/it]

Added new genus: Nilaparvata (ID: 2842)

Fetching Species:   4%|▍         | 525/13683 [20:11<8:28:53,  2.32s/it]

Added new genus: Opsiphanes (ID: 2843)

Fetching Species:   4%|▍         | 526/13683 [20:13<8:57:24,  2.45s/it]

Added new genus: Pityohyphantes (ID: 2844)

Fetching Species:   4%|▍         | 527/13683 [20:16<8:55:12,  2.44s/it]

Added new genus: Graminella (ID: 2845)

Fetching Species:   4%|▍         | 529/13683 [20:20<8:36:45,  2.36s/it]

Added new genus: Yongsan (ID: 2846)

Fetching Species:   4%|▍         | 533/13683 [20:30<8:52:31,  2.43s/it]

Added new genus: Britarnavirus (ID: 2847)

Fetching Species:   4%|▍         | 534/13683 [20:33<9:02:20,  2.47s/it]

Added new genus: Palmarnavirus (ID: 2848)

Fetching Species:   4%|▍         | 536/13683 [20:38<8:56:01,  2.45s/it]

Added new genus: Chaetenuissarnavirus (ID: 2849)

Fetching Species:   4%|▍         | 537/13683 [20:40<8:56:14,  2.45s/it]

Added new genus: Chaetarnavirus (ID: 2850)

Fetching Species:   4%|▍         | 538/13683 [20:43<9:26:06,  2.58s/it]

Added new genus: Jericarnavirus (ID: 2851)

Fetching Species:   4%|▍         | 539/13683 [20:45<9:06:49,  2.50s/it]

Added new genus: Chaetoceros (ID: 2852)

Fetching Species:   4%|▍         | 540/13683 [20:47<8:53:31,  2.44s/it]

Added new genus: Rhizosolenia (ID: 2853)

Fetching Species:   4%|▍         | 543/13683 [20:55<8:44:19,  2.39s/it]

Added new genus: Sanfarnavirus (ID: 2854)

Fetching Species:   4%|▍         | 550/13683 [21:11<8:32:42,  2.34s/it]

Added new genus: Aurantiochytrium (ID: 2855)

Fetching Species:   4%|▍         | 551/13683 [21:13<8:34:46,  2.35s/it]

Added new genus: Heterosigma (ID: 2856)

Fetching Species:   4%|▍         | 552/13683 [21:16<8:35:08,  2.35s/it]

Added new genus: Astarnavirus (ID: 2857)

Fetching Species:   4%|▍         | 553/13683 [21:18<8:29:44,  2.33s/it]

Added new genus: Lasius (ID: 2858)

Fetching Species:   4%|▍         | 555/13683 [21:22<8:21:43,  2.29s/it]

Added new genus: Solenopsis (ID: 2859)

Fetching Species:   4%|▍         | 556/13683 [21:25<8:20:09,  2.29s/it]

Added new genus: Shuangao (ID: 2860)

Fetching Species:   4%|▍         | 557/13683 [21:27<8:32:20,  2.34s/it]

Added new genus: Myrmica (ID: 2861)

Fetching Species:   4%|▍         | 560/13683 [21:34<8:36:04,  2.36s/it]

Added new genus: Hubei (ID: 2862)

Fetching Species:   4%|▍         | 562/13683 [21:39<8:28:07,  2.32s/it]

Added new genus: Biomphalaria (ID: 2863)

Fetching Species:   4%|▍         | 563/13683 [21:41<8:24:47,  2.31s/it]

Added new genus: Picorna-like (ID: 2864)

Fetching Species:   4%|▍         | 564/13683 [21:44<8:31:47,  2.34s/it]

Added new genus: Antarctic (ID: 2865)

Fetching Species:   4%|▍         | 565/13683 [21:46<8:27:38,  2.32s/it]

Added new genus: Husa-like (ID: 2866)

Fetching Species:   4%|▍         | 567/13683 [21:51<8:30:59,  2.34s/it]

Added new genus: Suncus (ID: 2867)

Fetching Species:   4%|▍         | 571/13683 [21:59<8:18:51,  2.28s/it]

Added new genus: HUN (ID: 2868)

Fetching Species:   4%|▍         | 572/13683 [22:01<7:27:33,  2.05s/it]

Added new genus: Aphis (ID: 2869)

Fetching Species:   4%|▍         | 573/13683 [22:04<8:01:35,  2.20s/it]

Added new genus: Anopheles (ID: 2870)

Fetching Species:   4%|▍         | 587/13683 [22:37<8:25:39,  2.32s/it]

Added new genus: Bivalve (ID: 2871)

Fetching Species:   4%|▍         | 589/13683 [22:41<8:11:52,  2.25s/it]

Added new genus: Centovirus (ID: 2872)

Fetching Species:   4%|▍         | 590/13683 [22:43<8:12:41,  2.26s/it]

Added new genus: Apis (ID: 2873)

Fetching Species:   4%|▍         | 591/13683 [22:46<8:15:06,  2.27s/it]

Added new genus: Big (ID: 2874)

Fetching Species:   4%|▍         | 593/13683 [22:50<8:31:33,  2.34s/it]

Added new genus: Macrobrachium (ID: 2875)

Fetching Species:   4%|▍         | 596/13683 [22:58<8:39:24,  2.38s/it]

Added new genus: Nephila (ID: 2876)

Fetching Species:   4%|▍         | 601/13683 [23:09<8:33:59,  2.36s/it]

Added new genus: Nylanderia (ID: 2877)

Fetching Species:   4%|▍         | 602/13683 [23:12<8:28:23,  2.33s/it]

Added new genus: Riptortus (ID: 2878)

Fetching Species:   4%|▍         | 603/13683 [23:14<8:24:16,  2.31s/it]

Added new genus: Picornavirales (ID: 2879)

Fetching Species:   4%|▍         | 605/13683 [23:19<8:21:00,  2.30s/it]

Added new genus: Tioga (ID: 2880)

Fetching Species:   4%|▍         | 607/13683 [23:23<8:18:27,  2.29s/it]

Added new genus: Apodemus (ID: 2881)

Fetching Species:   4%|▍         | 608/13683 [23:25<8:18:30,  2.29s/it]

Added new genus: Delisea (ID: 2882)

Fetching Species:   4%|▍         | 609/13683 [23:28<8:17:56,  2.29s/it]

Added new genus: Yili (ID: 2883)

Fetching Species:   4%|▍         | 615/13683 [23:42<8:51:48,  2.44s/it]

Added new genus: Sugar (ID: 2884)

Fetching Species:   5%|▍         | 616/13683 [23:44<8:40:45,  2.39s/it]

Added new genus: Pingu (ID: 2885)

Fetching Species:   5%|▍         | 619/13683 [23:51<8:20:19,  2.30s/it]

Added new genus: Guangdong (ID: 2886)

Fetching Species:   5%|▍         | 620/13683 [23:53<8:09:54,  2.25s/it]

Added new genus: Blackbird (ID: 2887)

Fetching Species:   5%|▍         | 621/13683 [23:56<8:46:16,  2.42s/it]

Added new genus: Kilifi (ID: 2888)

Fetching Species:   5%|▍         | 624/13683 [24:04<9:15:35,  2.55s/it]

Added new genus: Sparrow (ID: 2889)

Fetching Species:   5%|▍         | 625/13683 [24:06<9:07:39,  2.52s/it]

Added new genus: Night (ID: 2890)

Fetching Species:   5%|▍         | 626/13683 [24:09<9:15:02,  2.55s/it]

Added new genus: Munia (ID: 2891)

Fetching Species:   5%|▍         | 627/13683 [24:11<9:07:18,  2.52s/it]

Added new genus: Bulbul (ID: 2892)

Fetching Species:   5%|▍         | 628/13683 [24:14<9:01:45,  2.49s/it]

Added new genus: Wigeon (ID: 2893)

Fetching Species:   5%|▍         | 629/13683 [24:16<8:58:15,  2.47s/it]

Added new genus: White-eye (ID: 2894)

Fetching Species:   5%|▍         | 630/13683 [24:19<8:55:35,  2.46s/it]

Added new genus: Magpie-robin (ID: 2895)

Fetching Species:   5%|▍         | 631/13683 [24:21<8:53:50,  2.45s/it]

Added new genus: Common (ID: 2896)

Fetching Species:   5%|▍         | 632/13683 [24:23<8:52:13,  2.45s/it]

Added new genus: Coronavirus (ID: 2897)

Fetching Species:   5%|▍         | 633/13683 [24:26<8:51:34,  2.44s/it]

Added new genus: Thrush (ID: 2898)

Fetching Species:   5%|▍         | 634/13683 [24:28<8:50:27,  2.44s/it]

Added new genus: Shrew (ID: 2899)

Fetching Species:   5%|▍         | 637/13683 [24:35<8:49:49,  2.44s/it]

Added new genus: Wencheng (ID: 2900)

Fetching Species:   5%|▍         | 640/13683 [24:43<8:59:00,  2.48s/it]

Added new genus: Rhinolophus (ID: 2901)

Fetching Species:   5%|▍         | 641/13683 [24:45<8:55:55,  2.47s/it]

Added new genus: Nyctalus (ID: 2902)

Fetching Species:   5%|▍         | 645/13683 [24:55<8:45:50,  2.42s/it]

Added new genus: Ferret (ID: 2903)

Fetching Species:   5%|▍         | 646/13683 [24:57<8:36:55,  2.38s/it]

Added new genus: Miniopterus (ID: 2904)

Fetching Species:   5%|▍         | 649/13683 [25:05<8:34:09,  2.37s/it]

Added new genus: YN2012 (ID: 2905)

Fetching Species:   5%|▍         | 656/13683 [25:20<8:27:59,  2.34s/it]

Added new genus: Pipistrellus (ID: 2906)

Fetching Species:   5%|▍         | 657/13683 [25:23<8:39:00,  2.39s/it]

Added new genus: Lucheng (ID: 2907)

Fetching Species:   5%|▍         | 658/13683 [25:25<8:22:54,  2.32s/it]

Added new genus: NL63-related (ID: 2908)

Fetching Species:   5%|▍         | 659/13683 [25:27<8:20:49,  2.31s/it]

Added new genus: Myotis (ID: 2909)

Fetching Species:   5%|▍         | 662/13683 [25:34<8:35:42,  2.38s/it]

Added new genus: Middle (ID: 2910)

Fetching Species:   5%|▍         | 663/13683 [25:37<8:39:02,  2.39s/it]

Added new genus: China (ID: 2911)

Fetching Species:   5%|▍         | 664/13683 [25:39<8:41:23,  2.40s/it]

Added new genus: Hedgehog (ID: 2912)

Fetching Species:   5%|▍         | 665/13683 [25:42<8:52:12,  2.45s/it]

Added new genus: Murine (ID: 2913)

Fetching Species:   5%|▍         | 666/13683 [25:44<8:31:20,  2.36s/it]

Added new genus: Tylonycteris (ID: 2914)

Fetching Species:   5%|▍         | 667/13683 [25:46<8:26:03,  2.33s/it]

Added new genus: 2008 (ID: 2915)

Fetching Species:   5%|▍         | 669/13683 [25:50<7:54:23,  2.19s/it]

Added new genus: Rousettus (ID: 2916)

Fetching Species:   5%|▍         | 671/13683 [25:55<8:28:47,  2.35s/it]

Added new genus: Severe (ID: 2917)

Fetching Species:   5%|▍         | 674/13683 [26:03<9:15:49,  2.56s/it]

Added new genus: Beluga (ID: 2918)

Fetching Species:   5%|▍         | 675/13683 [26:06<8:49:12,  2.44s/it]

Added new genus: Avian (ID: 2919)

Fetching Species:   5%|▍         | 676/13683 [26:08<8:49:01,  2.44s/it]

Added new genus: Canada (ID: 2920)

Fetching Species:   5%|▍         | 678/13683 [26:13<9:09:19,  2.53s/it]

Added new genus: Rodent (ID: 2921)

Fetching Species:   5%|▍         | 684/13683 [26:27<8:30:57,  2.36s/it]

Added new genus: Chinook (ID: 2922)

Fetching Species:   5%|▌         | 685/13683 [26:30<8:38:28,  2.39s/it]

Added new genus: Serpentovirinae (ID: 2923)

Fetching Species:   5%|▌         | 688/13683 [26:37<8:51:48,  2.46s/it]

Added new genus: Goat (ID: 2924)

Fetching Species:   5%|▌         | 696/13683 [26:58<9:12:01,  2.55s/it]

Added new genus: Fathead (ID: 2925)

Fetching Species:   5%|▌         | 697/13683 [27:00<9:02:37,  2.51s/it]

Added new genus: Hebius (ID: 2926)

Fetching Species:   5%|▌         | 717/13683 [27:49<8:56:58,  2.48s/it]

Added new genus: Southwest (ID: 2927)

Fetching Species:   5%|▌         | 730/13683 [28:20<8:28:53,  2.36s/it]

Added new genus: Insemevirus (ID: 2928)

Fetching Species:   5%|▌         | 732/13683 [28:25<8:26:33,  2.35s/it]

Added new genus: Aplysia (ID: 2929)

Fetching Species:   5%|▌         | 736/13683 [28:34<8:31:17,  2.37s/it]

Added new genus: Chinturpovirus (ID: 2930)

Fetching Species:   5%|▌         | 738/13683 [28:39<8:34:53,  2.39s/it]

Added new genus: Oligodon (ID: 2931)

Fetching Species:   5%|▌         | 739/13683 [28:41<8:28:52,  2.36s/it]

Added new genus: Planidovirus (ID: 2932)

Fetching Species:   5%|▌         | 740/13683 [28:44<8:47:29,  2.45s/it]

Added new genus: Halfbeak (ID: 2933)

Fetching Species:   5%|▌         | 741/13683 [28:46<8:45:40,  2.44s/it]

Added new genus: Ptyasnivirus (ID: 2934)

Fetching Species:   5%|▌         | 743/13683 [28:51<8:37:42,  2.40s/it]

Added new genus: Decronivirus (ID: 2935)

Fetching Species:   5%|▌         | 746/13683 [28:58<8:50:16,  2.46s/it]

Added new genus: Botrylloides (ID: 2936)

Fetching Species:   5%|▌         | 747/13683 [29:01<8:47:48,  2.45s/it]

Added new genus: Nangarvirus (ID: 2937)

Fetching Species:   5%|▌         | 748/13683 [29:03<8:51:33,  2.47s/it]

Added new genus: Ixeridium (ID: 2938)

Fetching Species:   5%|▌         | 749/13683 [29:06<8:49:07,  2.45s/it]

Added new genus: Luffa (ID: 2939)

Fetching Species:   5%|▌         | 750/13683 [29:08<8:29:01,  2.36s/it]

Added new genus: Strawberry (ID: 2940)

Fetching Species:   5%|▌         | 752/13683 [29:13<8:24:33,  2.34s/it]

Added new genus: Barley (ID: 2941)

Fetching Species:   6%|▌         | 754/13683 [29:17<8:02:06,  2.24s/it]

Added new genus: Potato (ID: 2942)

Fetching Species:   6%|▌         | 755/13683 [29:19<7:55:55,  2.21s/it]

Added new genus: Sugarcane (ID: 2943)

Fetching Species:   6%|▌         | 756/13683 [29:21<8:00:51,  2.23s/it]

Added new genus: Phasey (ID: 2944)

Fetching Species:   6%|▌         | 758/13683 [29:26<8:05:56,  2.26s/it]

Added new genus: Maize (ID: 2945)

Fetching Species:   6%|▌         | 761/13683 [29:33<8:13:56,  2.29s/it]

Added new genus: Wheat (ID: 2946)

Fetching Species:   6%|▌         | 763/13683 [29:37<8:12:14,  2.29s/it]

Added new genus: Cotton (ID: 2947)

Fetching Species:   6%|▌         | 764/13683 [29:40<8:20:41,  2.33s/it]

Added new genus: Cereal (ID: 2948)

Fetching Species:   6%|▌         | 767/13683 [29:46<8:06:40,  2.26s/it]

Added new genus: Tobacco (ID: 2949)

Fetching Species:   6%|▌         | 769/13683 [29:51<8:01:16,  2.24s/it]

Added new genus: Sauropus (ID: 2950)

Fetching Species:   6%|▌         | 770/13683 [29:54<9:03:12,  2.52s/it]

Added new genus: Cowpea (ID: 2951)

Fetching Species:   6%|▌         | 772/13683 [29:59<9:04:30,  2.53s/it]

Added new genus: Suakwa (ID: 2952)

Fetching Species:   6%|▌         | 773/13683 [30:01<8:49:21,  2.46s/it]

Added new genus: Cucurbit (ID: 2953)

Fetching Species:   6%|▌         | 774/13683 [30:04<8:29:22,  2.37s/it]

Added new genus: Pepo (ID: 2954)

Fetching Species:   6%|▌         | 775/13683 [30:06<8:23:42,  2.34s/it]

Added new genus: African (ID: 2955)

Fetching Species:   6%|▌         | 778/13683 [30:13<8:11:55,  2.29s/it]

Added new genus: Pumpkin (ID: 2956)

Fetching Species:   6%|▌         | 781/13683 [30:19<8:10:12,  2.28s/it]

Added new genus: Faba (ID: 2957)

Fetching Species:   6%|▌         | 784/13683 [30:27<8:34:44,  2.39s/it]

Added new genus: Chickpea (ID: 2958)

Fetching Species:   6%|▌         | 785/13683 [30:29<8:18:32,  2.32s/it]

Added new genus: Citrus (ID: 2959)

Fetching Species:   6%|▌         | 787/13683 [30:34<8:52:35,  2.48s/it]

Added new genus: Pea (ID: 2960)

Fetching Species:   6%|▌         | 788/13683 [30:37<8:39:13,  2.42s/it]

Added new genus: Grapevine (ID: 2961)

Fetching Species:   6%|▌         | 790/13683 [30:41<8:23:26,  2.34s/it]

Added new genus: Papaya (ID: 2962)

Fetching Species:   6%|▌         | 791/13683 [30:43<8:12:15,  2.29s/it]

Added new genus: Physalis (ID: 2963)

Fetching Species:   6%|▌         | 792/13683 [30:46<8:11:13,  2.29s/it]

Added new genus: Southern (ID: 2964)

Fetching Species:   6%|▌         | 793/13683 [30:48<8:01:29,  2.24s/it]

Added new genus: Lucerne (ID: 2965)

Fetching Species:   6%|▌         | 794/13683 [30:50<8:15:54,  2.31s/it]

Added new genus: Soybean (ID: 2966)

Fetching Species:   6%|▌         | 795/13683 [30:55<10:29:06,  2.93s/it]

Added new genus: Subterranean (ID: 2967)

Fetching Species:   6%|▌         | 796/13683 [30:57<9:51:45,  2.76s/it]

Added new genus: Sowbane (ID: 2968)

Fetching Species:   6%|▌         | 797/13683 [30:59<9:13:04,  2.58s/it]

Added new genus: Blueberry (ID: 2969)

Fetching Species:   6%|▌         | 798/13683 [31:01<8:55:14,  2.49s/it]

Added new genus: Sesbania (ID: 2970)

Fetching Species:   6%|▌         | 799/13683 [31:04<8:42:42,  2.43s/it]

Added new genus: Rice (ID: 2971)

Fetching Species:   6%|▌         | 800/13683 [31:06<8:32:01,  2.38s/it]

Added new genus: Velvet (ID: 2972)

Fetching Species:   6%|▌         | 802/13683 [31:11<8:26:54,  2.36s/it]

Added new genus: Imperata (ID: 2973)

Fetching Species:   6%|▌         | 804/13683 [31:15<8:02:41,  2.25s/it]

Added new genus: Rottboellia (ID: 2974)

Fetching Species:   6%|▌         | 805/13683 [31:18<8:35:54,  2.40s/it]

Added new genus: Artemisia (ID: 2975)

Fetching Species:   6%|▌         | 806/13683 [31:20<8:19:20,  2.33s/it]

Added new genus: Cocksfoot (ID: 2976)

Fetching Species:   6%|▌         | 807/13683 [31:22<8:29:05,  2.37s/it]

Added new genus: Cymbidium (ID: 2977)

Fetching Species:   6%|▌         | 808/13683 [31:24<8:15:02,  2.31s/it]

Added new genus: Solanum (ID: 2978)

Fetching Species:   6%|▌         | 809/13683 [31:27<8:05:00,  2.26s/it]

Added new genus: Ryegrass (ID: 2979)

Fetching Species:   6%|▌         | 811/13683 [31:31<8:08:55,  2.28s/it]

Added new genus: Poinsettia (ID: 2980)

Fetching Species:   6%|▌         | 812/13683 [31:33<7:59:20,  2.23s/it]

Added new genus: Groundnut (ID: 2981)

Fetching Species:   6%|▌         | 813/13683 [31:35<7:53:12,  2.21s/it]

Added new genus: Heterocapsa (ID: 2982)

Fetching Species:   6%|▌         | 814/13683 [31:38<8:33:16,  2.39s/it]

Added new genus: Mushroom (ID: 2983)

Fetching Species:   6%|▌         | 816/13683 [31:44<9:19:45,  2.61s/it]

Added new genus: Bastrovirus (ID: 2984)

Fetching Species:   6%|▌         | 818/13683 [31:48<8:47:39,  2.46s/it]

Added new genus: 17819_21 (ID: 2985)

Fetching Species:   6%|▌         | 820/13683 [31:52<7:43:18,  2.16s/it]

Added new genus: Burkina (ID: 2986)

Fetching Species:   6%|▌         | 821/13683 [31:56<9:07:05,  2.55s/it]

Added new genus: HMO (ID: 2987)

Fetching Species:   6%|▌         | 827/13683 [32:08<7:23:15,  2.07s/it]

Added new genus: Qinghai (ID: 2988)

Fetching Species:   6%|▌         | 835/13683 [32:27<8:08:04,  2.28s/it]

Added new genus: Dromedary (ID: 2989)

Fetching Species:   6%|▌         | 855/13683 [33:08<8:14:10,  2.31s/it]

Added new genus: Astrovirus (ID: 2990)

Fetching Species:   6%|▋         | 858/13683 [33:16<8:41:59,  2.44s/it]

Added new genus: Duck (ID: 2991)

Fetching Species:   6%|▋         | 860/13683 [33:20<8:20:25,  2.34s/it]

Added new genus: Turkey (ID: 2992)

Fetching Species:   6%|▋         | 867/13683 [33:36<7:31:27,  2.11s/it]

Added new genus: 17489_85 (ID: 2993)

Fetching Species:   6%|▋         | 868/13683 [33:37<6:51:38,  1.93s/it]

Added new genus: 2011 (ID: 2994)

Fetching Species:   7%|▋         | 901/13683 [34:53<8:06:08,  2.28s/it]

Error fetching Potyvirus ranunculitenuis: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 907/13683 [35:06<7:48:25,  2.20s/it]

Error fetching Pepper severe mosaic virus: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 910/13683 [35:13<7:55:49,  2.24s/it]

Error fetching Potyvirus batatalatentis: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 915/13683 [35:24<8:20:37,  2.35s/it]

Error fetching Potyvirus carotatenuifoli: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 917/13683 [35:29<8:02:49,  2.27s/it]

Added new genus: Araujia (ID: 2995)
Error fetching Araujia mosaic virus: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 918/13683 [35:31<7:43:20,  2.18s/it]

Added new genus: Leek (ID: 2996)
Error fetching Leek yellow stripe virus: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 925/13683 [35:46<8:01:26,  2.26s/it]

Error fetching Potyvirus begoniae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 926/13683 [35:48<7:42:14,  2.17s/it]

Error fetching Potyvirus dasheenis: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 927/13683 [35:50<7:28:46,  2.11s/it]

Error fetching Potyvirus tulipadefractum: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 929/13683 [35:55<7:38:53,  2.16s/it]

Error fetching Potyvirus cliviaflavilineae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 930/13683 [35:57<7:25:56,  2.10s/it]

Error fetching Potyvirus nippodioscoreae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 934/13683 [36:06<7:44:44,  2.19s/it]

Error fetching Potyvirus gebatatae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 937/13683 [36:12<7:31:41,  2.13s/it]

Error fetching Potyvirus nicotianavenamaculae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 939/13683 [36:16<7:35:22,  2.14s/it]

Error fetching Potyvirus polianthismaculae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 940/13683 [36:18<7:27:50,  2.11s/it]

Error fetching Potyvirus ranunculi: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 942/13683 [36:23<7:41:52,  2.18s/it]

Error fetching Potyvirus plumpoxi: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 946/13683 [36:32<8:15:54,  2.34s/it]

Added new genus: Shallot (ID: 2997)

Fetching Species:   7%|▋         | 948/13683 [36:36<8:10:15,  2.31s/it]

Added new genus: Euphorbia (ID: 2998)

Fetching Species:   7%|▋         | 951/13683 [36:43<7:59:47,  2.26s/it]

Error fetching Potyvirus polianthis: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 953/13683 [36:47<7:56:30,  2.25s/it]

Error fetching Potyvirus phaseovulgaris: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 954/13683 [36:49<7:42:18,  2.18s/it]

Added new genus: Celery (ID: 2999)

Fetching Species:   7%|▋         | 955/13683 [36:52<7:40:12,  2.17s/it]

Error fetching Potyvirus basellae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 956/13683 [36:53<7:27:33,  2.11s/it]

Error fetching Potyvirus narcissusdegeneris: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 957/13683 [36:55<7:19:02,  2.07s/it]

Error fetching Potyvirus musae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 958/13683 [36:57<7:12:46,  2.04s/it]

Error fetching Potyvirus citrulli: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 963/13683 [37:09<8:23:43,  2.38s/it]

Error fetching Potyvirus caricae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 964/13683 [37:11<7:57:27,  2.25s/it]

Error fetching Potyvirus trifolii: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 965/13683 [37:14<8:18:05,  2.35s/it]

Error fetching Potyvirus yituberosi: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 966/13683 [37:16<8:14:41,  2.33s/it]

Error fetching Potyvirus morindatessellati: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 968/13683 [37:20<7:54:36,  2.24s/it]

Error fetching Potyvirus lupinus: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 970/13683 [37:25<7:52:30,  2.23s/it]

Error fetching Potyvirus fountaingrassi: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 971/13683 [37:27<7:37:30,  2.16s/it]

Error fetching Potyvirus bidensia: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 973/13683 [37:31<7:27:17,  2.11s/it]

Error fetching Potyvirus nerinis: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 981/13683 [37:49<8:03:37,  2.28s/it]

Error fetching Potyvirus sorghitessellati: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 983/13683 [37:54<8:29:20,  2.41s/it]

Error fetching Potyvirus calistephi: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 984/13683 [37:56<8:02:06,  2.28s/it]

Error fetching Potyvirus phaseoluteum: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 985/13683 [37:58<7:42:06,  2.18s/it]

Error fetching Potyvirus vanillae: HTTP Error 400: Bad Request

Fetching Species:   7%|▋         | 988/13683 [38:04<7:45:54,  2.20s/it]

Added new genus: Butterfly (ID: 3000)

Fetching Species:   7%|▋         | 995/13683 [38:21<8:15:54,  2.35s/it]

Added new genus: Asparagus (ID: 3001)

Fetching Species:   7%|▋         | 1000/13683 [38:32<8:00:07,  2.27s/it]

Added new genus: Scallion (ID: 3002)

Fetching Species:   7%|▋         | 1013/13683 [39:02<8:23:06,  2.38s/it]

Added new genus: Donkey (ID: 3003)

Fetching Species:   7%|▋         | 1020/13683 [39:20<8:30:30,  2.42s/it]

Added new genus: Narcissus (ID: 3004)

Fetching Species:   7%|▋         | 1025/13683 [39:31<7:53:27,  2.24s/it]

Added new genus: Chinese (ID: 3005)

Fetching Species:   8%|▊         | 1028/13683 [39:38<7:54:30,  2.25s/it]

Added new genus: Arracacha (ID: 3006)

Fetching Species:   8%|▊         | 1030/13683 [39:42<7:48:17,  2.22s/it]

Added new genus: Wild (ID: 3007)

Fetching Species:   8%|▊         | 1034/13683 [39:53<8:57:56,  2.55s/it]

Added new genus: Amomum (ID: 3008)

Fetching Species:   8%|▊         | 1053/13683 [40:37<8:00:19,  2.28s/it]

Added new genus: Peanut (ID: 3009)

Fetching Species:   8%|▊         | 1062/13683 [40:58<8:09:06,  2.33s/it]

Added new genus: Areca (ID: 3010)

Fetching Species:   8%|▊         | 1064/13683 [41:03<8:15:47,  2.36s/it]

Added new genus: Oat (ID: 3011)

Fetching Species:   8%|▊         | 1065/13683 [41:05<8:11:01,  2.33s/it]

Added new genus: Yellow (ID: 3012)

Fetching Species:   8%|▊         | 1066/13683 [41:07<8:20:34,  2.38s/it]

Added new genus: Brome (ID: 3013)

Fetching Species:   8%|▊         | 1068/13683 [41:13<8:46:11,  2.50s/it]

Added new genus: Tall (ID: 3014)

Fetching Species:   8%|▊         | 1070/13683 [41:17<8:13:51,  2.35s/it]

Added new genus: Cardamom (ID: 3015)

Fetching Species:   8%|▊         | 1071/13683 [41:20<8:25:06,  2.40s/it]

Added new genus: Broad-leafed (ID: 3016)

Fetching Species:   8%|▊         | 1073/13683 [41:24<8:23:44,  2.40s/it]

Added new genus: Maclura (ID: 3017)

Fetching Species:   8%|▊         | 1074/13683 [41:27<8:15:24,  2.36s/it]

Added new genus: Yam (ID: 3018)

Fetching Species:   8%|▊         | 1075/13683 [41:29<8:21:59,  2.39s/it]

Added new genus: Artichoke (ID: 3019)

Fetching Species:   8%|▊         | 1087/13683 [41:57<8:01:46,  2.29s/it]

Added new genus: Passiflora (ID: 3020)

Fetching Species:   8%|▊         | 1089/13683 [42:02<7:52:51,  2.25s/it]

Added new genus: Triticum (ID: 3021)

Fetching Species:   8%|▊         | 1090/13683 [42:04<7:54:30,  2.26s/it]

Added new genus: Caladenia (ID: 3022)

Fetching Species:   8%|▊         | 1091/13683 [42:06<7:56:49,  2.27s/it]

Added new genus: Blackberry (ID: 3023)

Fetching Species:   8%|▊         | 1092/13683 [42:10<8:47:36,  2.51s/it]

Added new genus: Agropyron (ID: 3024)

Fetching Species:   8%|▊         | 1093/13683 [42:12<8:33:25,  2.45s/it]

Added new genus: Hordeum (ID: 3025)

Fetching Species:   8%|▊         | 1096/13683 [42:19<8:24:19,  2.40s/it]

Added new genus: Squash (ID: 3026)

Fetching Species:   8%|▊         | 1098/13683 [42:24<8:14:19,  2.36s/it]

Added new genus: Coccinia (ID: 3027)

Fetching Species:   8%|▊         | 1099/13683 [42:26<8:19:09,  2.38s/it]

Added new genus: Ugandan (ID: 3028)

Fetching Species:   8%|▊         | 1100/13683 [42:28<8:15:20,  2.36s/it]

Added new genus: Cucumber (ID: 3029)

Fetching Species:   8%|▊         | 1101/13683 [42:31<8:10:36,  2.34s/it]

Added new genus: Sweet (ID: 3030)

Fetching Species:   8%|▊         | 1103/13683 [42:37<9:02:27,  2.59s/it]

Added new genus: Longan (ID: 3031)

Fetching Species:   8%|▊         | 1104/13683 [42:39<9:24:15,  2.69s/it]

Added new genus: Spartina (ID: 3032)

Fetching Species:   8%|▊         | 1105/13683 [42:42<9:12:28,  2.64s/it]

Added new genus: Reed (ID: 3033)

Fetching Species:   8%|▊         | 1106/13683 [42:44<8:50:47,  2.53s/it]

Added new genus: Bellflower (ID: 3034)

Fetching Species:   8%|▊         | 1131/13683 [43:42<8:07:12,  2.33s/it]

Added new genus: Dhati (ID: 3035)

Fetching Species:   9%|▊         | 1173/13683 [45:21<8:08:50,  2.34s/it]

Added new genus: Alethinophid (ID: 3036)

Fetching Species:   9%|▊         | 1175/13683 [45:26<8:05:23,  2.33s/it]

Added new genus: Mopeia (ID: 3037)

Fetching Species:   9%|▊         | 1179/13683 [45:35<8:04:36,  2.33s/it]

Added new genus: Inner (ID: 3038)

Fetching Species:   9%|▊         | 1193/13683 [46:07<8:04:27,  2.33s/it]

Added new genus: Hantavirus (ID: 3039)

Fetching Species:   9%|▉         | 1221/13683 [47:13<8:00:58,  2.32s/it]

Added new genus: Percilovirus (ID: 3040)

Fetching Species:   9%|▉         | 1240/13683 [47:57<7:57:03,  2.30s/it]

Added new genus: Songling (ID: 3041)

Fetching Species:   9%|▉         | 1275/13683 [49:17<7:53:00,  2.29s/it]

Added new genus: Beiji (ID: 3042)

Fetching Species:  10%|▉         | 1334/13683 [51:38<7:59:14,  2.33s/it]

Added new genus: Bimiti (ID: 3043)

Fetching Species:  10%|█         | 1379/13683 [53:23<8:10:14,  2.39s/it]

Added new genus: Alajuela (ID: 3044)

Fetching Species:  10%|█         | 1392/13683 [53:53<7:53:41,  2.31s/it]

Added new genus: Mulberry (ID: 3045)

Fetching Species:  10%|█         | 1401/13683 [54:13<8:03:08,  2.36s/it]

Added new genus: Belem (ID: 3046)

Fetching Species:  10%|█         | 1415/13683 [54:46<7:58:08,  2.34s/it]

Added new genus: Hedi (ID: 3047)

Fetching Species:  11%|█         | 1446/13683 [55:58<7:48:01,  2.29s/it]

Added new genus: Frijoles (ID: 3048)

Fetching Species:  11%|█         | 1456/13683 [56:21<7:40:27,  2.26s/it]

Added new genus: Arrabida (ID: 3049)

Fetching Species:  11%|█         | 1464/13683 [56:39<7:49:39,  2.31s/it]

Added new genus: Pacific (ID: 3050)

Fetching Species:  11%|█         | 1471/13683 [56:56<7:57:28,  2.35s/it]

Added new genus: Huangpi (ID: 3051)

Fetching Species:  11%|█         | 1517/13683 [58:42<7:37:41,  2.26s/it]

Added new genus: Toyo (ID: 3052)

Fetching Species:  11%|█         | 1529/13683 [59:10<7:40:25,  2.27s/it]

Added new genus: Watermelon (ID: 3053)

Fetching Species:  11%|█▏        | 1551/13683 [1:00:01<7:44:27,  2.30s/it]

Added new genus: Coleopteran (ID: 3054)

Fetching Species:  11%|█▏        | 1559/13683 [1:00:20<7:51:25,  2.33s/it]

Added new genus: Seattle (ID: 3055)

Fetching Species:  11%|█▏        | 1567/13683 [1:00:39<7:54:24,  2.35s/it]

Added new genus: Nome (ID: 3056)

Fetching Species:  12%|█▏        | 1581/13683 [1:01:11<7:44:01,  2.30s/it]

Added new genus: Saesbyeol (ID: 3057)

Fetching Species:  12%|█▏        | 1583/13683 [1:01:15<7:47:47,  2.32s/it]

Added new genus: Fushun (ID: 3058)

Fetching Species:  12%|█▏        | 1584/13683 [1:01:18<7:45:04,  2.31s/it]

Added new genus: Insect (ID: 3059)

Fetching Species:  12%|█▏        | 1598/13683 [1:01:51<7:43:07,  2.30s/it]

Added new genus: Pistacia (ID: 3060)

Fetching Species:  12%|█▏        | 1600/13683 [1:01:55<7:27:05,  2.22s/it]

Added new genus: Karaka (ID: 3061)

Fetching Species:  12%|█▏        | 1642/13683 [1:03:29<7:33:36,  2.26s/it]

Added new genus: 2014 (ID: 3062)

Fetching Species:  12%|█▏        | 1651/13683 [1:03:49<7:37:50,  2.28s/it]

Added new genus: Turtle (ID: 3063)

Fetching Species:  12%|█▏        | 1655/13683 [1:03:58<7:43:17,  2.31s/it]

Added new genus: Athtab (ID: 3064)

Fetching Species:  12%|█▏        | 1703/13683 [1:05:50<7:57:04,  2.39s/it]

Added new genus: Joa (ID: 3065)

Fetching Species:  13%|█▎        | 1721/13683 [1:06:32<7:47:10,  2.34s/it]

Added new genus: Chrysanthemum (ID: 3066)

Fetching Species:  13%|█▎        | 1734/13683 [1:07:03<7:37:12,  2.30s/it]

Added new genus: Actinidia (ID: 3067)

Fetching Species:  13%|█▎        | 1827/13683 [1:10:43<7:40:49,  2.33s/it]

Added new genus: Tacheng (ID: 3068)

Fetching Species:  14%|█▍        | 1899/13683 [1:13:31<7:41:18,  2.35s/it]

Added new genus: Orgi (ID: 3069)

Fetching Species:  14%|█▍        | 1916/13683 [1:14:11<7:35:23,  2.32s/it]

Added new genus: Farmington (ID: 3070)

Fetching Species:  14%|█▍        | 1917/13683 [1:14:13<7:33:13,  2.31s/it]

Added new genus: Rhabdoviridae (ID: 3071)

Fetching Species:  14%|█▍        | 1922/13683 [1:14:25<7:35:13,  2.32s/it]

Added new genus: Green (ID: 3072)

Fetching Species:  14%|█▍        | 1924/13683 [1:14:30<7:32:26,  2.31s/it]

Added new genus: Wuhan (ID: 3073)

Fetching Species:  14%|█▍        | 1933/13683 [1:14:51<8:11:15,  2.51s/it]

Added new genus: Hymenopteran (ID: 3074)

Fetching Species:  14%|█▍        | 1934/13683 [1:14:53<8:09:02,  2.50s/it]

Added new genus: Merida-like (ID: 3075)

Fetching Species:  14%|█▍        | 1949/13683 [1:15:29<7:31:41,  2.31s/it]

Added new genus: Fox (ID: 3076)

Fetching Species:  14%|█▍        | 1950/13683 [1:15:31<7:30:24,  2.30s/it]

Added new genus: Xinjiang (ID: 3077)

Fetching Species:  14%|█▍        | 1955/13683 [1:15:43<7:44:32,  2.38s/it]

Added new genus: Diachasmimorpha (ID: 3078)

Fetching Species:  14%|█▍        | 1963/13683 [1:16:02<7:40:11,  2.36s/it]

Added new genus: Gata (ID: 3079)

Fetching Species:  14%|█▍        | 1964/13683 [1:16:04<7:43:42,  2.37s/it]

Added new genus: Taishun (ID: 3080)

Fetching Species:  15%|█▌        | 2101/13683 [1:21:28<7:36:34,  2.37s/it]

Added new genus: Xiangshan (ID: 3081)

Fetching Species:  16%|█▌        | 2122/13683 [1:22:18<7:29:15,  2.33s/it]

Added new genus: Guiyang (ID: 3082)

Fetching Species:  16%|█▌        | 2127/13683 [1:22:30<7:33:42,  2.36s/it]

Added new genus: Hangzhou (ID: 3083)

Fetching Species:  16%|█▌        | 2144/13683 [1:23:11<7:51:36,  2.45s/it]

Added new genus: Erthesina (ID: 3084)

Fetching Species:  16%|█▌        | 2199/13683 [1:25:22<7:44:15,  2.43s/it]

Added new genus: Yunnan (ID: 3085)

Fetching Species:  16%|█▌        | 2204/13683 [1:25:34<7:47:37,  2.44s/it]

Added new genus: Grapevine-associated (ID: 3086)

Fetching Species:  16%|█▌        | 2205/13683 [1:25:36<7:38:50,  2.40s/it]

Added new genus: Lepeophtheirus (ID: 3087)

Fetching Species:  16%|█▌        | 2208/13683 [1:25:43<7:29:12,  2.35s/it]

Added new genus: Xinzhou (ID: 3088)

Fetching Species:  16%|█▌        | 2209/13683 [1:25:46<7:32:21,  2.37s/it]

Added new genus: Hancheng (ID: 3089)

Fetching Species:  16%|█▌        | 2214/13683 [1:25:57<7:22:54,  2.32s/it]

Added new genus: Hermit (ID: 3090)

Fetching Species:  16%|█▌        | 2215/13683 [1:26:00<7:12:54,  2.26s/it]

Added new genus: Crustacean (ID: 3091)

Fetching Species:  17%|█▋        | 2307/13683 [1:29:34<7:35:19,  2.40s/it]

Added new genus: Stemphylium (ID: 3092)

Fetching Species:  17%|█▋        | 2339/13683 [1:30:49<7:04:31,  2.25s/it]

Added new genus: Magnaporthe (ID: 3093)

Fetching Species:  17%|█▋        | 2341/13683 [1:30:53<7:08:42,  2.27s/it]

Added new genus: Botryosphaeria (ID: 3094)

Fetching Species:  17%|█▋        | 2344/13683 [1:31:00<7:14:31,  2.30s/it]

Added new genus: 1980 (ID: 3095)

Fetching Species:  17%|█▋        | 2348/13683 [1:31:08<6:48:22,  2.16s/it]

Added new genus: Beauveria (ID: 3096)

Fetching Species:  17%|█▋        | 2350/13683 [1:31:13<7:28:17,  2.37s/it]

Added new genus: Sphaeropsis (ID: 3097)

Fetching Species:  17%|█▋        | 2354/13683 [1:31:22<7:05:27,  2.25s/it]

Added new genus: Tolypocladium (ID: 3098)

Fetching Species:  17%|█▋        | 2356/13683 [1:31:27<7:27:24,  2.37s/it]

Added new genus: Epichloe (ID: 3099)

Fetching Species:  17%|█▋        | 2363/13683 [1:31:43<7:20:53,  2.34s/it]

Added new genus: Chalara (ID: 3100)

Fetching Species:  17%|█▋        | 2365/13683 [1:31:48<7:16:20,  2.31s/it]

Added new genus: Eimeria (ID: 3101)

Fetching Species:  17%|█▋        | 2366/13683 [1:31:50<7:22:53,  2.35s/it]

Added new genus: Helminthosporium (ID: 3102)

Fetching Species:  17%|█▋        | 2368/13683 [1:31:55<7:11:19,  2.29s/it]

Added new genus: Coniothyrium (ID: 3103)

Fetching Species:  17%|█▋        | 2369/13683 [1:31:57<7:10:57,  2.29s/it]

Added new genus: Alternaria (ID: 3104)

Fetching Species:  17%|█▋        | 2370/13683 [1:32:00<7:18:28,  2.33s/it]

Added new genus: Diatom (ID: 3105)

Fetching Species:  17%|█▋        | 2372/13683 [1:32:04<7:16:16,  2.31s/it]

Added new genus: Xanthophyllomyces (ID: 3106)

Fetching Species:  17%|█▋        | 2373/13683 [1:32:06<7:14:35,  2.31s/it]

Added new genus: Saccharomyces (ID: 3107)

Fetching Species:  17%|█▋        | 2375/13683 [1:32:11<6:59:22,  2.23s/it]

Added new genus: Black (ID: 3108)

Fetching Species:  17%|█▋        | 2376/13683 [1:32:14<7:38:48,  2.43s/it]

Added new genus: Tuber (ID: 3109)

Fetching Species:  17%|█▋        | 2378/13683 [1:32:20<9:04:13,  2.89s/it]

Added new genus: Scheffersomyces (ID: 3110)

Fetching Species:  17%|█▋        | 2379/13683 [1:32:22<8:23:07,  2.67s/it]

Added new genus: Ustilago (ID: 3111)

Fetching Species:  17%|█▋        | 2382/13683 [1:32:29<7:29:54,  2.39s/it]

Added new genus: Trichomonas (ID: 3112)

Fetching Species:  17%|█▋        | 2387/13683 [1:32:40<7:00:04,  2.23s/it]

Added new genus: Phlebiopsis (ID: 3113)

Fetching Species:  17%|█▋        | 2391/13683 [1:32:49<7:07:56,  2.27s/it]

Added new genus: Piscine (ID: 3114)

Fetching Species:  17%|█▋        | 2393/13683 [1:32:54<7:02:27,  2.25s/it]

Added new genus: Panax (ID: 3115)

Fetching Species:  17%|█▋        | 2394/13683 [1:32:56<7:13:19,  2.30s/it]

Added new genus: Maize-associated (ID: 3116)

Fetching Species:  18%|█▊        | 2398/13683 [1:33:06<7:40:40,  2.45s/it]

Added new genus: Leishmania (ID: 3117)

Fetching Species:  18%|█▊        | 2401/13683 [1:33:13<7:06:41,  2.27s/it]

Added new genus: Penaeid (ID: 3118)

Fetching Species:  18%|█▊        | 2404/13683 [1:33:20<7:09:20,  2.28s/it]

Added new genus: Camponotus (ID: 3119)

Fetching Species:  18%|█▊        | 2405/13683 [1:33:22<7:17:21,  2.33s/it]

Added new genus: Australian (ID: 3120)

Fetching Species:  18%|█▊        | 2409/13683 [1:33:31<7:08:02,  2.28s/it]

Added new genus: Leptopilina (ID: 3121)

Fetching Species:  18%|█▊        | 2410/13683 [1:33:33<7:08:01,  2.28s/it]

Added new genus: Thelephora (ID: 3122)

Fetching Species:  18%|█▊        | 2412/13683 [1:33:39<7:42:33,  2.46s/it]

Added new genus: Sogatella (ID: 3123)

Fetching Species:  18%|█▊        | 2416/13683 [1:33:48<7:23:40,  2.36s/it]

Added new genus: Golden (ID: 3124)

Fetching Species:  18%|█▊        | 2423/13683 [1:34:04<7:01:41,  2.25s/it]

Added new genus: Gigaspora (ID: 3125)

Fetching Species:  18%|█▊        | 2424/13683 [1:34:06<6:55:44,  2.22s/it]

Added new genus: Giardia (ID: 3126)

Fetching Species:  18%|█▊        | 2426/13683 [1:34:11<7:02:13,  2.25s/it]

Added new genus: Tianjin (ID: 3127)

Fetching Species:  18%|█▊        | 2434/13683 [1:34:29<7:11:21,  2.30s/it]

Added new genus: Drosophila (ID: 3128)

Fetching Species:  18%|█▊        | 2440/13683 [1:34:44<7:18:08,  2.34s/it]

Added new genus: Fall (ID: 3129)

Fetching Species:  18%|█▊        | 2445/13683 [1:34:55<6:59:59,  2.24s/it]

Added new genus: Etheostoma (ID: 3130)

Fetching Species:  18%|█▊        | 2448/13683 [1:35:01<6:51:44,  2.20s/it]

Added new genus: Fako (ID: 3131)

Fetching Species:  18%|█▊        | 2454/13683 [1:35:18<8:27:36,  2.71s/it]

Added new genus: Daphnis (ID: 3132)

Fetching Species:  18%|█▊        | 2456/13683 [1:35:23<7:53:06,  2.53s/it]

Added new genus: Dendrolimus (ID: 3133)

Fetching Species:  18%|█▊        | 2457/13683 [1:35:25<7:42:44,  2.47s/it]

Added new genus: Broome (ID: 3134)

Fetching Species:  18%|█▊        | 2458/13683 [1:35:27<7:32:44,  2.42s/it]

Added new genus: Mammalian (ID: 3135)

Fetching Species:  18%|█▊        | 2459/13683 [1:35:30<7:18:31,  2.34s/it]

Added new genus: Pteropine (ID: 3136)

Fetching Species:  18%|█▊        | 2460/13683 [1:35:32<7:46:02,  2.49s/it]

Added new genus: Nelson (ID: 3137)

Fetching Species:  18%|█▊        | 2464/13683 [1:35:41<7:08:03,  2.29s/it]

Added new genus: Mahlapitsi (ID: 3138)

Fetching Species:  18%|█▊        | 2465/13683 [1:35:43<6:59:43,  2.24s/it]

Added new genus: Reptilian (ID: 3139)

Fetching Species:  18%|█▊        | 2468/13683 [1:35:50<6:51:13,  2.20s/it]

Added new genus: Mal (ID: 3140)

Fetching Species:  18%|█▊        | 2471/13683 [1:35:59<8:03:16,  2.59s/it]

Added new genus: Fiji (ID: 3141)

Fetching Species:  18%|█▊        | 2474/13683 [1:36:06<7:15:21,  2.33s/it]

Added new genus: Tarumizu (ID: 3142)

Fetching Species:  18%|█▊        | 2475/13683 [1:36:08<7:12:14,  2.31s/it]

Added new genus: Colorado (ID: 3143)

Fetching Species:  18%|█▊        | 2476/13683 [1:36:10<7:03:00,  2.26s/it]

Added new genus: Eyach (ID: 3144)

Fetching Species:  18%|█▊        | 2477/13683 [1:36:12<6:56:14,  2.23s/it]

Added new genus: Kundal (ID: 3145)

Fetching Species:  18%|█▊        | 2478/13683 [1:36:15<7:07:45,  2.29s/it]

Added new genus: Tai (ID: 3146)

Fetching Species:  18%|█▊        | 2483/13683 [1:36:26<7:03:02,  2.27s/it]

Added new genus: Chiqui (ID: 3147)

Fetching Species:  18%|█▊        | 2485/13683 [1:36:31<7:24:52,  2.38s/it]

Added new genus: Lebombo (ID: 3148)

Fetching Species:  18%|█▊        | 2487/13683 [1:36:35<7:02:44,  2.27s/it]

Added new genus: Umatilla (ID: 3149)

Fetching Species:  18%|█▊        | 2489/13683 [1:36:40<7:15:29,  2.33s/it]

Added new genus: Bluetongue (ID: 3150)

Fetching Species:  18%|█▊        | 2490/13683 [1:36:42<7:05:04,  2.28s/it]

Added new genus: St (ID: 3151)

Fetching Species:  18%|█▊        | 2491/13683 [1:36:44<6:57:26,  2.24s/it]

Added new genus: Great (ID: 3152)

Fetching Species:  18%|█▊        | 2492/13683 [1:36:47<6:52:11,  2.21s/it]

Added new genus: Chobar (ID: 3153)

Fetching Species:  18%|█▊        | 2493/13683 [1:36:49<6:58:39,  2.24s/it]

Added new genus: Changuinola (ID: 3154)

Fetching Species:  18%|█▊        | 2494/13683 [1:36:51<6:53:06,  2.22s/it]

Added new genus: Tibet (ID: 3155)

Fetching Species:  18%|█▊        | 2495/13683 [1:36:53<6:58:42,  2.25s/it]

Added new genus: Palyam (ID: 3156)

Fetching Species:  18%|█▊        | 2496/13683 [1:36:56<7:18:46,  2.35s/it]

Added new genus: Epizootic (ID: 3157)

Fetching Species:  18%|█▊        | 2497/13683 [1:36:58<7:06:44,  2.29s/it]

Added new genus: Chenuda (ID: 3158)

Fetching Species:  18%|█▊        | 2498/13683 [1:37:00<6:58:11,  2.24s/it]

Added new genus: Guangxi (ID: 3159)

Fetching Species:  18%|█▊        | 2499/13683 [1:37:03<7:02:24,  2.27s/it]

Added new genus: Warrego (ID: 3160)

Fetching Species:  18%|█▊        | 2500/13683 [1:37:05<6:55:18,  2.23s/it]

Added new genus: Wallal (ID: 3161)

Fetching Species:  18%|█▊        | 2501/13683 [1:37:07<6:50:59,  2.21s/it]

Added new genus: Eubenangee (ID: 3162)

Fetching Species:  18%|█▊        | 2502/13683 [1:37:09<6:55:51,  2.23s/it]

Added new genus: Peruvian (ID: 3163)

Fetching Species:  18%|█▊        | 2503/13683 [1:37:11<6:51:47,  2.21s/it]

Added new genus: Corriparta (ID: 3164)

Fetching Species:  18%|█▊        | 2505/13683 [1:37:16<6:45:32,  2.18s/it]

Added new genus: Mobuck (ID: 3165)

Fetching Species:  18%|█▊        | 2506/13683 [1:37:18<6:45:27,  2.18s/it]

Added new genus: Orungo (ID: 3166)

Fetching Species:  18%|█▊        | 2507/13683 [1:37:21<7:17:51,  2.35s/it]

Added new genus: Wad (ID: 3167)

Fetching Species:  18%|█▊        | 2509/13683 [1:37:25<7:12:32,  2.32s/it]

Added new genus: Stretch (ID: 3168)

Fetching Species:  18%|█▊        | 2510/13683 [1:37:28<8:06:32,  2.61s/it]

Added new genus: Homalodisca (ID: 3169)

Fetching Species:  18%|█▊        | 2512/13683 [1:37:33<7:26:20,  2.40s/it]

Added new genus: Wound (ID: 3170)

Fetching Species:  18%|█▊        | 2527/13683 [1:38:06<6:47:17,  2.19s/it]

Added new genus: Eriocheir (ID: 3171)

Fetching Species:  18%|█▊        | 2528/13683 [1:38:08<7:00:21,  2.26s/it]

Added new genus: Micromonas (ID: 3172)

Fetching Species:  18%|█▊        | 2530/13683 [1:38:12<6:49:34,  2.20s/it]

Added new genus: Cimodo (ID: 3173)

Fetching Species:  18%|█▊        | 2531/13683 [1:38:15<6:47:00,  2.19s/it]

Added new genus: Lutzomyia (ID: 3174)

Fetching Species:  19%|█▊        | 2532/13683 [1:38:17<6:47:37,  2.19s/it]

Added new genus: Operophtera (ID: 3175)

Fetching Species:  19%|█▊        | 2533/13683 [1:38:19<6:45:16,  2.18s/it]

Added new genus: Callinectes (ID: 3176)

Fetching Species:  19%|█▊        | 2534/13683 [1:38:22<7:07:04,  2.30s/it]

Added new genus: Spissistilus (ID: 3177)

Fetching Species:  19%|█▊        | 2536/13683 [1:38:26<7:10:56,  2.32s/it]

Added new genus: Raspberry (ID: 3178)

Fetching Species:  19%|█▉        | 2655/13683 [1:42:53<6:46:57,  2.21s/it]

Added new genus: Wahlkovirus (ID: 3179)

Fetching Species:  21%|██        | 2838/13683 [1:49:47<6:38:54,  2.21s/it]

Added new genus: Leviviridae (ID: 3180)

Fetching Species:  21%|██        | 2862/13683 [1:50:40<6:34:21,  2.19s/it]

Added new genus: Dursuvirus (ID: 3181)

Fetching Species:  24%|██▍       | 3309/13683 [2:07:51<7:49:57,  2.72s/it]

Added new genus: Bihckevirus (ID: 3182)

Fetching Species:  25%|██▌       | 3446/13683 [2:13:37<7:29:24,  2.63s/it]

Added new genus: Pyricularia (ID: 3183)

Fetching Species:  25%|██▌       | 3462/13683 [2:14:18<6:41:30,  2.36s/it]

Added new genus: Cladosporium (ID: 3184)

Fetching Species:  25%|██▌       | 3464/13683 [2:14:23<7:28:14,  2.63s/it]

Added new genus: Ourmia (ID: 3185)

Fetching Species:  25%|██▌       | 3467/13683 [2:14:31<6:58:00,  2.45s/it]

Added new genus: Epirus (ID: 3186)

Fetching Species:  25%|██▌       | 3473/13683 [2:14:45<7:18:00,  2.57s/it]

Added new genus: Colletotrichum (ID: 3187)

Fetching Species:  26%|██▌       | 3495/13683 [2:15:39<7:26:21,  2.63s/it]

Added new genus: Acremonium (ID: 3188)

Fetching Species:  26%|██▌       | 3504/13683 [2:16:03<7:14:06,  2.56s/it]

Added new genus: Phaeoacremonium (ID: 3189)

Fetching Species:  26%|██▌       | 3509/13683 [2:16:15<6:32:11,  2.31s/it]

Added new genus: Phomosis (ID: 3190)

Fetching Species:  26%|██▌       | 3520/13683 [2:16:41<6:27:19,  2.29s/it]

Added new genus: Epicoccum (ID: 3191)

Fetching Species:  26%|██▌       | 3523/13683 [2:16:48<6:34:15,  2.33s/it]

Added new genus: Phoma (ID: 3192)

Fetching Species:  26%|██▌       | 3524/13683 [2:16:50<6:25:04,  2.27s/it]

Added new genus: Neofusicoccum (ID: 3193)

Fetching Species:  26%|██▌       | 3552/13683 [2:17:53<6:12:30,  2.21s/it]

Added new genus: Botrytis (ID: 3194)

Fetching Species:  27%|██▋       | 3632/13683 [2:20:53<6:32:51,  2.35s/it]

Added new genus: Ocimum (ID: 3195)

Fetching Species:  27%|██▋       | 3633/13683 [2:20:56<6:24:29,  2.30s/it]

Added new genus: Rhizophagus (ID: 3196)

Fetching Species:  27%|██▋       | 3634/13683 [2:20:58<6:24:40,  2.30s/it]

Added new genus: Erysiphe (ID: 3197)

Fetching Species:  27%|██▋       | 3637/13683 [2:21:05<6:16:50,  2.25s/it]

Added new genus: Binucleate (ID: 3198)

Fetching Species:  27%|██▋       | 3684/13683 [2:22:53<6:13:15,  2.24s/it]

Added new genus: Kvaramitovirus (ID: 3199)

Fetching Species:  27%|██▋       | 3695/13683 [2:23:19<7:01:29,  2.53s/it]

Added new genus: Blechomonas (ID: 3200)

Fetching Species:  27%|██▋       | 3698/13683 [2:23:27<7:09:44,  2.58s/it]

Added new genus: Phytomonas (ID: 3201)

Fetching Species:  27%|██▋       | 3705/13683 [2:23:44<6:52:54,  2.48s/it]

Added new genus: Leptomonas (ID: 3202)

Fetching Species:  27%|██▋       | 3708/13683 [2:23:51<6:25:37,  2.32s/it]

Added new genus: Phytophthora (ID: 3203)

Fetching Species:  27%|██▋       | 3710/13683 [2:23:55<6:16:42,  2.27s/it]

Added new genus: Penaeus (ID: 3204)

Fetching Species:  27%|██▋       | 3712/13683 [2:23:59<6:13:12,  2.25s/it]

Added new genus: Boolarra (ID: 3205)

Fetching Species:  27%|██▋       | 3713/13683 [2:24:02<6:15:24,  2.26s/it]

Added new genus: Flock (ID: 3206)

Fetching Species:  27%|██▋       | 3714/13683 [2:24:04<6:17:13,  2.27s/it]

Added new genus: Nodamura (ID: 3207)

Fetching Species:  27%|██▋       | 3715/13683 [2:24:06<6:10:33,  2.23s/it]

Added new genus: Pariacoto (ID: 3208)

Fetching Species:  27%|██▋       | 3716/13683 [2:24:08<6:06:49,  2.21s/it]

Added new genus: Le (ID: 3209)

Fetching Species:  27%|██▋       | 3717/13683 [2:24:10<6:04:00,  2.19s/it]

Added new genus: Striped (ID: 3210)

Fetching Species:  27%|██▋       | 3718/13683 [2:24:13<6:01:42,  2.18s/it]

Added new genus: Tiger (ID: 3211)

Fetching Species:  27%|██▋       | 3719/13683 [2:24:15<6:06:57,  2.21s/it]

Added new genus: Redspotted (ID: 3212)

Fetching Species:  27%|██▋       | 3720/13683 [2:24:17<6:03:50,  2.19s/it]

Added new genus: Barfin (ID: 3213)

Fetching Species:  27%|██▋       | 3721/13683 [2:24:19<6:02:13,  2.18s/it]

Added new genus: Santeuil (ID: 3214)

Fetching Species:  27%|██▋       | 3722/13683 [2:24:21<6:01:50,  2.18s/it]

Added new genus: Orsay (ID: 3215)

Fetching Species:  27%|██▋       | 3723/13683 [2:24:24<6:06:31,  2.21s/it]

Added new genus: Lake (ID: 3216)

Fetching Species:  27%|██▋       | 3731/13683 [2:24:42<6:17:36,  2.28s/it]

Added new genus: Parietaria (ID: 3217)

Fetching Species:  27%|██▋       | 3733/13683 [2:24:47<6:18:37,  2.28s/it]

Added new genus: Prunus (ID: 3218)

Fetching Species:  27%|██▋       | 3736/13683 [2:24:54<6:20:38,  2.30s/it]

Added new genus: Privet (ID: 3219)

Fetching Species:  27%|██▋       | 3738/13683 [2:24:58<6:14:28,  2.26s/it]

Added new genus: Tea (ID: 3220)

Fetching Species:  27%|██▋       | 3739/13683 [2:25:00<6:17:00,  2.27s/it]

Added new genus: Tulare (ID: 3221)

Fetching Species:  27%|██▋       | 3740/13683 [2:25:03<6:18:45,  2.29s/it]

Added new genus: Lilac (ID: 3222)

Fetching Species:  27%|██▋       | 3741/13683 [2:25:05<6:13:58,  2.26s/it]

Added new genus: Apple (ID: 3223)

Fetching Species:  27%|██▋       | 3745/13683 [2:25:15<6:38:31,  2.41s/it]

Added new genus: Cape (ID: 3224)

Fetching Species:  27%|██▋       | 3749/13683 [2:25:24<6:25:03,  2.33s/it]

Added new genus: Prune (ID: 3225)

Fetching Species:  27%|██▋       | 3750/13683 [2:25:26<6:26:53,  2.34s/it]

Added new genus: Elm (ID: 3226)

Fetching Species:  27%|██▋       | 3754/13683 [2:25:35<6:20:03,  2.30s/it]

Added new genus: Humulus (ID: 3227)

Fetching Species:  27%|██▋       | 3756/13683 [2:25:40<6:11:20,  2.24s/it]

Added new genus: Pelargonium (ID: 3228)

Fetching Species:  27%|██▋       | 3760/13683 [2:25:49<6:18:02,  2.29s/it]

Added new genus: Broad (ID: 3229)

Fetching Species:  27%|██▋       | 3761/13683 [2:25:51<6:11:05,  2.24s/it]

Added new genus: Spring (ID: 3230)

Fetching Species:  28%|██▊       | 3763/13683 [2:25:56<6:15:20,  2.27s/it]

Added new genus: Melandrium (ID: 3231)

Fetching Species:  28%|██▊       | 3765/13683 [2:26:00<6:17:56,  2.29s/it]

Added new genus: Cassia (ID: 3232)

Fetching Species:  28%|██▊       | 3770/13683 [2:26:12<6:07:28,  2.22s/it]

Added new genus: Gayfeather (ID: 3233)

Fetching Species:  28%|██▊       | 3771/13683 [2:26:14<6:17:29,  2.29s/it]

Added new genus: Olive (ID: 3234)

Fetching Species:  28%|██▊       | 3774/13683 [2:26:21<6:24:58,  2.33s/it]

Added new genus: Bell (ID: 3235)

Fetching Species:  28%|██▊       | 3778/13683 [2:26:30<6:26:16,  2.34s/it]

Added new genus: Basella (ID: 3236)

Fetching Species:  28%|██▊       | 3779/13683 [2:26:32<6:24:32,  2.33s/it]

Added new genus: Lagenaria (ID: 3237)

Fetching Species:  28%|██▊       | 3780/13683 [2:26:35<6:15:04,  2.27s/it]

Added new genus: Phaseolus (ID: 3238)

Fetching Species:  28%|██▊       | 3782/13683 [2:26:39<6:10:37,  2.25s/it]

Added new genus: Yerba (ID: 3239)

Fetching Species:  28%|██▊       | 3785/13683 [2:26:46<6:21:43,  2.31s/it]

Added new genus: Oryza (ID: 3240)

Fetching Species:  28%|██▊       | 3787/13683 [2:26:51<6:22:38,  2.32s/it]

Added new genus: Persea (ID: 3241)

Fetching Species:  28%|██▊       | 3789/13683 [2:26:55<6:15:06,  2.27s/it]

Added new genus: Helianthus (ID: 3242)

Fetching Species:  28%|██▊       | 3791/13683 [2:26:59<6:10:21,  2.25s/it]

Added new genus: Hot (ID: 3243)

Fetching Species:  28%|██▊       | 3793/13683 [2:27:04<6:06:49,  2.23s/it]

Added new genus: Cucumis (ID: 3244)

Fetching Species:  28%|██▊       | 3794/13683 [2:27:06<6:11:23,  2.25s/it]

Added new genus: Winged (ID: 3245)

Fetching Species:  28%|██▊       | 3804/13683 [2:27:30<6:44:06,  2.45s/it]

Added new genus: Ceratobasidium (ID: 3246)

Fetching Species:  28%|██▊       | 3807/13683 [2:27:37<6:37:46,  2.42s/it]

Added new genus: Cluster (ID: 3247)

Fetching Species:  28%|██▊       | 3811/13683 [2:27:47<6:30:05,  2.37s/it]

Added new genus: Pixuna (ID: 3248)

Fetching Species:  28%|██▊       | 3812/13683 [2:27:49<6:52:05,  2.50s/it]

Added new genus: Middelburg (ID: 3249)

Fetching Species:  28%|██▊       | 3813/13683 [2:27:52<6:41:13,  2.44s/it]

Added new genus: Mucambo (ID: 3250)

Fetching Species:  28%|██▊       | 3814/13683 [2:27:54<6:33:04,  2.39s/it]

Added new genus: Getah (ID: 3251)

Fetching Species:  28%|██▊       | 3815/13683 [2:27:56<6:27:20,  2.36s/it]

Added new genus: Madariaga (ID: 3252)

Fetching Species:  28%|██▊       | 3816/13683 [2:27:59<6:30:05,  2.37s/it]

Added new genus: Venezuelan (ID: 3253)

Fetching Species:  28%|██▊       | 3817/13683 [2:28:01<6:25:17,  2.34s/it]

Added new genus: Onyong-nyong (ID: 3254)

Fetching Species:  28%|██▊       | 3818/13683 [2:28:03<6:15:13,  2.28s/it]

Added new genus: Aura (ID: 3255)

Fetching Species:  28%|██▊       | 3819/13683 [2:28:05<6:08:14,  2.24s/it]

Added new genus: Ross (ID: 3256)

Fetching Species:  28%|██▊       | 3820/13683 [2:28:07<6:06:57,  2.23s/it]

Added new genus: Fort (ID: 3257)

Fetching Species:  28%|██▊       | 3821/13683 [2:28:10<6:16:31,  2.29s/it]

Added new genus: Whataroa (ID: 3258)

Fetching Species:  28%|██▊       | 3822/13683 [2:28:12<6:09:33,  2.25s/it]

Added new genus: Western (ID: 3259)

Fetching Species:  28%|██▊       | 3823/13683 [2:28:14<6:04:07,  2.22s/it]

Added new genus: Tonate (ID: 3260)

Fetching Species:  28%|██▊       | 3824/13683 [2:28:16<6:07:01,  2.23s/it]

Added new genus: Salmon (ID: 3261)

Fetching Species:  28%|██▊       | 3825/13683 [2:28:19<6:03:15,  2.21s/it]

Added new genus: Mosso (ID: 3262)

Fetching Species:  28%|██▊       | 3826/13683 [2:28:21<6:05:55,  2.23s/it]

Added new genus: Eastern (ID: 3263)

Fetching Species:  28%|██▊       | 3827/13683 [2:28:23<6:10:45,  2.26s/it]

Added new genus: Una (ID: 3264)

Fetching Species:  28%|██▊       | 3828/13683 [2:28:25<6:12:25,  2.27s/it]

Added new genus: Bebaru (ID: 3265)

Fetching Species:  28%|██▊       | 3829/13683 [2:28:29<7:27:08,  2.72s/it]

Added new genus: Caaingua (ID: 3266)

Fetching Species:  28%|██▊       | 3830/13683 [2:28:32<7:08:17,  2.61s/it]

Added new genus: Highlands (ID: 3267)

Fetching Species:  28%|██▊       | 3831/13683 [2:28:34<6:53:34,  2.52s/it]

Added new genus: Sindbis (ID: 3268)

Fetching Species:  28%|██▊       | 3832/13683 [2:28:36<6:41:36,  2.45s/it]

Added new genus: Cabassou (ID: 3269)

Fetching Species:  28%|██▊       | 3834/13683 [2:28:41<6:27:24,  2.36s/it]

Added new genus: Mayaro (ID: 3270)

Fetching Species:  28%|██▊       | 3835/13683 [2:28:43<6:16:35,  2.29s/it]

Added new genus: Semliki (ID: 3271)

Fetching Species:  28%|██▊       | 3837/13683 [2:28:47<6:21:16,  2.32s/it]

Added new genus: Chikungunya (ID: 3272)

Fetching Species:  28%|██▊       | 3838/13683 [2:28:50<6:21:46,  2.33s/it]

Added new genus: Everglades (ID: 3273)

Fetching Species:  28%|██▊       | 3839/13683 [2:28:52<6:12:39,  2.27s/it]

Added new genus: Ndumu (ID: 3274)

Fetching Species:  28%|██▊       | 3840/13683 [2:28:54<6:19:36,  2.31s/it]

Added new genus: Trocara (ID: 3275)

Fetching Species:  28%|██▊       | 3841/13683 [2:28:57<6:25:47,  2.35s/it]

Added new genus: Rio (ID: 3276)

Fetching Species:  28%|██▊       | 3842/13683 [2:28:59<6:23:56,  2.34s/it]

Added new genus: Barmah (ID: 3277)

Fetching Species:  28%|██▊       | 3843/13683 [2:29:01<6:20:40,  2.32s/it]

Added new genus: Eilat (ID: 3278)

Fetching Species:  28%|██▊       | 3857/13683 [2:29:34<6:23:51,  2.34s/it]

Added new genus: Blackcurrant (ID: 3279)

Fetching Species:  28%|██▊       | 3863/13683 [2:29:49<6:35:48,  2.42s/it]

Added new genus: Mint (ID: 3280)

Fetching Species:  28%|██▊       | 3869/13683 [2:30:03<6:27:02,  2.37s/it]

Added new genus: Rehmannia (ID: 3281)

Fetching Species:  28%|██▊       | 3874/13683 [2:30:15<6:22:51,  2.34s/it]

Added new genus: Tetterwort (ID: 3282)

Fetching Species:  28%|██▊       | 3877/13683 [2:30:22<6:16:09,  2.30s/it]

Added new genus: Lettuce (ID: 3283)

Fetching Species:  28%|██▊       | 3878/13683 [2:30:24<6:15:17,  2.30s/it]

Added new genus: Bean (ID: 3284)

Fetching Species:  28%|██▊       | 3886/13683 [2:30:42<6:19:57,  2.33s/it]

Added new genus: Diodia (ID: 3285)

Fetching Species:  28%|██▊       | 3890/13683 [2:30:51<6:19:23,  2.32s/it]

Added new genus: Pineapple (ID: 3286)

Fetching Species:  28%|██▊       | 3897/13683 [2:31:07<6:11:38,  2.28s/it]

Added new genus: Little (ID: 3287)

Fetching Species:  28%|██▊       | 3898/13683 [2:31:10<6:04:46,  2.24s/it]

Added new genus: Pistachio (ID: 3288)

Fetching Species:  29%|██▊       | 3900/13683 [2:31:14<6:13:00,  2.29s/it]

Added new genus: Plum (ID: 3289)

Fetching Species:  29%|██▊       | 3904/13683 [2:31:24<6:15:50,  2.31s/it]

Added new genus: Cordyline (ID: 3290)

Fetching Species:  29%|██▊       | 3908/13683 [2:31:33<6:11:00,  2.28s/it]

Added new genus: Malus (ID: 3291)

Fetching Species:  29%|██▊       | 3920/13683 [2:32:01<6:05:01,  2.24s/it]

Added new genus: Poa (ID: 3292)

Fetching Species:  29%|██▊       | 3921/13683 [2:32:04<6:37:59,  2.45s/it]

Added new genus: Lychnis (ID: 3293)

Fetching Species:  29%|██▊       | 3924/13683 [2:32:11<6:24:55,  2.37s/it]

Added new genus: Colombian (ID: 3294)

Fetching Species:  29%|██▊       | 3927/13683 [2:32:18<6:09:47,  2.27s/it]

Added new genus: Plumeria (ID: 3295)

Fetching Species:  29%|██▊       | 3928/13683 [2:32:20<6:09:43,  2.27s/it]

Added new genus: Cactus (ID: 3296)

Fetching Species:  29%|██▊       | 3929/13683 [2:32:23<6:10:45,  2.28s/it]

Added new genus: Maracuja (ID: 3297)

Fetching Species:  29%|██▊       | 3932/13683 [2:32:29<5:59:02,  2.21s/it]

Added new genus: Youcai (ID: 3298)

Fetching Species:  29%|██▊       | 3933/13683 [2:32:32<6:11:34,  2.29s/it]

Added new genus: Opuntia (ID: 3299)

Fetching Species:  29%|██▉       | 3934/13683 [2:32:34<6:10:47,  2.28s/it]

Added new genus: Ribgrass (ID: 3300)

Fetching Species:  29%|██▉       | 3935/13683 [2:32:36<6:06:55,  2.26s/it]

Added new genus: Obuda (ID: 3301)

Fetching Species:  29%|██▉       | 3936/13683 [2:32:39<6:08:40,  2.27s/it]

Added new genus: Odontoglossum (ID: 3302)

Fetching Species:  29%|██▉       | 3940/13683 [2:32:48<6:06:45,  2.26s/it]

Added new genus: Streptocarpus (ID: 3303)

Fetching Species:  29%|██▉       | 3941/13683 [2:32:51<6:51:29,  2.53s/it]

Added new genus: Tropical (ID: 3304)

Fetching Species:  29%|██▉       | 3942/13683 [2:32:53<6:33:32,  2.42s/it]

Added new genus: Rattail (ID: 3305)

Fetching Species:  29%|██▉       | 3943/13683 [2:32:55<6:22:42,  2.36s/it]

Added new genus: Hoya (ID: 3306)

Fetching Species:  29%|██▉       | 3947/13683 [2:33:04<6:03:47,  2.24s/it]

Added new genus: Paprika (ID: 3307)

Fetching Species:  29%|██▉       | 3948/13683 [2:33:06<6:11:44,  2.29s/it]

Added new genus: Clitoria (ID: 3308)

Fetching Species:  29%|██▉       | 3949/13683 [2:33:09<6:17:41,  2.33s/it]

Added new genus: Hibiscus (ID: 3309)

Fetching Species:  29%|██▉       | 3950/13683 [2:33:11<6:08:35,  2.27s/it]

Added new genus: Brugmansia (ID: 3310)

Fetching Species:  29%|██▉       | 3951/13683 [2:33:13<6:17:20,  2.33s/it]

Added new genus: Zucchini (ID: 3311)

Fetching Species:  29%|██▉       | 3954/13683 [2:33:20<6:11:37,  2.29s/it]

Added new genus: Kyuri (ID: 3312)

Fetching Species:  29%|██▉       | 3955/13683 [2:33:23<6:11:53,  2.29s/it]

Added new genus: Passion (ID: 3313)

Fetching Species:  29%|██▉       | 3956/13683 [2:33:25<6:12:06,  2.30s/it]

Added new genus: Frangipani (ID: 3314)

Fetching Species:  29%|██▉       | 3958/13683 [2:33:29<6:02:01,  2.23s/it]

Added new genus: Sunn-hemp (ID: 3315)

Fetching Species:  29%|██▉       | 3963/13683 [2:33:41<5:58:34,  2.21s/it]

Added new genus: Wasabi (ID: 3316)

Fetching Species:  29%|██▉       | 3965/13683 [2:33:45<6:04:57,  2.25s/it]

Added new genus: Sorghum (ID: 3317)

Fetching Species:  29%|██▉       | 3966/13683 [2:33:47<6:06:17,  2.26s/it]

Added new genus: Japanese (ID: 3318)

Fetching Species:  29%|██▉       | 3967/13683 [2:33:50<6:14:09,  2.31s/it]

Added new genus: Soil-borne (ID: 3319)

Fetching Species:  29%|██▉       | 3973/13683 [2:34:03<6:08:22,  2.28s/it]

Added new genus: Gentian (ID: 3320)

Fetching Species:  29%|██▉       | 3974/13683 [2:34:06<6:08:41,  2.28s/it]

Added new genus: Drakaea (ID: 3321)

Fetching Species:  29%|██▉       | 3975/13683 [2:34:08<6:09:33,  2.28s/it]

Added new genus: Macrophomina (ID: 3322)

Fetching Species:  29%|██▉       | 3976/13683 [2:34:10<6:09:28,  2.28s/it]

Added new genus: Indian (ID: 3323)

Fetching Species:  29%|██▉       | 3980/13683 [2:34:19<6:09:00,  2.28s/it]

Added new genus: Euonymus (ID: 3324)

Fetching Species:  29%|██▉       | 3982/13683 [2:34:24<6:15:33,  2.32s/it]

Added new genus: Clover (ID: 3325)

Fetching Species:  29%|██▉       | 3986/13683 [2:34:33<6:08:36,  2.28s/it]

Added new genus: Tulip (ID: 3326)

Fetching Species:  29%|██▉       | 3991/13683 [2:34:45<6:20:08,  2.35s/it]

Added new genus: Phaius (ID: 3327)

Fetching Species:  29%|██▉       | 3995/13683 [2:34:54<6:08:37,  2.28s/it]

Added new genus: Nerine (ID: 3328)

Fetching Species:  29%|██▉       | 3998/13683 [2:35:02<6:50:39,  2.54s/it]

Added new genus: Pitaya (ID: 3329)

Fetching Species:  29%|██▉       | 4000/13683 [2:35:06<6:23:07,  2.37s/it]

Added new genus: Hosta (ID: 3330)

Fetching Species:  29%|██▉       | 4001/13683 [2:35:09<6:19:16,  2.35s/it]

Added new genus: Hydrangea (ID: 3331)

Fetching Species:  29%|██▉       | 4002/13683 [2:35:11<6:16:16,  2.33s/it]

Added new genus: Plantago (ID: 3332)

Fetching Species:  29%|██▉       | 4003/13683 [2:35:13<6:20:05,  2.36s/it]

Added new genus: Vanilla (ID: 3333)

Fetching Species:  29%|██▉       | 4005/13683 [2:35:18<6:19:00,  2.35s/it]

Added new genus: Pepino (ID: 3334)

Fetching Species:  29%|██▉       | 4008/13683 [2:35:25<6:09:35,  2.29s/it]

Added new genus: Foxtail (ID: 3335)

Fetching Species:  29%|██▉       | 4011/13683 [2:35:33<6:24:09,  2.38s/it]

Added new genus: Zygocactus (ID: 3336)

Fetching Species:  29%|██▉       | 4012/13683 [2:35:35<6:18:48,  2.35s/it]

Added new genus: Plantain (ID: 3337)

Fetching Species:  29%|██▉       | 4013/13683 [2:35:37<6:21:45,  2.37s/it]

Added new genus: Tamus (ID: 3338)

Fetching Species:  29%|██▉       | 4014/13683 [2:35:40<6:29:44,  2.42s/it]

Added new genus: Senna (ID: 3339)

Fetching Species:  29%|██▉       | 4016/13683 [2:35:44<6:18:54,  2.35s/it]

Added new genus: Lily (ID: 3340)

Fetching Species:  29%|██▉       | 4018/13683 [2:35:49<6:07:00,  2.28s/it]

Added new genus: Schlumbergera (ID: 3341)

Fetching Species:  29%|██▉       | 4024/13683 [2:36:03<6:25:15,  2.39s/it]

Added new genus: Malva (ID: 3342)

Fetching Species:  29%|██▉       | 4026/13683 [2:36:07<6:09:23,  2.30s/it]

Added new genus: Cnidium (ID: 3343)

Fetching Species:  29%|██▉       | 4031/13683 [2:36:19<5:59:58,  2.24s/it]

Added new genus: Garlic (ID: 3344)

Fetching Species:  29%|██▉       | 4033/13683 [2:36:24<6:19:59,  2.36s/it]

Added new genus: Arachis (ID: 3345)

Fetching Species:  30%|██▉       | 4044/13683 [2:36:50<6:46:24,  2.53s/it]

Added new genus: Lolium (ID: 3346)

Fetching Species:  30%|██▉       | 4045/13683 [2:36:53<6:34:39,  2.46s/it]

Added new genus: Ribes (ID: 3347)

Fetching Species:  30%|██▉       | 4046/13683 [2:36:55<6:26:35,  2.41s/it]

Added new genus: Hardenbergia (ID: 3348)

Fetching Species:  30%|██▉       | 4047/13683 [2:36:57<6:14:21,  2.33s/it]

Added new genus: Diuris (ID: 3349)

Fetching Species:  30%|██▉       | 4059/13683 [2:37:26<6:42:16,  2.51s/it]

Added new genus: Heracleum (ID: 3350)

Fetching Species:  30%|██▉       | 4063/13683 [2:37:36<6:26:53,  2.41s/it]

Added new genus: Agave (ID: 3351)

Fetching Species:  30%|██▉       | 4068/13683 [2:37:47<6:13:22,  2.33s/it]

Added new genus: Kalanchoe (ID: 3352)

Fetching Species:  30%|██▉       | 4076/13683 [2:38:05<6:15:58,  2.35s/it]

Added new genus: Ligustrum (ID: 3353)

Fetching Species:  30%|██▉       | 4077/13683 [2:38:08<6:12:53,  2.33s/it]

Added new genus: Helleborus (ID: 3354)

Fetching Species:  30%|██▉       | 4078/13683 [2:38:10<6:11:10,  2.32s/it]

Added new genus: Daphne (ID: 3355)

Fetching Species:  30%|██▉       | 4079/13683 [2:38:12<6:02:43,  2.27s/it]

Added new genus: Sambucus (ID: 3356)

Fetching Species:  30%|██▉       | 4087/13683 [2:38:30<6:06:58,  2.29s/it]

Added new genus: Elderberry (ID: 3357)

Fetching Species:  30%|██▉       | 4088/13683 [2:38:33<6:06:42,  2.29s/it]

Added new genus: Gaillardia (ID: 3358)

Fetching Species:  30%|██▉       | 4090/13683 [2:38:37<6:10:02,  2.31s/it]

Added new genus: Coleus (ID: 3359)

Fetching Species:  30%|██▉       | 4100/13683 [2:39:01<6:09:44,  2.31s/it]

Added new genus: Hippeastrum (ID: 3360)

Fetching Species:  30%|██▉       | 4101/13683 [2:39:03<6:08:10,  2.31s/it]

Added new genus: Poplar (ID: 3361)

Fetching Species:  30%|██▉       | 4103/13683 [2:39:07<6:07:45,  2.30s/it]

Added new genus: Mirabilis (ID: 3362)

Fetching Species:  30%|███       | 4107/13683 [2:39:17<6:11:43,  2.33s/it]

Added new genus: Phlox (ID: 3363)

Fetching Species:  30%|███       | 4109/13683 [2:39:22<6:18:39,  2.37s/it]

Added new genus: Helenium (ID: 3364)

Fetching Species:  30%|███       | 4110/13683 [2:39:24<6:13:49,  2.34s/it]

Added new genus: Atractylodes (ID: 3365)

Fetching Species:  30%|███       | 4112/13683 [2:39:29<6:21:26,  2.39s/it]

Added new genus: Aconite (ID: 3366)

Fetching Species:  30%|███       | 4123/13683 [2:39:54<5:58:12,  2.25s/it]

Added new genus: Butterbur (ID: 3367)

Fetching Species:  30%|███       | 4124/13683 [2:39:56<6:00:12,  2.26s/it]

Added new genus: Jasmine (ID: 3368)

Fetching Species:  30%|███       | 4135/13683 [2:40:22<6:15:52,  2.36s/it]

Added new genus: Peach (ID: 3369)

Fetching Species:  30%|███       | 4137/13683 [2:40:26<6:08:33,  2.32s/it]

Added new genus: Phlomis (ID: 3370)

Fetching Species:  30%|███       | 4140/13683 [2:40:33<6:01:35,  2.27s/it]

Added new genus: Mexico (ID: 3371)

Fetching Species:  30%|███       | 4151/13683 [2:40:58<6:04:40,  2.30s/it]

Added new genus: Currant (ID: 3372)

Fetching Species:  30%|███       | 4152/13683 [2:41:01<6:04:17,  2.29s/it]

Added new genus: Mume (ID: 3373)

Fetching Species:  30%|███       | 4156/13683 [2:41:10<6:12:30,  2.35s/it]

Added new genus: Yacon (ID: 3374)

Fetching Species:  30%|███       | 4160/13683 [2:41:20<6:20:27,  2.40s/it]

Added new genus: Asian (ID: 3375)

Fetching Species:  30%|███       | 4161/13683 [2:41:22<6:08:50,  2.32s/it]

Added new genus: Rubus (ID: 3376)

Fetching Species:  31%|███       | 4180/13683 [2:42:06<6:05:40,  2.31s/it]

Added new genus: Banana (ID: 3377)

Fetching Species:  31%|███       | 4182/13683 [2:42:10<5:59:02,  2.27s/it]

Added new genus: Loquat (ID: 3378)

Fetching Species:  31%|███       | 4185/13683 [2:42:17<6:06:04,  2.31s/it]

Added new genus: Hogweed (ID: 3379)

Fetching Species:  31%|███       | 4191/13683 [2:42:31<5:58:39,  2.27s/it]

Added new genus: Bee (ID: 3380)

Fetching Species:  31%|███       | 4199/13683 [2:42:50<6:04:54,  2.31s/it]

Added new genus: Diascia (ID: 3381)

Fetching Species:  31%|███       | 4204/13683 [2:43:01<5:58:33,  2.27s/it]

Added new genus: Naranjilla (ID: 3382)

Fetching Species:  31%|███       | 4212/13683 [2:43:19<6:00:49,  2.29s/it]

Added new genus: Asclepias (ID: 3383)

Fetching Species:  31%|███       | 4219/13683 [2:43:35<5:55:27,  2.25s/it]

Added new genus: Switchgrass (ID: 3384)

Fetching Species:  31%|███       | 4236/13683 [2:44:15<6:02:43,  2.30s/it]

Added new genus: Soybean-associated (ID: 3385)

Fetching Species:  31%|███       | 4251/13683 [2:44:51<6:35:43,  2.52s/it]

Added new genus: Rana (ID: 3386)

Fetching Species:  31%|███       | 4255/13683 [2:45:00<6:00:53,  2.30s/it]

Added new genus: Burdock (ID: 3387)

Fetching Species:  31%|███       | 4261/13683 [2:45:14<6:09:02,  2.35s/it]

Added new genus: Nudaurelia (ID: 3388)

Fetching Species:  31%|███       | 4263/13683 [2:45:19<6:07:06,  2.34s/it]

Added new genus: Sarawak (ID: 3389)

Fetching Species:  31%|███▏      | 4278/13683 [2:45:53<5:53:54,  2.26s/it]

Added new genus: Culex-associated (ID: 3390)

Fetching Species:  32%|███▏      | 4320/13683 [2:47:28<6:17:27,  2.42s/it]

Added new genus: Bermuda (ID: 3391)

Fetching Species:  32%|███▏      | 4358/13683 [2:48:56<6:24:15,  2.47s/it]

Added new genus: Providence (ID: 3392)

Fetching Species:  32%|███▏      | 4362/13683 [2:49:05<5:55:36,  2.29s/it]

Added new genus: Norway (ID: 3393)

Fetching Species:  32%|███▏      | 4388/13683 [2:50:07<5:55:54,  2.30s/it]

Added new genus: Kampung (ID: 3394)

Fetching Species:  32%|███▏      | 4391/13683 [2:50:15<6:31:35,  2.53s/it]

Added new genus: Tamana (ID: 3395)

Fetching Species:  32%|███▏      | 4397/13683 [2:50:29<6:07:09,  2.37s/it]

Added new genus: Kamiti (ID: 3396)

Fetching Species:  32%|███▏      | 4404/13683 [2:50:45<6:00:04,  2.33s/it]

Added new genus: Quang (ID: 3397)

Fetching Species:  32%|███▏      | 4406/13683 [2:50:50<6:11:27,  2.40s/it]

Added new genus: Chaoyang (ID: 3398)

Fetching Species:  32%|███▏      | 4410/13683 [2:51:00<6:03:09,  2.35s/it]

Added new genus: Donggang (ID: 3399)

Fetching Species:  32%|███▏      | 4415/13683 [2:51:11<5:56:18,  2.31s/it]

Added new genus: Hanko (ID: 3400)

Fetching Species:  32%|███▏      | 4420/13683 [2:51:24<6:36:26,  2.57s/it]

Added new genus: T'Ho (ID: 3401)

Fetching Species:  32%|███▏      | 4422/13683 [2:51:28<6:08:28,  2.39s/it]

Added new genus: Mercadeo (ID: 3402)

Fetching Species:  32%|███▏      | 4426/13683 [2:51:38<5:56:47,  2.31s/it]

Added new genus: Spanish (ID: 3403)

Fetching Species:  32%|███▏      | 4428/13683 [2:51:42<5:56:22,  2.31s/it]

Added new genus: Parramatta (ID: 3404)

Fetching Species:  32%|███▏      | 4432/13683 [2:51:52<6:02:06,  2.35s/it]

Added new genus: Aedes (ID: 3405)

Fetching Species:  32%|███▏      | 4437/13683 [2:52:04<6:10:28,  2.40s/it]

Added new genus: Nanay (ID: 3406)

Fetching Species:  32%|███▏      | 4438/13683 [2:52:06<6:11:58,  2.41s/it]

Added new genus: Kama (ID: 3407)

Fetching Species:  32%|███▏      | 4441/13683 [2:52:14<6:50:43,  2.67s/it]

Added new genus: Paraiso (ID: 3408)

Fetching Species:  32%|███▏      | 4444/13683 [2:52:21<6:12:07,  2.42s/it]

Added new genus: Palm (ID: 3409)

Fetching Species:  33%|███▎      | 4447/13683 [2:52:28<6:14:39,  2.43s/it]

Added new genus: Cell (ID: 3410)

Fetching Species:  33%|███▎      | 4451/13683 [2:52:38<6:02:06,  2.35s/it]

Added new genus: Nounane (ID: 3411)

Fetching Species:  33%|███▎      | 4453/13683 [2:52:42<6:01:16,  2.35s/it]

Added new genus: Ochlerotatus (ID: 3412)

Fetching Species:  33%|███▎      | 4457/13683 [2:52:52<5:52:02,  2.29s/it]

Added new genus: Wenling (ID: 3413)

Fetching Species:  33%|███▎      | 4472/13683 [2:53:27<5:55:22,  2.31s/it]

Added new genus: Mac (ID: 3414)

Fetching Species:  33%|███▎      | 4473/13683 [2:53:29<6:00:33,  2.35s/it]

Added new genus: Xishuangbanna (ID: 3415)

Fetching Species:  33%|███▎      | 4474/13683 [2:53:31<5:57:00,  2.33s/it]

Added new genus: Mogiana (ID: 3416)

Fetching Species:  33%|███▎      | 4475/13683 [2:53:34<6:15:07,  2.44s/it]

Added new genus: Karumba (ID: 3417)

Fetching Species:  33%|███▎      | 4476/13683 [2:53:36<6:07:42,  2.40s/it]

Added new genus: Ilomantsi (ID: 3418)

Fetching Species:  33%|███▎      | 4478/13683 [2:53:41<5:59:22,  2.34s/it]

Added new genus: Bamaga (ID: 3419)

Fetching Species:  33%|███▎      | 4480/13683 [2:53:46<6:02:04,  2.36s/it]

Added new genus: Menghai (ID: 3420)

Fetching Species:  33%|███▎      | 4481/13683 [2:53:48<5:58:19,  2.34s/it]

Added new genus: Nienokoue (ID: 3421)

Fetching Species:  33%|███▎      | 4482/13683 [2:53:50<5:57:39,  2.33s/it]

Added new genus: Lumpfish (ID: 3422)

Fetching Species:  33%|███▎      | 4483/13683 [2:53:53<5:56:40,  2.33s/it]

Added new genus: Culiseta (ID: 3423)

Fetching Species:  33%|███▎      | 4484/13683 [2:53:55<5:54:12,  2.31s/it]

Added new genus: Nakiwogo (ID: 3424)

Fetching Species:  33%|███▎      | 4486/13683 [2:54:00<6:06:11,  2.39s/it]

Added new genus: 2013 (ID: 3425)

Fetching Species:  33%|███▎      | 4487/13683 [2:54:01<5:24:55,  2.12s/it]

Added new genus: Macrosiphum (ID: 3426)

Fetching Species:  33%|███▎      | 4488/13683 [2:54:04<5:39:18,  2.21s/it]

Added new genus: Lammi (ID: 3427)

Fetching Species:  33%|███▎      | 4489/13683 [2:54:06<5:42:45,  2.24s/it]

Added new genus: Nhumirim (ID: 3428)

Fetching Species:  33%|███▎      | 4500/13683 [2:54:32<5:49:35,  2.28s/it]

Added new genus: Tasmanian (ID: 3429)

Fetching Species:  33%|███▎      | 4501/13683 [2:54:34<5:43:11,  2.24s/it]

Added new genus: Victorian (ID: 3430)

Fetching Species:  33%|███▎      | 4504/13683 [2:54:40<5:43:45,  2.25s/it]

Added new genus: Espirito (ID: 3431)

Fetching Species:  33%|███▎      | 4508/13683 [2:54:50<5:48:29,  2.28s/it]

Added new genus: Thosea (ID: 3432)

Fetching Species:  33%|███▎      | 4509/13683 [2:54:52<5:43:18,  2.25s/it]

Added new genus: Euprosterna (ID: 3433)

Fetching Species:  33%|███▎      | 4520/13683 [2:55:23<6:58:15,  2.74s/it]

Added new genus: Escherichia (ID: 3434)

Fetching Species:  33%|███▎      | 4535/13683 [2:56:02<6:30:08,  2.56s/it]

Added new genus: Salmonella (ID: 3435)

Fetching Species:  36%|███▌      | 4878/13683 [3:10:34<6:08:33,  2.51s/it]

Added new genus: Synechococcus (ID: 3436)

Fetching Species:  36%|███▌      | 4903/13683 [3:11:36<6:04:31,  2.49s/it]

Added new genus: Xylella (ID: 3437)

Fetching Species:  37%|███▋      | 5045/13683 [3:17:35<5:54:29,  2.46s/it]

Added new genus: Streptococcus (ID: 3438)

Fetching Species:  37%|███▋      | 5059/13683 [3:18:10<6:01:28,  2.51s/it]

Added new genus: Pseudomonas (ID: 3439)

Fetching Species:  38%|███▊      | 5152/13683 [3:22:15<6:16:53,  2.65s/it]

Added new genus: Klebsiella (ID: 3440)

Fetching Species:  38%|███▊      | 5157/13683 [3:22:29<6:31:01,  2.75s/it]/home/mlima/workspace/envs/rapids-new/lib/python3.12/site-packages/Bio/SeqIO/FastaIO.py:202: BiopythonDeprecationWarning: Previously, the FASTA parser silently ignored comments at the beginning of the FASTA file (before the first sequence).

Nowadays, the FASTA file format is usually understood not to have any such comments, and most software packages do not allow them. Therefore, the use of comments at the beginning of a FASTA file is now deprecated in Biopython.

In a future Biopython release, this deprecation warning will be replaced by a ValueError. To avoid this, there are three options:

(1) Modify your FASTA file to remove such comments at the beginning of the file.

(2) Use SeqIO.parse with the 'fasta-pearson' format instead of 'fasta'. This format is consistent with the FASTA format defined by William Pearson's FASTA aligner software. This format allows for comments before the first sequence; lines starting with the ';' character anywhere in the file are also regarded as comment lines and are ignored.

(3) Use the 'fasta-blast' format. This format regards any lines starting with '!', '#', or ';' as comment lines. The 'fasta-blast' format may be safer than the 'fasta-pearson' format, as it explicitly indicates which lines are comments.
  warnings.warn(
Fetching Species:  38%|███▊      | 5234/13683 [3:26:01<6:43:33,  2.87s/it]

Added new genus: Enterobacteria (ID: 3441)

Fetching Species:  39%|███▉      | 5356/13683 [3:31:52<6:26:38,  2.79s/it]

Added new genus: Cronobacter (ID: 3442)

Fetching Species:  39%|███▉      | 5377/13683 [3:32:51<6:27:18,  2.80s/it]

Added new genus: Acinetobacter (ID: 3443)

Fetching Species:  39%|███▉      | 5380/13683 [3:33:00<6:21:08,  2.75s/it]

Added new genus: Tuaanevirus (ID: 3444)

Fetching Species:  40%|███▉      | 5405/13683 [3:34:11<6:33:06,  2.85s/it]

Added new genus: Rhodococcus (ID: 3445)

Fetching Species:  40%|████      | 5527/13683 [3:39:43<5:34:06,  2.46s/it]

Added new genus: Mycobacterium (ID: 3446)

Fetching Species:  41%|████      | 5611/13683 [3:43:14<5:20:13,  2.38s/it]

Added new genus: Staphylococcus (ID: 3447)

Fetching Species:  41%|████▏     | 5657/13683 [3:45:08<5:29:59,  2.47s/it]

Added new genus: Shigella (ID: 3448)

Fetching Species:  42%|████▏     | 5690/13683 [3:46:31<5:42:44,  2.57s/it]

Added new genus: Gordonia (ID: 3449)

Fetching Species:  42%|████▏     | 5717/13683 [3:47:42<5:34:01,  2.52s/it]

Added new genus: Lactobacillus (ID: 3450)

Fetching Species:  42%|████▏     | 5742/13683 [3:48:47<5:29:41,  2.49s/it]

Added new genus: Propionibacterium (ID: 3451)

Fetching Species:  42%|████▏     | 5794/13683 [3:50:55<5:35:12,  2.55s/it]

Added new genus: Listeria (ID: 3452)

Fetching Species:  43%|████▎     | 5934/13683 [3:57:02<5:41:18,  2.64s/it]

Added new genus: Vibrio (ID: 3453)

Fetching Species:  44%|████▎     | 5968/13683 [3:58:34<6:13:13,  2.90s/it]

Added new genus: Roseovarius (ID: 3454)

Fetching Species:  45%|████▌     | 6223/13683 [4:09:39<5:29:15,  2.65s/it]

Added new genus: Burkholderia (ID: 3455)

Fetching Species:  46%|████▌     | 6231/13683 [4:09:59<5:29:39,  2.65s/it]

Added new genus: 41 (ID: 3456)

Fetching Species:  46%|████▌     | 6232/13683 [4:10:01<4:46:30,  2.31s/it]

Added new genus: 44 (ID: 3457)

Fetching Species:  46%|████▌     | 6233/13683 [4:10:02<4:16:24,  2.06s/it]

Added new genus: 40 (ID: 3458)

Fetching Species:  46%|████▌     | 6234/13683 [4:10:04<3:55:17,  1.90s/it]

Added new genus: 4 (ID: 3459)

Fetching Species:  46%|████▌     | 6290/13683 [4:12:41<5:39:45,  2.76s/it]

Added new genus: Ralstonia (ID: 3460)

Fetching Species:  46%|████▋     | 6354/13683 [4:15:26<5:42:22,  2.80s/it]

Added new genus: Lactococcus (ID: 3461)

Fetching Species:  47%|████▋     | 6478/13683 [4:20:41<5:33:09,  2.77s/it]

Added new genus: Bacillus (ID: 3462)

Fetching Species:  49%|████▊     | 6641/13683 [4:28:05<4:54:20,  2.51s/it]

Added new genus: Serratia (ID: 3463)

Fetching Species:  49%|████▉     | 6764/13683 [4:33:34<5:26:05,  2.83s/it]

Added new genus: Streptomyces (ID: 3464)

Fetching Species:  50%|████▉     | 6837/13683 [4:37:03<5:20:46,  2.81s/it]

Added new genus: Cyanophage (ID: 3465)

Fetching Species:  50%|█████     | 6847/13683 [4:37:33<5:26:55,  2.87s/it]

Added new genus: Pelagibacter (ID: 3466)

Fetching Species:  50%|█████     | 6883/13683 [4:39:09<4:47:26,  2.54s/it]

Added new genus: Stenotrophomonas (ID: 3467)

Fetching Species:  50%|█████     | 6893/13683 [4:39:35<4:54:47,  2.60s/it]

Added new genus: Bordetella (ID: 3468)

Fetching Species:  50%|█████     | 6897/13683 [4:39:46<5:02:08,  2.67s/it]

Added new genus: Xanthomonas (ID: 3469)

Fetching Species:  50%|█████     | 6909/13683 [4:40:18<5:12:56,  2.77s/it]

Added new genus: Janthinobacterium (ID: 3470)

Fetching Species:  51%|█████     | 6940/13683 [4:41:35<4:45:27,  2.54s/it]

Added new genus: Thermus (ID: 3471)

Fetching Species:  51%|█████▏    | 7019/13683 [4:45:07<4:58:36,  2.69s/it]

Added new genus: Microbacterium (ID: 3472)

Fetching Species:  52%|█████▏    | 7059/13683 [4:46:54<5:16:21,  2.87s/it]

Added new genus: Ruegeria (ID: 3473)

Fetching Species:  52%|█████▏    | 7063/13683 [4:47:05<4:52:15,  2.65s/it]

Added new genus: Pectobacterium (ID: 3474)

Fetching Species:  52%|█████▏    | 7068/13683 [4:47:18<4:50:32,  2.64s/it]

Added new genus: Proteus (ID: 3475)

Fetching Species:  52%|█████▏    | 7091/13683 [4:48:17<4:44:36,  2.59s/it]

Added new genus: Sinorhizobium (ID: 3476)

Fetching Species:  52%|█████▏    | 7134/13683 [4:50:09<4:50:56,  2.67s/it]

Added new genus: Arthrobacter (ID: 3477)

Fetching Species:  52%|█████▏    | 7170/13683 [4:51:46<4:50:54,  2.68s/it]

Added new genus: Erwinia (ID: 3478)

Fetching Species:  52%|█████▏    | 7183/13683 [4:52:21<4:58:24,  2.75s/it]

Added new genus: Aeromonas (ID: 3479)

Fetching Species:  53%|█████▎    | 7186/13683 [4:52:29<4:54:21,  2.72s/it]

Added new genus: Yersinia (ID: 3480)

Fetching Species:  53%|█████▎    | 7200/13683 [4:53:06<4:49:33,  2.68s/it]

Added new genus: Cellulophaga (ID: 3481)

Fetching Species:  53%|█████▎    | 7211/13683 [4:53:34<4:40:31,  2.60s/it]

Added new genus: Sodalis (ID: 3482)

Fetching Species:  54%|█████▍    | 7426/13683 [5:02:51<4:31:50,  2.61s/it]

Added new genus: Efkovirus (ID: 3483)

Fetching Species:  55%|█████▍    | 7486/13683 [5:05:24<4:49:35,  2.80s/it]

Added new genus: Caulobacter (ID: 3484)

Fetching Species:  55%|█████▌    | 7549/13683 [5:08:03<4:18:24,  2.53s/it]

Added new genus: Flavobacterium (ID: 3485)

Fetching Species:  55%|█████▌    | 7566/13683 [5:08:47<4:23:14,  2.58s/it]

Added new genus: Campylobacter (ID: 3486)

Fetching Species:  55%|█████▌    | 7593/13683 [5:10:01<4:29:28,  2.65s/it]

Added new genus: Halorubrum (ID: 3487)

Fetching Species:  56%|█████▌    | 7595/13683 [5:10:07<4:31:07,  2.67s/it]

Added new genus: Halovirus (ID: 3488)

Fetching Species:  56%|█████▌    | 7615/13683 [5:10:59<4:28:57,  2.66s/it]

Added new genus: Enterococcus (ID: 3489)

Fetching Species:  56%|█████▌    | 7638/13683 [5:12:00<4:25:04,  2.63s/it]

Added new genus: Corynebacterium (ID: 3490)

Fetching Species:  56%|█████▌    | 7655/13683 [5:12:45<4:22:01,  2.61s/it]

Added new genus: Arthobacter (ID: 3491)

Fetching Species:  57%|█████▋    | 7797/13683 [5:18:57<4:29:58,  2.75s/it]

Added new genus: Clostridium (ID: 3492)

Fetching Species:  57%|█████▋    | 7830/13683 [5:20:28<4:35:49,  2.83s/it]

Added new genus: Brochothrix (ID: 3493)

Fetching Species:  58%|█████▊    | 7953/13683 [5:25:58<4:11:49,  2.64s/it]

Added new genus: Pseudoalteromonas (ID: 3494)

Fetching Species:  58%|█████▊    | 7958/13683 [5:26:12<4:11:16,  2.63s/it]

Added new genus: Leuconostoc (ID: 3495)

Fetching Species:  58%|█████▊    | 7972/13683 [5:26:47<4:01:08,  2.53s/it]

Added new genus: 6 (ID: 3496)

Fetching Species:  59%|█████▊    | 8016/13683 [5:28:45<4:00:09,  2.54s/it]

Added new genus: Enterobacter (ID: 3497)

Fetching Species:  59%|█████▊    | 8019/13683 [5:28:52<4:00:57,  2.55s/it]

Added new genus: Psychrobacter (ID: 3498)

Fetching Species:  59%|█████▉    | 8076/13683 [5:31:24<3:55:39,  2.52s/it]

Added new genus: Hafnia (ID: 3499)

Fetching Species:  59%|█████▉    | 8081/13683 [5:31:37<4:25:07,  2.84s/it]

Added new genus: Mannheimia (ID: 3500)

Fetching Species:  59%|█████▉    | 8088/13683 [5:31:57<4:22:12,  2.81s/it]

Added new genus: Sphingomonas (ID: 3501)

Fetching Species:  60%|█████▉    | 8180/13683 [5:35:56<3:59:52,  2.62s/it]

Added new genus: Weissella (ID: 3502)

Fetching Species:  60%|█████▉    | 8203/13683 [5:36:58<4:30:49,  2.97s/it]

Added new genus: Rhodovulum (ID: 3503)

Fetching Species:  60%|█████▉    | 8205/13683 [5:37:03<4:06:23,  2.70s/it]

Added new genus: Rhodoferax (ID: 3504)

Fetching Species:  60%|██████    | 8245/13683 [5:38:47<4:03:19,  2.68s/it]

Added new genus: Croceibacter (ID: 3505)

Fetching Species:  61%|██████    | 8283/13683 [5:40:29<3:54:38,  2.61s/it]

Added new genus: Rhodobacter (ID: 3506)

Fetching Species:  61%|██████    | 8300/13683 [5:41:13<3:47:55,  2.54s/it]

Added new genus: Yangshan (ID: 3507)

Fetching Species:  61%|██████    | 8335/13683 [5:42:49<3:43:40,  2.51s/it]

Added new genus: 1 (ID: 3508)

Fetching Species:  61%|██████▏   | 8403/13683 [5:45:50<4:02:38,  2.76s/it]

Added new genus: Thalassomonas (ID: 3509)

Fetching Species:  61%|██████▏   | 8408/13683 [5:46:03<3:49:36,  2.61s/it]

Added new genus: Glutamicibacter (ID: 3510)

Fetching Species:  62%|██████▏   | 8418/13683 [5:46:31<3:54:55,  2.68s/it]

Added new genus: Nitrincola (ID: 3511)

Fetching Species:  62%|██████▏   | 8471/13683 [5:48:54<3:58:27,  2.75s/it]

Added new genus: Myranavirus (ID: 3512)

Fetching Species:  62%|██████▏   | 8492/13683 [5:49:48<3:38:25,  2.52s/it]

Added new genus: R656 (ID: 3513)

Fetching Species:  62%|██████▏   | 8493/13683 [5:49:49<3:11:45,  2.22s/it]

Added new genus: P54_PAE_BP (ID: 3514)

Fetching Species:  62%|██████▏   | 8495/13683 [5:49:53<3:08:13,  2.18s/it]

Added new genus: Prochlorococcus (ID: 3515)

Fetching Species:  63%|██████▎   | 8565/13683 [5:52:54<3:51:54,  2.72s/it]

Added new genus: Paenibacillus (ID: 3516)

Fetching Species:  63%|██████▎   | 8571/13683 [5:53:10<3:47:22,  2.67s/it]

Added new genus: Riemerella (ID: 3517)

Fetching Species:  63%|██████▎   | 8627/13683 [5:55:38<3:28:45,  2.48s/it]

Added new genus: Lucadorvirus (ID: 3518)

Fetching Species:  63%|██████▎   | 8668/13683 [5:57:28<3:40:02,  2.63s/it]

Added new genus: Brevibacillus (ID: 3519)

Fetching Species:  63%|██████▎   | 8680/13683 [5:57:59<3:35:01,  2.58s/it]

Added new genus: Helicobacter (ID: 3520)

Fetching Species:  64%|██████▎   | 8705/13683 [5:59:03<3:26:36,  2.49s/it]

Added new genus: Bifidobacterium (ID: 3521)

Fetching Species:  64%|██████▎   | 8706/13683 [5:59:05<3:21:42,  2.43s/it]

Added new genus: Idiomarinaceae (ID: 3522)

Fetching Species:  64%|██████▎   | 8720/13683 [5:59:40<3:28:16,  2.52s/it]

Added new genus: Methanoculleus (ID: 3523)

Fetching Species:  64%|██████▎   | 8722/13683 [5:59:45<3:27:54,  2.51s/it]

Added new genus: Rhizobium (ID: 3524)

Fetching Species:  64%|██████▍   | 8736/13683 [6:00:23<3:37:18,  2.64s/it]

Added new genus: Achromobacter (ID: 3525)

Fetching Species:  64%|██████▍   | 8751/13683 [6:01:01<3:18:45,  2.42s/it]

Added new genus: Azospirillum (ID: 3526)

Fetching Species:  64%|██████▍   | 8813/13683 [6:03:47<3:34:10,  2.64s/it]

Added new genus: Methanothermobacter (ID: 3527)

Fetching Species:  65%|██████▍   | 8830/13683 [6:04:31<3:30:42,  2.61s/it]

Added new genus: Marinomonas (ID: 3528)

Fetching Species:  65%|██████▍   | 8840/13683 [6:04:58<3:33:16,  2.64s/it]

Added new genus: Halocynthia (ID: 3529)

Fetching Species:  65%|██████▍   | 8857/13683 [6:05:43<3:28:14,  2.59s/it]

Added new genus: Salicola (ID: 3530)

Fetching Species:  65%|██████▍   | 8891/13683 [6:07:12<3:21:00,  2.52s/it]

Added new genus: Brucella (ID: 3531)

Fetching Species:  65%|██████▌   | 8899/13683 [6:07:33<3:35:03,  2.70s/it]

Added new genus: Haemophilus (ID: 3532)

Fetching Species:  65%|██████▌   | 8913/13683 [6:08:12<3:52:49,  2.93s/it]

Added new genus: Tsukamurella (ID: 3533)

Fetching Species:  66%|██████▌   | 8978/13683 [6:11:06<3:26:42,  2.64s/it]

Added new genus: Sulfitobacter (ID: 3534)

Fetching Species:  66%|██████▌   | 9014/13683 [6:12:43<3:24:24,  2.63s/it]

Added new genus: Bdellovibrio (ID: 3535)

Fetching Species:  66%|██████▌   | 9023/13683 [6:13:07<3:34:17,  2.76s/it]

Added new genus: uncultured (ID: 3536)

Fetching Species:  66%|██████▌   | 9032/13683 [6:13:30<3:21:19,  2.60s/it]

Added new genus: Curtobacterium (ID: 3537)

Fetching Species:  66%|██████▌   | 9034/13683 [6:13:35<3:15:33,  2.52s/it]

Added new genus: Nocardia (ID: 3538)

Fetching Species:  66%|██████▌   | 9052/13683 [6:14:21<3:29:03,  2.71s/it]

Added new genus: Alteromonas (ID: 3539)

Fetching Species:  66%|██████▌   | 9063/13683 [6:14:50<3:22:59,  2.64s/it]

Added new genus: Baxtervirus (ID: 3540)

Fetching Species:  66%|██████▋   | 9077/13683 [6:15:26<3:26:23,  2.69s/it]

Added new genus: Geobacillus (ID: 3541)

Fetching Species:  66%|██████▋   | 9091/13683 [6:16:05<3:33:17,  2.79s/it]

Added new genus: Bacteroides (ID: 3542)

Fetching Species:  67%|██████▋   | 9100/13683 [6:16:27<3:10:35,  2.50s/it]

Added new genus: Rhodothermus (ID: 3543)

Fetching Species:  67%|██████▋   | 9101/13683 [6:16:30<3:12:14,  2.52s/it]

Added new genus: Rothia (ID: 3544)

Fetching Species:  67%|██████▋   | 9107/13683 [6:16:47<3:31:15,  2.77s/it]

Added new genus: Deep-sea (ID: 3545)

Fetching Species:  67%|██████▋   | 9110/13683 [6:16:55<3:25:12,  2.69s/it]

Added new genus: Phreappuccinovirus (ID: 3546)

Fetching Species:  67%|██████▋   | 9156/13683 [6:18:55<3:13:15,  2.56s/it]

Added new genus: 49 (ID: 3547)

Fetching Species:  67%|██████▋   | 9160/13683 [6:19:04<3:01:47,  2.41s/it]

Added new genus: Paracoccus (ID: 3548)

Fetching Species:  67%|██████▋   | 9164/13683 [6:19:14<3:05:13,  2.46s/it]

Added new genus: Thermoanaerobacterium (ID: 3549)

Fetching Species:  67%|██████▋   | 9191/13683 [6:20:25<3:32:18,  2.84s/it]

Added new genus: Tetraselmis (ID: 3550)

Fetching Species:  68%|██████▊   | 9241/13683 [6:22:36<3:15:05,  2.64s/it]

Added new genus: R2096 (ID: 3551)

Fetching Species:  68%|██████▊   | 9250/13683 [6:23:00<3:44:46,  3.04s/it]

Added new genus: Verrucomicrobia (ID: 3552)

Fetching Species:  68%|██████▊   | 9258/13683 [6:23:21<3:18:47,  2.70s/it]

Added new genus: Aggregatibacter (ID: 3553)

Fetching Species:  68%|██████▊   | 9281/13683 [6:24:22<3:14:23,  2.65s/it]

Added new genus: Puniceispirillum (ID: 3554)

Fetching Species:  68%|██████▊   | 9291/13683 [6:24:47<3:05:22,  2.53s/it]

Added new genus: Erysipelothrix (ID: 3555)

Fetching Species:  68%|██████▊   | 9326/13683 [6:26:17<3:01:36,  2.50s/it]

Added new genus: Liberibacter (ID: 3556)

Fetching Species:  68%|██████▊   | 9338/13683 [6:26:48<3:05:33,  2.56s/it]

Added new genus: Planktothrix (ID: 3557)

Fetching Species:  69%|██████▊   | 9381/13683 [6:28:41<3:11:17,  2.67s/it]

Added new genus: Listonella (ID: 3558)

Fetching Species:  69%|██████▊   | 9394/13683 [6:29:14<3:01:47,  2.54s/it]

Added new genus: Actinoplanes (ID: 3559)

Fetching Species:  69%|██████▉   | 9425/13683 [6:30:33<3:02:44,  2.58s/it]

Added new genus: Dunaliella (ID: 3560)

Fetching Species:  69%|██████▉   | 9431/13683 [6:30:48<2:58:22,  2.52s/it]

Added new genus: Aurantimonas (ID: 3561)

Fetching Species:  69%|██████▉   | 9440/13683 [6:31:11<2:57:57,  2.52s/it]

Added new genus: Flyfo (ID: 3562)

Fetching Species:  69%|██████▉   | 9477/13683 [6:32:47<3:00:15,  2.57s/it]

Added new genus: Abalone (ID: 3563)

Fetching Species:  69%|██████▉   | 9485/13683 [6:33:09<3:14:55,  2.79s/it]

Added new genus: Cynomolgus (ID: 3564)

Fetching Species:  70%|██████▉   | 9529/13683 [6:35:04<3:04:17,  2.66s/it]

Added new genus: Equid (ID: 3565)

Fetching Species:  70%|███████   | 9580/13683 [6:37:26<2:44:40,  2.41s/it]

Added new genus: Elephant (ID: 3566)

Fetching Species:  70%|███████   | 9587/13683 [6:37:46<3:08:49,  2.77s/it]

Added new genus: Eptesicus (ID: 3567)

Fetching Species:  70%|███████   | 9590/13683 [6:37:53<2:53:50,  2.55s/it]

Added new genus: Cacatuid (ID: 3568)

Fetching Species:  70%|███████   | 9591/13683 [6:37:56<2:57:25,  2.60s/it]

Added new genus: Macropodid (ID: 3569)

Fetching Species:  70%|███████   | 9600/13683 [6:38:20<3:05:28,  2.73s/it]

Added new genus: Bufonid (ID: 3570)

Fetching Species:  71%|███████   | 9666/13683 [6:40:49<2:28:33,  2.22s/it]

Added new genus: Giant (ID: 3571)

Fetching Species:  71%|███████   | 9687/13683 [6:41:36<2:24:19,  2.17s/it]

Added new genus: Sewage-associated (ID: 3572)

Fetching Species:  71%|███████   | 9690/13683 [6:41:43<2:24:04,  2.16s/it]

Error fetching Gemycircularvirus hydro1: Search Backend failed:

Fetching Species:  71%|███████   | 9691/13683 [6:41:44<2:10:40,  1.96s/it]

Error fetching Gemycircularvirus cassa1: Search Backend failed:

Fetching Species:  71%|███████▏  | 9755/13683 [6:44:20<2:30:16,  2.30s/it]

Added new genus: Genomoviridae (ID: 3573)

Fetching Species:  71%|███████▏  | 9773/13683 [6:45:08<2:30:36,  2.31s/it]

Added new genus: Thrips-associated (ID: 3574)

Fetching Species:  72%|███████▏  | 9788/13683 [6:45:41<2:23:19,  2.21s/it]

Added new genus: Lepus (ID: 3575)

Fetching Species:  72%|███████▏  | 9795/13683 [6:45:58<2:32:26,  2.35s/it]

Added new genus: Blackfly (ID: 3576)

Fetching Species:  72%|███████▏  | 9797/13683 [6:46:04<2:43:16,  2.52s/it]

Added new genus: Alces (ID: 3577)

Fetching Species:  72%|███████▏  | 9798/13683 [6:46:06<2:36:20,  2.41s/it]

Added new genus: Gemytondvirus (ID: 3578)

Fetching Species:  72%|███████▏  | 9799/13683 [6:46:08<2:31:17,  2.34s/it]

Added new genus: Gemyvongvirus (ID: 3579)

Fetching Species:  72%|███████▏  | 9801/13683 [6:46:13<2:33:07,  2.37s/it]

Added new genus: Ageratum (ID: 3580)

Fetching Species:  72%|███████▏  | 9802/13683 [6:46:15<2:31:16,  2.34s/it]

Added new genus: Clerodendrum (ID: 3581)

Fetching Species:  72%|███████▏  | 9803/13683 [6:46:17<2:30:05,  2.32s/it]

Added new genus: Dalechampia (ID: 3582)

Fetching Species:  72%|███████▏  | 9804/13683 [6:46:20<2:30:07,  2.32s/it]

Added new genus: Hybanthus (ID: 3583)

Fetching Species:  72%|███████▏  | 9805/13683 [6:46:23<2:52:32,  2.67s/it]

Added new genus: Dicliptera (ID: 3584)

Fetching Species:  72%|███████▏  | 9806/13683 [6:46:25<2:42:22,  2.51s/it]

Added new genus: Malvastrum (ID: 3585)

Fetching Species:  72%|███████▏  | 9807/13683 [6:46:28<2:38:31,  2.45s/it]

Added new genus: Mungbean (ID: 3586)

Fetching Species:  72%|███████▏  | 9808/13683 [6:46:30<2:32:26,  2.36s/it]

Added new genus: Blainvillea (ID: 3587)

Fetching Species:  72%|███████▏  | 9810/13683 [6:46:34<2:25:39,  2.26s/it]

Added new genus: Bitter (ID: 3588)

Fetching Species:  72%|███████▏  | 9813/13683 [6:46:41<2:28:17,  2.30s/it]

Added new genus: Sida (ID: 3589)

Fetching Species:  72%|███████▏  | 9814/13683 [6:46:43<2:25:51,  2.26s/it]

Added new genus: Sidastrum (ID: 3590)

Fetching Species:  72%|███████▏  | 9816/13683 [6:46:52<3:49:29,  3.56s/it]

Added new genus: Cnidoscolus (ID: 3591)

Fetching Species:  72%|███████▏  | 9817/13683 [6:46:54<3:24:48,  3.18s/it]

Added new genus: Honeysuckle (ID: 3592)

Fetching Species:  72%|███████▏  | 9819/13683 [6:46:59<3:03:59,  2.86s/it]

Added new genus: Vernonia (ID: 3593)

Fetching Species:  72%|███████▏  | 9822/13683 [6:47:06<2:41:21,  2.51s/it]

Added new genus: East (ID: 3594)

Fetching Species:  72%|███████▏  | 9823/13683 [6:47:09<2:38:15,  2.46s/it]

Added new genus: Macroptilium (ID: 3595)

Fetching Species:  72%|███████▏  | 9825/13683 [6:47:13<2:36:18,  2.43s/it]

Added new genus: Jatropha (ID: 3596)

Fetching Species:  72%|███████▏  | 9828/13683 [6:47:21<2:44:34,  2.56s/it]

Added new genus: Chilli (ID: 3597)

Fetching Species:  72%|███████▏  | 9831/13683 [6:47:28<2:35:10,  2.42s/it]

Added new genus: Ipomoea (ID: 3598)

Fetching Species:  72%|███████▏  | 9835/13683 [6:47:37<2:32:13,  2.37s/it]

Added new genus: Rhynchosia (ID: 3599)

Fetching Species:  72%|███████▏  | 9837/13683 [6:47:42<2:33:18,  2.39s/it]

Added new genus: Passionfruit (ID: 3600)

Fetching Species:  72%|███████▏  | 9843/13683 [6:47:57<2:34:08,  2.41s/it]

Added new genus: Corchorus (ID: 3601)

Fetching Species:  72%|███████▏  | 9844/13683 [6:47:59<2:29:06,  2.33s/it]

Added new genus: Malachra (ID: 3602)

Fetching Species:  72%|███████▏  | 9845/13683 [6:48:01<2:25:52,  2.28s/it]

Added new genus: Telfairia (ID: 3603)

Fetching Species:  72%|███████▏  | 9847/13683 [6:48:06<2:23:15,  2.24s/it]

Added new genus: Kudzu (ID: 3604)

Fetching Species:  72%|███████▏  | 9851/13683 [6:48:15<2:20:15,  2.20s/it]

Added new genus: French (ID: 3605)

Fetching Species:  72%|███████▏  | 9853/13683 [6:48:19<2:21:14,  2.21s/it]

Added new genus: Verbena (ID: 3606)

Fetching Species:  72%|███████▏  | 9856/13683 [6:48:26<2:26:13,  2.29s/it]

Added new genus: Pavonia (ID: 3607)

Fetching Species:  72%|███████▏  | 9858/13683 [6:48:30<2:11:32,  2.06s/it]

Added new genus: West (ID: 3608)

Fetching Species:  72%|███████▏  | 9872/13683 [6:49:04<2:41:43,  2.55s/it]

Added new genus: Lycianthes (ID: 3609)

Fetching Species:  72%|███████▏  | 9873/13683 [6:49:07<2:36:42,  2.47s/it]

Added new genus: Chenopodium (ID: 3610)

Fetching Species:  72%|███████▏  | 9877/13683 [6:49:16<2:28:22,  2.34s/it]

Added new genus: Senecio (ID: 3611)

Fetching Species:  72%|███████▏  | 9881/13683 [6:49:26<2:40:21,  2.53s/it]

Added new genus: Stachytarpheta (ID: 3612)

Fetching Species:  72%|███████▏  | 9886/13683 [6:49:38<2:31:14,  2.39s/it]

Added new genus: Leonurus (ID: 3613)

Fetching Species:  72%|███████▏  | 9888/13683 [6:49:43<2:25:45,  2.30s/it]

Added new genus: Okra (ID: 3614)

Fetching Species:  72%|███████▏  | 9898/13683 [6:50:07<2:31:40,  2.40s/it]

Added new genus: Merremia (ID: 3615)

Fetching Species:  72%|███████▏  | 9908/13683 [6:50:30<2:26:51,  2.33s/it]

Added new genus: Ludwigia (ID: 3616)

Fetching Species:  72%|███████▏  | 9909/13683 [6:50:33<2:30:06,  2.39s/it]

Added new genus: Mimosa (ID: 3617)

Fetching Species:  72%|███████▏  | 9910/13683 [6:50:36<2:45:25,  2.63s/it]

Added new genus: Hollyhock (ID: 3618)

Fetching Species:  72%|███████▏  | 9916/13683 [6:50:51<2:33:14,  2.44s/it]

Added new genus: Melochia (ID: 3619)

Fetching Species:  73%|███████▎  | 9921/13683 [6:51:02<2:27:04,  2.35s/it]

Added new genus: Cabbage (ID: 3620)

Fetching Species:  73%|███████▎  | 9924/13683 [6:51:10<2:31:12,  2.41s/it]

Added new genus: Desmodium (ID: 3621)

Fetching Species:  73%|███████▎  | 9928/13683 [6:51:19<2:33:06,  2.45s/it]

Added new genus: Croton (ID: 3622)

Fetching Species:  73%|███████▎  | 9929/13683 [6:51:21<2:27:54,  2.36s/it]

Added new genus: Jacquemontia (ID: 3623)

Fetching Species:  73%|███████▎  | 9932/13683 [6:51:28<2:25:03,  2.32s/it]

Added new genus: Asystasia (ID: 3624)

Fetching Species:  73%|███████▎  | 9942/13683 [6:51:54<2:48:31,  2.70s/it]

Added new genus: Triumfetta (ID: 3625)

Fetching Species:  73%|███████▎  | 9947/13683 [6:52:07<2:44:35,  2.64s/it]

Added new genus: Bhendi (ID: 3626)

Fetching Species:  73%|███████▎  | 9949/13683 [6:52:12<2:40:07,  2.57s/it]

Added new genus: Mesta (ID: 3627)

Fetching Species:  73%|███████▎  | 9965/13683 [6:52:53<2:21:35,  2.28s/it]

Added new genus: Datura (ID: 3628)

Fetching Species:  73%|███████▎  | 9973/13683 [6:53:12<2:22:10,  2.30s/it]

Added new genus: Chino (ID: 3629)

Fetching Species:  73%|███████▎  | 9982/13683 [6:53:35<2:34:02,  2.50s/it]

Added new genus: 2014] (ID: 3630)

Fetching Species:  73%|███████▎  | 9984/13683 [6:53:40<2:40:29,  2.60s/it]

Added new genus: Whitefly-associated (ID: 3631)

Fetching Species:  73%|███████▎  | 10008/13683 [6:54:36<2:21:53,  2.32s/it]

Added new genus: Eupatorium (ID: 3632)

Fetching Species:  73%|███████▎  | 10022/13683 [6:55:08<2:18:54,  2.28s/it]

Added new genus: Gossypium (ID: 3633)

Fetching Species:  73%|███████▎  | 10023/13683 [6:55:10<2:19:28,  2.29s/it]

Added new genus: South (ID: 3634)

Fetching Species:  73%|███████▎  | 10028/13683 [6:55:24<2:40:12,  2.63s/it]

Added new genus: Catharanthus (ID: 3635)

Fetching Species:  73%|███████▎  | 10038/13683 [6:55:48<2:20:45,  2.32s/it]

Added new genus: Centrosema (ID: 3636)

Fetching Species:  73%|███████▎  | 10048/13683 [6:56:11<2:18:07,  2.28s/it]

Added new genus: Clerodendron (ID: 3637)

Fetching Species:  74%|███████▎  | 10058/13683 [6:56:35<2:26:38,  2.43s/it]

Added new genus: Hedyotis (ID: 3638)

Fetching Species:  74%|███████▎  | 10061/13683 [6:56:41<2:19:37,  2.31s/it]

Added new genus: Chayote (ID: 3639)

Fetching Species:  74%|███████▎  | 10063/13683 [6:56:46<2:14:27,  2.23s/it]

Added new genus: Wissadula (ID: 3640)

Fetching Species:  74%|███████▎  | 10066/13683 [6:56:52<2:13:56,  2.22s/it]

Added new genus: Crassocephalum (ID: 3641)

Fetching Species:  74%|███████▎  | 10069/13683 [6:56:59<2:16:36,  2.27s/it]

Added new genus: Synedrella (ID: 3642)

Fetching Species:  74%|███████▎  | 10074/13683 [6:57:10<2:11:05,  2.18s/it]

Added new genus: Kenaf (ID: 3643)

Fetching Species:  74%|███████▎  | 10075/13683 [6:57:12<2:11:44,  2.19s/it]

Added new genus: Radish (ID: 3644)

Fetching Species:  74%|███████▎  | 10077/13683 [6:57:17<2:12:23,  2.20s/it]

Added new genus: Oxalis (ID: 3645)

Fetching Species:  74%|███████▎  | 10085/13683 [6:57:35<2:22:47,  2.38s/it]

Added new genus: Hemidesmus (ID: 3646)

Fetching Species:  74%|███████▎  | 10090/13683 [6:57:48<2:22:11,  2.37s/it]

Added new genus: Abutilon (ID: 3647)

Fetching Species:  74%|███████▍  | 10093/13683 [6:57:54<2:18:03,  2.31s/it]

Added new genus: Lisianthus (ID: 3648)

Fetching Species:  74%|███████▍  | 10094/13683 [6:57:57<2:17:44,  2.30s/it]

Added new genus: Emilia (ID: 3649)

Fetching Species:  74%|███████▍  | 10099/13683 [6:58:08<2:14:53,  2.26s/it]

Added new genus: Sunn (ID: 3650)

Fetching Species:  74%|███████▍  | 10105/13683 [6:58:21<2:13:01,  2.23s/it]

Added new genus: Siegesbeckia (ID: 3651)

Fetching Species:  74%|███████▍  | 10116/13683 [6:58:46<2:10:32,  2.20s/it]

Added new genus: Sri (ID: 3652)

Fetching Species:  74%|███████▍  | 10121/13683 [6:58:57<2:08:56,  2.17s/it]

Added new genus: Duranta (ID: 3653)

Fetching Species:  74%|███████▍  | 10128/13683 [6:59:13<2:11:39,  2.22s/it]

Added new genus: Pedilanthus (ID: 3654)

Fetching Species:  74%|███████▍  | 10132/13683 [6:59:21<2:10:56,  2.21s/it]

Added new genus: Vigna (ID: 3655)

Fetching Species:  74%|███████▍  | 10138/13683 [6:59:35<2:15:00,  2.29s/it]

Added new genus: Pouzolzia (ID: 3656)

Fetching Species:  74%|███████▍  | 10152/13683 [7:00:06<2:10:25,  2.22s/it]

Added new genus: Ramie (ID: 3657)

Fetching Species:  74%|███████▍  | 10169/13683 [7:00:44<2:08:43,  2.20s/it]

Added new genus: Dolichos (ID: 3658)

Fetching Species:  74%|███████▍  | 10172/13683 [7:00:51<2:13:40,  2.28s/it]

Added new genus: Capraria (ID: 3659)

Fetching Species:  74%|███████▍  | 10180/13683 [7:01:09<2:09:52,  2.22s/it]

Added new genus: Blechum (ID: 3660)

Fetching Species:  75%|███████▍  | 10200/13683 [7:01:54<2:10:55,  2.26s/it]

Added new genus: Eclipta (ID: 3661)

Fetching Species:  75%|███████▍  | 10213/13683 [7:02:24<2:08:29,  2.22s/it]

Added new genus: Horsegram (ID: 3662)

Fetching Species:  75%|███████▍  | 10235/13683 [7:03:12<2:08:33,  2.24s/it]

Added new genus: Vinca (ID: 3663)

Fetching Species:  75%|███████▍  | 10242/13683 [7:03:29<2:13:28,  2.33s/it]

Added new genus: Deinbollia (ID: 3664)

Fetching Species:  75%|███████▍  | 10259/13683 [7:04:07<2:09:31,  2.27s/it]

Added new genus: Boerhavia (ID: 3665)

Fetching Species:  75%|███████▍  | 10260/13683 [7:04:09<2:07:38,  2.24s/it]

Added new genus: Lindernia (ID: 3666)

Fetching Species:  75%|███████▌  | 10264/13683 [7:04:18<2:09:54,  2.28s/it]

Added new genus: Erectites (ID: 3667)

Fetching Species:  75%|███████▌  | 10273/13683 [7:04:38<2:04:27,  2.19s/it]

Added new genus: Premna (ID: 3668)

Fetching Species:  75%|███████▌  | 10275/13683 [7:04:43<2:08:33,  2.26s/it]

Added new genus: Spilanthes (ID: 3669)

Fetching Species:  75%|███████▌  | 10296/13683 [7:05:30<2:04:18,  2.20s/it]

Added new genus: Chloris (ID: 3670)

Fetching Species:  75%|███████▌  | 10302/13683 [7:05:43<2:09:36,  2.30s/it]

Added new genus: Axonopus (ID: 3671)

Fetching Species:  75%|███████▌  | 10304/13683 [7:05:48<2:10:18,  2.31s/it]

Added new genus: Digitaria (ID: 3672)

Fetching Species:  75%|███████▌  | 10305/13683 [7:05:51<2:14:28,  2.39s/it]

Added new genus: Sporobolus (ID: 3673)

Fetching Species:  75%|███████▌  | 10307/13683 [7:05:55<2:07:29,  2.27s/it]

Added new genus: Eragrostis (ID: 3674)

Fetching Species:  75%|███████▌  | 10311/13683 [7:06:04<2:10:12,  2.32s/it]

Added new genus: Dragonfly-associated (ID: 3675)

Fetching Species:  75%|███████▌  | 10316/13683 [7:06:16<2:05:31,  2.24s/it]

Added new genus: Paspalum (ID: 3676)

Fetching Species:  75%|███████▌  | 10322/13683 [7:06:29<2:05:03,  2.23s/it]

Added new genus: Urochloa (ID: 3677)

Fetching Species:  75%|███████▌  | 10323/13683 [7:06:31<2:07:16,  2.27s/it]

Added new genus: Bromus (ID: 3678)

Fetching Species:  75%|███████▌  | 10330/13683 [7:06:47<2:04:44,  2.23s/it]

Added new genus: Eleusine (ID: 3679)

Fetching Species:  76%|███████▌  | 10331/13683 [7:06:51<2:42:11,  2.90s/it]

Added new genus: Miscanthus (ID: 3680)

Fetching Species:  76%|███████▌  | 10332/13683 [7:06:54<2:34:31,  2.77s/it]

Added new genus: Panicum (ID: 3681)

Fetching Species:  76%|███████▌  | 10336/13683 [7:07:04<2:25:06,  2.60s/it]

Added new genus: Saccharum (ID: 3682)

Fetching Species:  76%|███████▌  | 10344/13683 [7:07:23<2:13:58,  2.41s/it]

Added new genus: Sesame (ID: 3683)

Fetching Species:  76%|███████▌  | 10346/13683 [7:07:28<2:15:05,  2.43s/it]

Added new genus: Peristrophe (ID: 3684)

Fetching Species:  76%|███████▌  | 10349/13683 [7:07:35<2:05:47,  2.26s/it]

Added new genus: Exomis (ID: 3685)

Fetching Species:  76%|███████▌  | 10351/13683 [7:07:39<2:06:12,  2.27s/it]

Added new genus: Niminivirus (ID: 3686)

Fetching Species:  76%|███████▌  | 10356/13683 [7:07:51<2:08:54,  2.32s/it]

Added new genus: Horseradish (ID: 3687)

Fetching Species:  76%|███████▌  | 10357/13683 [7:07:53<2:06:23,  2.28s/it]

Added new genus: Polygala (ID: 3688)

Fetching Species:  76%|███████▌  | 10362/13683 [7:08:04<2:07:01,  2.29s/it]

Added new genus: Limeum (ID: 3689)

Fetching Species:  76%|███████▌  | 10365/13683 [7:08:11<2:09:03,  2.33s/it]

Added new genus: Paper (ID: 3690)

Fetching Species:  76%|███████▌  | 10367/13683 [7:08:16<2:05:36,  2.27s/it]

Added new genus: Juncus (ID: 3691)

Fetching Species:  76%|███████▌  | 10371/13683 [7:08:25<2:06:21,  2.29s/it]

Added new genus: Baminivirus (ID: 3692)

Fetching Species:  76%|███████▌  | 10373/13683 [7:08:29<2:07:02,  2.30s/it]

Added new genus: Melinis (ID: 3693)

Fetching Species:  76%|███████▌  | 10375/13683 [7:08:34<2:06:37,  2.30s/it]

Added new genus: Rat (ID: 3694)

Fetching Species:  76%|███████▌  | 10377/13683 [7:08:39<2:04:36,  2.26s/it]

Added new genus: Camel (ID: 3695)

Fetching Species:  76%|███████▌  | 10386/13683 [7:08:59<2:06:40,  2.31s/it]

Added new genus: Chimpanzee (ID: 3696)

Fetching Species:  76%|███████▌  | 10419/13683 [7:10:14<2:04:05,  2.28s/it]

Added new genus: Lemur (ID: 3697)

Fetching Species:  76%|███████▌  | 10423/13683 [7:10:23<2:03:25,  2.27s/it]

Added new genus: PoSCV (ID: 3698)

Fetching Species:  76%|███████▋  | 10435/13683 [7:10:50<2:01:42,  2.25s/it]

Added new genus: Cosmacovirus (ID: 3699)

Fetching Species:  76%|███████▋  | 10436/13683 [7:10:53<2:03:03,  2.27s/it]

Added new genus: Smacoviridae (ID: 3700)

Fetching Species:  76%|███████▋  | 10440/13683 [7:11:02<2:03:17,  2.28s/it]

Added new genus: Felismacovirus (ID: 3701)

Fetching Species:  76%|███████▋  | 10441/13683 [7:11:04<2:00:59,  2.24s/it]

Added new genus: Pig (ID: 3702)

Fetching Species:  76%|███████▋  | 10445/13683 [7:11:13<1:58:43,  2.20s/it]

Added new genus: Bostasmacovirus (ID: 3703)

Fetching Species:  76%|███████▋  | 10448/13683 [7:11:20<2:03:53,  2.30s/it]

Added new genus: Bonzesmacovirus (ID: 3704)

Fetching Species:  76%|███████▋  | 10449/13683 [7:11:22<2:01:53,  2.26s/it]

Added new genus: Dragsmacovirus (ID: 3705)

Fetching Species:  76%|███████▋  | 10450/13683 [7:11:24<1:59:54,  2.23s/it]

Added new genus: Inpeasmacovirus (ID: 3706)

Fetching Species:  76%|███████▋  | 10455/13683 [7:11:35<2:01:13,  2.25s/it]

Added new genus: Bacilladnaviridae (ID: 3707)

Fetching Species:  77%|███████▋  | 10472/13683 [7:12:15<2:02:34,  2.29s/it]

Added new genus: Fiddler (ID: 3708)

Fetching Species:  77%|███████▋  | 10475/13683 [7:12:21<1:59:50,  2.24s/it]

Added new genus: Dragonfly (ID: 3709)

Fetching Species:  77%|███████▋  | 10481/13683 [7:12:35<2:01:25,  2.28s/it]

Added new genus: Chifec (ID: 3710)

Fetching Species:  77%|███████▋  | 10484/13683 [7:12:41<1:56:45,  2.19s/it]

Added new genus: Army (ID: 3711)

Fetching Species:  77%|███████▋  | 10499/13683 [7:13:14<2:00:36,  2.27s/it]

Added new genus: Mongoose-associated (ID: 3712)

Fetching Species:  77%|███████▋  | 10502/13683 [7:13:22<2:08:50,  2.43s/it]

Added new genus: 2009 (ID: 3713)

Fetching Species:  77%|███████▋  | 10531/13683 [7:14:26<1:55:23,  2.20s/it]

Added new genus: Dipodfec (ID: 3714)

Fetching Species:  77%|███████▋  | 10539/13683 [7:14:44<1:56:44,  2.23s/it]

Added new genus: Werosea (ID: 3715)

Fetching Species:  77%|███████▋  | 10558/13683 [7:15:26<1:55:25,  2.22s/it]

Added new genus: Avon-Heathcote (ID: 3716)

Fetching Species:  77%|███████▋  | 10559/13683 [7:15:29<1:54:18,  2.20s/it]

Added new genus: Calanoida (ID: 3717)

Fetching Species:  77%|███████▋  | 10560/13683 [7:15:31<1:53:51,  2.19s/it]

Added new genus: Marine (ID: 3718)

Fetching Species:  77%|███████▋  | 10566/13683 [7:15:44<1:56:13,  2.24s/it]

Added new genus: Molossus (ID: 3719)

Fetching Species:  77%|███████▋  | 10567/13683 [7:15:46<1:55:02,  2.22s/it]

Added new genus: Sonfela (ID: 3720)

Fetching Species:  77%|███████▋  | 10571/13683 [7:15:55<1:55:32,  2.23s/it]

Added new genus: Farfantepenaeus (ID: 3721)

Fetching Species:  77%|███████▋  | 10603/13683 [7:17:06<1:50:11,  2.15s/it]

Added new genus: Wolvfec (ID: 3722)

Fetching Species:  78%|███████▊  | 10607/13683 [7:17:15<2:01:28,  2.37s/it]

Added new genus: 2a (ID: 3723)

Fetching Species:  78%|███████▊  | 10611/13683 [7:17:24<2:03:37,  2.41s/it]

Added new genus: Anguilla (ID: 3724)

Fetching Species:  78%|███████▊  | 10615/13683 [7:17:34<2:02:28,  2.40s/it]

Added new genus: Labidocera (ID: 3725)

Fetching Species:  78%|███████▊  | 10620/13683 [7:17:45<1:53:27,  2.22s/it]

Added new genus: Acartia (ID: 3726)

Fetching Species:  78%|███████▊  | 10631/13683 [7:18:09<1:53:41,  2.24s/it]

Added new genus: Pleurochrysis (ID: 3727)

Fetching Species:  78%|███████▊  | 10634/13683 [7:18:16<1:58:10,  2.33s/it]

Added new genus: Sicyonia (ID: 3728)

Fetching Species:  78%|███████▊  | 10635/13683 [7:18:19<2:00:59,  2.38s/it]

Added new genus: Circovirus-like (ID: 3729)

Fetching Species:  78%|███████▊  | 10637/13683 [7:18:23<1:54:32,  2.26s/it]

Added new genus: Calfel (ID: 3730)

Fetching Species:  78%|███████▊  | 10643/13683 [7:18:36<1:50:07,  2.17s/it]

Added new genus: Circoviridae (ID: 3731)

Fetching Species:  78%|███████▊  | 10645/13683 [7:18:41<1:54:54,  2.27s/it]

Added new genus: Apteryx (ID: 3732)

Fetching Species:  78%|███████▊  | 10647/13683 [7:18:45<1:52:20,  2.22s/it]

Added new genus: Palaemonetes (ID: 3733)

Fetching Species:  78%|███████▊  | 10648/13683 [7:18:48<1:52:11,  2.22s/it]

Added new genus: Ecklonia (ID: 3734)

Fetching Species:  78%|███████▊  | 10652/13683 [7:18:56<1:53:12,  2.24s/it]

Added new genus: Petrochirus (ID: 3735)

Fetching Species:  78%|███████▊  | 10659/13683 [7:19:12<1:52:38,  2.24s/it]

Added new genus: Po-Circo-like (ID: 3736)

Fetching Species:  78%|███████▊  | 10669/13683 [7:19:35<1:54:25,  2.28s/it]

Added new genus: Aiptasia (ID: 3737)

Fetching Species:  78%|███████▊  | 10671/13683 [7:19:39<1:51:04,  2.21s/it]

Added new genus: Garrulus (ID: 3738)

Fetching Species:  78%|███████▊  | 10688/13683 [7:20:18<1:57:09,  2.35s/it]

Added new genus: WigFec (ID: 3739)

Fetching Species:  78%|███████▊  | 10689/13683 [7:20:21<1:54:17,  2.29s/it]

Added new genus: Lytechinus (ID: 3740)

Fetching Species:  78%|███████▊  | 10690/13683 [7:20:23<1:52:00,  2.25s/it]

Added new genus: Meles (ID: 3741)

Fetching Species:  78%|███████▊  | 10694/13683 [7:20:32<1:53:38,  2.28s/it]

Added new genus: Littorina (ID: 3742)

Fetching Species:  78%|███████▊  | 10695/13683 [7:20:34<1:51:38,  2.24s/it]

Added new genus: Paramuricea (ID: 3743)

Fetching Species:  78%|███████▊  | 10709/13683 [7:21:05<1:49:10,  2.20s/it]

Added new genus: Mosquito (ID: 3744)

Fetching Species:  78%|███████▊  | 10711/13683 [7:21:10<1:53:01,  2.28s/it]

Added new genus: Artemia (ID: 3745)

Fetching Species:  78%|███████▊  | 10721/13683 [7:21:32<1:47:46,  2.18s/it]

Added new genus: 15V010 (ID: 3746)

Fetching Species:  78%|███████▊  | 10726/13683 [7:21:43<1:49:26,  2.22s/it]

Added new genus: 2019 (ID: 3747)

Fetching Species:  78%|███████▊  | 10728/13683 [7:21:46<1:44:16,  2.12s/it]

Added new genus: Gammarus (ID: 3748)

Fetching Species:  78%|███████▊  | 10729/13683 [7:21:49<1:46:58,  2.17s/it]

Added new genus: Mytilus (ID: 3749)

Fetching Species:  78%|███████▊  | 10732/13683 [7:21:55<1:46:13,  2.16s/it]

Added new genus: Didemnum (ID: 3750)

Fetching Species:  79%|███████▊  | 10742/13683 [7:22:18<1:50:50,  2.26s/it]

Added new genus: Herugrimvirus (ID: 3751)

Fetching Species:  79%|███████▊  | 10743/13683 [7:22:20<1:49:21,  2.23s/it]

Added new genus: Illuinvirus (ID: 3752)

Fetching Species:  79%|███████▊  | 10745/13683 [7:22:24<1:47:57,  2.20s/it]

Added new genus: Arnorvirus (ID: 3753)

Fetching Species:  79%|███████▊  | 10746/13683 [7:22:27<1:47:20,  2.19s/it]

Added new genus: Grondvirus (ID: 3754)

Fetching Species:  79%|███████▊  | 10750/13683 [7:22:36<1:50:19,  2.26s/it]

Added new genus: Cow (ID: 3755)

Fetching Species:  79%|███████▊  | 10752/13683 [7:22:40<1:47:53,  2.21s/it]

Added new genus: Milk (ID: 3756)

Fetching Species:  79%|███████▊  | 10759/13683 [7:22:55<1:45:09,  2.16s/it]

Added new genus: Parsley (ID: 3757)

Fetching Species:  79%|███████▊  | 10765/13683 [7:23:10<1:59:51,  2.46s/it]

Added new genus: Angainorvirus (ID: 3758)

Fetching Species:  79%|███████▊  | 10766/13683 [7:23:12<1:55:19,  2.37s/it]

Added new genus: Mazarbulvirus (ID: 3759)

Fetching Species:  79%|███████▊  | 10767/13683 [7:23:14<1:54:17,  2.35s/it]

Added new genus: Mithrilvirus (ID: 3760)

Fetching Species:  79%|███████▊  | 10769/13683 [7:23:18<1:49:44,  2.26s/it]

Added new genus: Nauglamirvirus (ID: 3761)

Fetching Species:  79%|███████▊  | 10770/13683 [7:23:20<1:47:53,  2.22s/it]

Added new genus: Menegrothvirus (ID: 3762)

Fetching Species:  79%|███████▊  | 10771/13683 [7:23:23<1:47:04,  2.21s/it]

Added new genus: Phialvirus (ID: 3763)

Fetching Species:  79%|███████▊  | 10772/13683 [7:23:25<1:46:13,  2.19s/it]

Added new genus: Vientovirus (ID: 3764)

Fetching Species:  79%|███████▊  | 10773/13683 [7:23:27<1:45:36,  2.18s/it]

Added new genus: Cressdnaviricota (ID: 3765)

Fetching Species:  79%|███████▉  | 10778/13683 [7:23:38<1:48:47,  2.25s/it]

Added new genus: Pileated (ID: 3766)

Fetching Species:  79%|███████▉  | 10783/13683 [7:23:50<1:51:43,  2.31s/it]

Added new genus: Lupine (ID: 3767)

Fetching Species:  79%|███████▉  | 10816/13683 [7:25:11<2:04:27,  2.60s/it]

Added new genus: Decapod (ID: 3768)

Fetching Species:  79%|███████▉  | 10823/13683 [7:25:27<1:50:54,  2.33s/it]

Added new genus: Danaus (ID: 3769)

Fetching Species:  79%|███████▉  | 10865/13683 [7:27:05<1:47:21,  2.29s/it]

Added new genus: Newlavirus (ID: 3770)

Fetching Species:  79%|███████▉  | 10875/13683 [7:27:28<1:50:07,  2.35s/it]

Added new genus: Parvoviridae (ID: 3771)

Fetching Species:  80%|███████▉  | 10890/13683 [7:28:03<1:46:31,  2.29s/it]

Added new genus: Adeno-associated (ID: 3772)

Fetching Species:  80%|███████▉  | 10899/13683 [7:28:24<1:49:13,  2.35s/it]

Added new genus: Eqcopivirus (ID: 3773)

Fetching Species:  80%|███████▉  | 10900/13683 [7:28:27<1:48:05,  2.33s/it]

Added new genus: Lepidopteran (ID: 3774)

Fetching Species:  80%|███████▉  | 10902/13683 [7:28:31<1:45:50,  2.28s/it]

Added new genus: Hemipteran (ID: 3775)

Fetching Species:  80%|███████▉  | 10934/13683 [7:29:46<1:47:12,  2.34s/it]

Added new genus: Opossum (ID: 3776)

Fetching Species:  80%|███████▉  | 10939/13683 [7:29:57<1:42:15,  2.24s/it]

Added new genus: Parvovirus (ID: 3777)

Fetching Species:  80%|███████▉  | 10941/13683 [7:30:02<1:43:05,  2.26s/it]

Added new genus: Bufavirus-3 (ID: 3778)

Fetching Species:  80%|███████▉  | 10945/13683 [7:30:11<1:42:32,  2.25s/it]

Added new genus: 07 (ID: 3779)

Fetching Species:  80%|████████  | 10948/13683 [7:30:17<1:37:44,  2.14s/it]

Added new genus: California (ID: 3780)

Fetching Species:  80%|████████  | 10949/13683 [7:30:19<1:37:54,  2.15s/it]

Added new genus: Horse (ID: 3781)

Fetching Species:  80%|████████  | 10950/13683 [7:30:21<1:39:45,  2.19s/it]

Added new genus: Sea (ID: 3782)

Fetching Species:  80%|████████  | 10952/13683 [7:30:26<1:42:03,  2.24s/it]

Added new genus: Orthopteran (ID: 3783)

Fetching Species:  80%|████████  | 10954/13683 [7:30:30<1:43:55,  2.28s/it]

Added new genus: Parvovirinae (ID: 3784)

Fetching Species:  80%|████████  | 10955/13683 [7:30:33<1:46:54,  2.35s/it]

Added new genus: Sesavirus (ID: 3785)

Fetching Species:  80%|████████  | 10956/13683 [7:30:35<1:45:53,  2.33s/it]

Added new genus: Bombus (ID: 3786)

Fetching Species:  80%|████████  | 10958/13683 [7:30:40<1:44:51,  2.31s/it]

Added new genus: Desmodus (ID: 3787)

Fetching Species:  80%|████████  | 10960/13683 [7:30:45<1:46:31,  2.35s/it]

Added new genus: Diatraea (ID: 3788)

Fetching Species:  80%|████████  | 10961/13683 [7:30:47<1:45:34,  2.33s/it]

Added new genus: Psittacine (ID: 3789)

Fetching Species:  80%|████████  | 10980/13683 [7:31:32<1:48:35,  2.41s/it]

Added new genus: Macaca (ID: 3790)

Fetching Species:  81%|████████  | 11016/13683 [7:32:56<1:50:44,  2.49s/it]

Added new genus: Serinus (ID: 3791)

Fetching Species:  81%|████████  | 11033/13683 [7:33:36<1:48:18,  2.45s/it]

Added new genus: Boa (ID: 3792)

Fetching Species:  81%|████████  | 11053/13683 [7:34:23<1:41:19,  2.31s/it]

Added new genus: Felis (ID: 3793)

Fetching Species:  81%|████████  | 11055/13683 [7:34:28<1:40:34,  2.30s/it]

Added new genus: Leptonychotes (ID: 3794)

Fetching Species:  81%|████████  | 11089/13683 [7:35:48<1:45:32,  2.44s/it]

Added new genus: Rusa (ID: 3795)

Fetching Species:  81%|████████  | 11107/13683 [7:36:32<1:38:48,  2.30s/it]

Added new genus: Erethizon (ID: 3796)

Fetching Species:  81%|████████  | 11110/13683 [7:36:39<1:42:03,  2.38s/it]

Added new genus: Bos (ID: 3797)

Fetching Species:  81%|████████  | 11112/13683 [7:36:44<1:39:50,  2.33s/it]

Added new genus: Bandicoot (ID: 3798)

Fetching Species:  81%|████████▏ | 11121/13683 [7:37:06<1:40:53,  2.36s/it]

Added new genus: Sus (ID: 3799)

Fetching Species:  82%|████████▏ | 11225/13683 [7:41:13<1:35:12,  2.32s/it]

Added new genus: Pan (ID: 3800)

Fetching Species:  82%|████████▏ | 11236/13683 [7:41:38<1:32:07,  2.26s/it]

Added new genus: Polyomavirus (ID: 3801)

Fetching Species:  82%|████████▏ | 11237/13683 [7:41:40<1:30:47,  2.23s/it]

Added new genus: Marbled (ID: 3802)

Fetching Species:  82%|████████▏ | 11246/13683 [7:42:02<1:40:54,  2.48s/it]

Added new genus: Tadarida (ID: 3803)

Fetching Species:  82%|████████▏ | 11248/13683 [7:42:07<1:38:22,  2.42s/it]

Added new genus: Akodon (ID: 3804)

Fetching Species:  82%|████████▏ | 11249/13683 [7:42:09<1:36:42,  2.38s/it]

Added new genus: Simian (ID: 3805)

Fetching Species:  82%|████████▏ | 11252/13683 [7:42:16<1:35:10,  2.35s/it]

Added new genus: Chaerephon (ID: 3806)

Fetching Species:  82%|████████▏ | 11254/13683 [7:42:21<1:35:40,  2.36s/it]

Added new genus: Myocastor (ID: 3807)

Fetching Species:  82%|████████▏ | 11259/13683 [7:42:33<1:39:11,  2.46s/it]

Added new genus: Pomona (ID: 3808)

Fetching Species:  82%|████████▏ | 11261/13683 [7:42:38<1:37:51,  2.42s/it]

Added new genus: Sheep (ID: 3809)

Fetching Species:  82%|████████▏ | 11268/13683 [7:42:54<1:31:39,  2.28s/it]

Added new genus: Sclerophthora (ID: 3810)

Fetching Species:  82%|████████▏ | 11269/13683 [7:42:57<1:37:46,  2.43s/it]

Added new genus: Beihai (ID: 3811)

Fetching Species:  82%|████████▏ | 11288/13683 [7:43:41<1:34:48,  2.38s/it]

Error fetching Tomato leaf curl betasatellite: Search Backend failed:

Fetching Species:  83%|████████▎ | 11302/13683 [7:44:13<1:31:26,  2.30s/it]

Added new genus: Chili (ID: 3812)

Fetching Species:  83%|████████▎ | 11303/13683 [7:44:15<1:29:37,  2.26s/it]

Added new genus: Zinnia (ID: 3813)

Fetching Species:  83%|████████▎ | 11313/13683 [7:44:42<1:30:21,  2.29s/it]

Error fetching Tomato leaf curl Nepal betasatellite: Search Backend failed:

Fetching Species:  83%|████████▎ | 11321/13683 [7:45:00<1:27:20,  2.22s/it]

Added new genus: Leucas (ID: 3814)

Fetching Species:  83%|████████▎ | 11337/13683 [7:45:48<1:30:45,  2.32s/it]

Added new genus: Codiaeum (ID: 3815)

Fetching Species:  83%|████████▎ | 11339/13683 [7:45:52<1:27:12,  2.23s/it]

Added new genus: Momordica (ID: 3816)

Fetching Species:  83%|████████▎ | 11361/13683 [7:46:48<1:27:52,  2.27s/it]

Added new genus: Anelloviridae (ID: 3817)

Fetching Species:  83%|████████▎ | 11364/13683 [7:46:55<1:27:48,  2.27s/it]

Added new genus: TTV-like (ID: 3818)

Fetching Species:  83%|████████▎ | 11384/13683 [7:47:48<1:27:49,  2.29s/it]

Added new genus: Torque (ID: 3819)

Fetching Species:  84%|████████▎ | 11431/13683 [7:49:36<1:21:38,  2.18s/it]

Added new genus: Tettorquevirus (ID: 3820)

Fetching Species:  84%|████████▎ | 11459/13683 [7:50:41<1:25:44,  2.31s/it]

Added new genus: Small (ID: 3821)

Fetching Species:  84%|████████▍ | 11473/13683 [7:51:12<1:22:28,  2.24s/it]

Added new genus: 2006 (ID: 3822)

Fetching Species:  84%|████████▍ | 11481/13683 [7:51:30<1:23:01,  2.26s/it]

Added new genus: Deltatorquevirus (ID: 3823)

Fetching Species:  84%|████████▍ | 11482/13683 [7:51:32<1:23:38,  2.28s/it]

Added new genus: Omegatorquevirus (ID: 3824)

Fetching Species:  84%|████████▍ | 11483/13683 [7:51:35<1:25:14,  2.32s/it]

Added new genus: Rhotorquevirus (ID: 3825)

Fetching Species:  84%|████████▍ | 11484/13683 [7:51:38<1:32:30,  2.52s/it]

Added new genus: Chitorquevirus (ID: 3826)

Fetching Species:  84%|████████▍ | 11523/13683 [7:53:09<1:23:12,  2.31s/it]

Added new genus: Cacao (ID: 3827)

Fetching Species:  84%|████████▍ | 11529/13683 [7:53:23<1:22:45,  2.31s/it]

Added new genus: Dioscorea (ID: 3828)

Fetching Species:  84%|████████▍ | 11534/13683 [7:53:34<1:20:34,  2.25s/it]

Added new genus: Epiphyllum (ID: 3829)

Fetching Species:  84%|████████▍ | 11537/13683 [7:53:42<1:29:33,  2.50s/it]

Error fetching Badnavirus etavirgamusae: Search Backend failed:

Fetching Species:  85%|████████▍ | 11573/13683 [7:55:04<1:20:48,  2.30s/it]

Added new genus: Chinaberry (ID: 3830)

Fetching Species:  85%|████████▍ | 11605/13683 [7:56:19<1:19:39,  2.30s/it]

Added new genus: Pinus (ID: 3831)

Fetching Species:  85%|████████▍ | 11609/13683 [7:56:29<1:21:29,  2.36s/it]

Added new genus: Water (ID: 3832)

Fetching Species:  85%|████████▍ | 11620/13683 [7:56:54<1:17:17,  2.25s/it]

Added new genus: UR2 (ID: 3833)

Fetching Species:  85%|████████▍ | 11621/13683 [7:56:57<1:16:18,  2.22s/it]

Added new genus: Rous (ID: 3834)

Fetching Species:  85%|████████▍ | 11624/13683 [7:57:04<1:19:12,  2.31s/it]

Added new genus: Fujinami (ID: 3835)

Fetching Species:  85%|████████▍ | 11625/13683 [7:57:06<1:18:56,  2.30s/it]

Added new genus: Y73 (ID: 3836)

Fetching Species:  85%|████████▍ | 11627/13683 [7:57:11<1:18:46,  2.30s/it]

Added new genus: Mason-Pfizer (ID: 3837)

Fetching Species:  85%|████████▍ | 11629/13683 [7:57:15<1:17:16,  2.26s/it]

Added new genus: Mouse (ID: 3838)

Fetching Species:  85%|████████▌ | 11632/13683 [7:57:22<1:18:07,  2.29s/it]

Added new genus: Squirrel (ID: 3839)

Fetching Species:  85%|████████▌ | 11634/13683 [7:57:27<1:22:03,  2.40s/it]

Added new genus: Jaagsiekte (ID: 3840)

Fetching Species:  85%|████████▌ | 11636/13683 [7:57:32<1:25:38,  2.51s/it]

Added new genus: Enzootic (ID: 3841)

Fetching Species:  85%|████████▌ | 11637/13683 [7:57:35<1:23:23,  2.45s/it]

Added new genus: Spleen (ID: 3842)

Fetching Species:  85%|████████▌ | 11638/13683 [7:57:37<1:23:07,  2.44s/it]

Added new genus: Gibbon (ID: 3843)

Fetching Species:  85%|████████▌ | 11639/13683 [7:57:39<1:21:42,  2.40s/it]

Added new genus: Reticuloendotheliosis (ID: 3844)

Fetching Species:  85%|████████▌ | 11640/13683 [7:57:42<1:19:12,  2.33s/it]

Added new genus: RD114 (ID: 3845)

Fetching Species:  85%|████████▌ | 11641/13683 [7:57:44<1:17:32,  2.28s/it]

Added new genus: Woolly (ID: 3846)

Fetching Species:  85%|████████▌ | 11642/13683 [7:57:46<1:17:29,  2.28s/it]

Added new genus: Finkel-Biskis-Jinkins (ID: 3847)

Fetching Species:  85%|████████▌ | 11643/13683 [7:57:48<1:16:08,  2.24s/it]

Added new genus: Moloney (ID: 3848)

Fetching Species:  85%|████████▌ | 11646/13683 [7:57:55<1:18:23,  2.31s/it]

Added new genus: Abelson (ID: 3849)

Fetching Species:  85%|████████▌ | 11647/13683 [7:57:57<1:16:46,  2.26s/it]

Added new genus: Koala (ID: 3850)

Fetching Species:  85%|████████▌ | 11649/13683 [7:58:02<1:16:28,  2.26s/it]

Added new genus: Baboon (ID: 3851)

Fetching Species:  85%|████████▌ | 11651/13683 [7:58:07<1:26:04,  2.54s/it]

Added new genus: Hardy-Zuckerman (ID: 3852)

Fetching Species:  85%|████████▌ | 11652/13683 [7:58:09<1:21:50,  2.42s/it]

Added new genus: Snyder-Theilen (ID: 3853)

Fetching Species:  85%|████████▌ | 11653/13683 [7:58:12<1:20:28,  2.38s/it]

Added new genus: Mus (ID: 3854)

Fetching Species:  85%|████████▌ | 11660/13683 [7:58:28<1:18:52,  2.34s/it]

Added new genus: Snakehead (ID: 3855)

Fetching Species:  85%|████████▌ | 11663/13683 [7:58:35<1:16:22,  2.27s/it]

Added new genus: Puma (ID: 3856)

Fetching Species:  85%|████████▌ | 11667/13683 [7:58:44<1:16:26,  2.28s/it]

Added new genus: Visna-maedi (ID: 3857)

Fetching Species:  85%|████████▌ | 11669/13683 [7:58:49<1:15:56,  2.26s/it]

Added new genus: Caprine (ID: 3858)

Fetching Species:  85%|████████▌ | 11671/13683 [7:58:53<1:14:28,  2.22s/it]

Added new genus: Jembrana (ID: 3859)

Fetching Species:  85%|████████▌ | 11676/13683 [7:59:05<1:17:50,  2.33s/it]

Added new genus: Rhesus (ID: 3860)

Fetching Species:  85%|████████▌ | 11679/13683 [7:59:12<1:18:25,  2.35s/it]

Added new genus: Bornean (ID: 3861)

Fetching Species:  85%|████████▌ | 11680/13683 [7:59:14<1:19:01,  2.37s/it]

Added new genus: White-tufted-ear (ID: 3862)

Fetching Species:  85%|████████▌ | 11681/13683 [7:59:16<1:19:41,  2.39s/it]

Added new genus: Spider (ID: 3863)

Fetching Species:  85%|████████▌ | 11682/13683 [7:59:19<1:18:44,  2.36s/it]

Added new genus: Yellow-breasted (ID: 3864)

Fetching Species:  85%|████████▌ | 11683/13683 [7:59:21<1:17:59,  2.34s/it]

Added new genus: Central (ID: 3865)

Fetching Species:  85%|████████▌ | 11684/13683 [7:59:23<1:09:39,  2.09s/it]

Added new genus: Guenon (ID: 3866)

Fetching Species:  85%|████████▌ | 11686/13683 [7:59:27<1:12:43,  2.19s/it]

Added new genus: Atlantic (ID: 3867)

Fetching Species:  85%|████████▌ | 11693/13683 [7:59:43<1:15:18,  2.27s/it]

Added new genus: Xenopus (ID: 3868)

Fetching Species:  85%|████████▌ | 11696/13683 [7:59:51<1:24:09,  2.54s/it]

Added new genus: Walleye (ID: 3869)

Fetching Species:  86%|████████▌ | 11699/13683 [7:59:58<1:17:51,  2.35s/it]

Added new genus: Trichoplusia (ID: 3870)

Fetching Species:  86%|████████▌ | 11701/13683 [8:00:02<1:16:35,  2.32s/it]

Added new genus: Parrot (ID: 3871)

Fetching Species:  86%|████████▌ | 11703/13683 [8:00:07<1:15:49,  2.30s/it]

Added new genus: Tinamou (ID: 3872)

Fetching Species:  86%|████████▌ | 11704/13683 [8:00:09<1:14:12,  2.25s/it]

Added new genus: Heron (ID: 3873)

Fetching Species:  86%|████████▌ | 11705/13683 [8:00:11<1:13:09,  2.22s/it]

Added new genus: Capuchin (ID: 3874)

Fetching Species:  86%|████████▌ | 11706/13683 [8:00:13<1:12:23,  2.20s/it]

Added new genus: Woodchuck (ID: 3875)

Fetching Species:  86%|████████▌ | 11708/13683 [8:00:17<1:11:40,  2.18s/it]

Added new genus: Roundleaf (ID: 3876)

Fetching Species:  86%|████████▌ | 11710/13683 [8:00:22<1:16:31,  2.33s/it]

Added new genus: Long-fingered (ID: 3877)

Fetching Species:  86%|████████▌ | 11711/13683 [8:00:25<1:17:21,  2.35s/it]

Added new genus: Tent-making (ID: 3878)

Fetching Species:  86%|████████▌ | 11712/13683 [8:00:27<1:16:32,  2.33s/it]

Added new genus: Ground (ID: 3879)

Fetching Species:  86%|████████▌ | 11713/13683 [8:00:29<1:14:45,  2.28s/it]

Added new genus: Domestic (ID: 3880)

Fetching Species:  86%|████████▌ | 11716/13683 [8:00:36<1:12:45,  2.22s/it]

Added new genus: Tibetan (ID: 3881)

Fetching Species:  86%|████████▌ | 11718/13683 [8:00:40<1:13:52,  2.26s/it]

Added new genus: Bluegill (ID: 3882)

Fetching Species:  86%|████████▌ | 11727/13683 [8:01:02<1:16:13,  2.34s/it]

Added new genus: Skunk (ID: 3883)

Fetching Species:  86%|████████▌ | 11730/13683 [8:01:10<1:20:34,  2.48s/it]

Added new genus: Eidolon (ID: 3884)

Fetching Species:  86%|████████▌ | 11748/13683 [8:01:54<1:22:18,  2.55s/it]

Added new genus: Dolphin (ID: 3885)

Fetching Species:  86%|████████▌ | 11754/13683 [8:02:10<1:25:39,  2.66s/it]

Added new genus: Tree (ID: 3886)

Fetching Species:  86%|████████▌ | 11755/13683 [8:02:12<1:26:26,  2.69s/it]

Added new genus: Polar (ID: 3887)

Fetching Species:  86%|████████▌ | 11759/13683 [8:02:22<1:19:22,  2.48s/it]

Added new genus: Deer (ID: 3888)

Fetching Species:  86%|████████▌ | 11765/13683 [8:02:37<1:17:15,  2.42s/it]

Added new genus: Guinea (ID: 3889)

Fetching Species:  86%|████████▌ | 11766/13683 [8:02:40<1:20:12,  2.51s/it]

Added new genus: Platyrrhini (ID: 3890)

Fetching Species:  86%|████████▌ | 11771/13683 [8:02:52<1:17:25,  2.43s/it]

Added new genus: Fowl (ID: 3891)

Fetching Species:  86%|████████▌ | 11783/13683 [8:03:21<1:13:08,  2.31s/it]

Added new genus: Skua (ID: 3892)

Fetching Species:  86%|████████▌ | 11784/13683 [8:03:23<1:12:44,  2.30s/it]

Added new genus: Raptor (ID: 3893)

Fetching Species:  86%|████████▌ | 11788/13683 [8:03:32<1:14:03,  2.35s/it]

Added new genus: Frog (ID: 3894)

Fetching Species:  86%|████████▌ | 11790/13683 [8:03:37<1:12:44,  2.31s/it]

Added new genus: Penguin (ID: 3895)

Fetching Species:  86%|████████▌ | 11791/13683 [8:03:39<1:13:53,  2.34s/it]

Added new genus: Sturgeon (ID: 3896)

Fetching Species:  86%|████████▌ | 11795/13683 [8:03:49<1:14:42,  2.37s/it]

Added new genus: Lizard (ID: 3897)

Fetching Species:  86%|████████▌ | 11800/13683 [8:04:01<1:16:10,  2.43s/it]

Added new genus: Snake (ID: 3898)

Fetching Species:  86%|████████▌ | 11801/13683 [8:04:03<1:13:30,  2.34s/it]

Added new genus: Possum (ID: 3899)

Fetching Species:  86%|████████▋ | 11802/13683 [8:04:06<1:15:16,  2.40s/it]

Added new genus: Pond (ID: 3900)

Fetching Species:  86%|████████▋ | 11825/13683 [8:04:59<1:11:08,  2.30s/it]

Added new genus: Sulfolobus (ID: 3901)

Fetching Species:  86%|████████▋ | 11828/13683 [8:05:07<1:15:59,  2.46s/it]

Added new genus: Yellowstone (ID: 3902)

Fetching Species:  86%|████████▋ | 11831/13683 [8:05:15<1:20:16,  2.60s/it]

Added new genus: Mimivirus-dependent (ID: 3903)

Fetching Species:  86%|████████▋ | 11833/13683 [8:05:20<1:18:39,  2.55s/it]

Added new genus: Cafeteriavirus-dependent (ID: 3904)

Fetching Species:  86%|████████▋ | 11834/13683 [8:05:22<1:17:53,  2.53s/it]

Added new genus: Preplasmiviricota (ID: 3905)

Fetching Species:  87%|████████▋ | 11838/13683 [8:05:32<1:12:31,  2.36s/it]

Added new genus: Swinepox (ID: 3906)

Fetching Species:  87%|████████▋ | 11839/13683 [8:05:34<1:10:39,  2.30s/it]

Added new genus: Penguinpox (ID: 3907)

Fetching Species:  87%|████████▋ | 11840/13683 [8:05:37<1:16:01,  2.47s/it]

Added new genus: Flamingopox (ID: 3908)

Fetching Species:  87%|████████▋ | 11841/13683 [8:05:40<1:19:42,  2.60s/it]

Added new genus: Pigeonpox (ID: 3909)

Fetching Species:  87%|████████▋ | 11842/13683 [8:05:43<1:23:36,  2.72s/it]

Added new genus: Fowlpox (ID: 3910)

Fetching Species:  87%|████████▋ | 11843/13683 [8:05:45<1:23:44,  2.73s/it]

Added new genus: Canarypox (ID: 3911)

Fetching Species:  87%|████████▋ | 11844/13683 [8:05:48<1:23:38,  2.73s/it]

Added new genus: Turkeypox (ID: 3912)

Fetching Species:  87%|████████▋ | 11846/13683 [8:05:53<1:23:38,  2.73s/it]

Added new genus: Variola (ID: 3913)

Fetching Species:  87%|████████▋ | 11847/13683 [8:05:56<1:19:24,  2.59s/it]

Added new genus: Taterapox (ID: 3914)

Fetching Species:  87%|████████▋ | 11848/13683 [8:05:58<1:19:18,  2.59s/it]

Added new genus: Camelpox (ID: 3915)

Fetching Species:  87%|████████▋ | 11850/13683 [8:06:04<1:23:11,  2.72s/it]

Added new genus: Cowpox (ID: 3916)

Fetching Species:  87%|████████▋ | 11852/13683 [8:06:10<1:25:38,  2.81s/it]

Added new genus: Vaccinia (ID: 3917)

Fetching Species:  87%|████████▋ | 11853/13683 [8:06:12<1:19:30,  2.61s/it]

Added new genus: Skunkpox (ID: 3918)

Fetching Species:  87%|████████▋ | 11854/13683 [8:06:15<1:21:56,  2.69s/it]

Added new genus: Volepox (ID: 3919)

Fetching Species:  87%|████████▋ | 11855/13683 [8:06:17<1:22:41,  2.71s/it]

Added new genus: Monkeypox (ID: 3920)

Fetching Species:  87%|████████▋ | 11856/13683 [8:06:20<1:24:07,  2.76s/it]

Added new genus: Ectromelia (ID: 3921)

Fetching Species:  87%|████████▋ | 11857/13683 [8:06:25<1:43:50,  3.41s/it]

Added new genus: Raccoonpox (ID: 3922)

Fetching Species:  87%|████████▋ | 11858/13683 [8:06:28<1:40:41,  3.31s/it]

Added new genus: NY_014 (ID: 3923)

Fetching Species:  87%|████████▋ | 11859/13683 [8:06:30<1:29:59,  2.96s/it]

Added new genus: Yokapox (ID: 3924)

Fetching Species:  87%|████████▋ | 11860/13683 [8:06:33<1:27:45,  2.89s/it]

Added new genus: Murmansk (ID: 3925)

Fetching Species:  87%|████████▋ | 11861/13683 [8:06:36<1:26:21,  2.84s/it]

Added new genus: Sheeppox (ID: 3926)

Fetching Species:  87%|████████▋ | 11862/13683 [8:06:39<1:25:19,  2.81s/it]

Added new genus: Lumpy (ID: 3927)

Fetching Species:  87%|████████▋ | 11863/13683 [8:06:41<1:23:16,  2.75s/it]

Added new genus: Goatpox (ID: 3928)

Fetching Species:  87%|████████▋ | 11865/13683 [8:06:48<1:31:13,  3.01s/it]

Added new genus: Choristoneura (ID: 3929)

Fetching Species:  87%|████████▋ | 11866/13683 [8:06:51<1:31:08,  3.01s/it]

Added new genus: Mythimna (ID: 3930)

Fetching Species:  87%|████████▋ | 11870/13683 [8:07:02<1:25:16,  2.82s/it]

Added new genus: Pteropox (ID: 3931)

Fetching Species:  87%|████████▋ | 11871/13683 [8:07:04<1:24:25,  2.80s/it]

Added new genus: Nile (ID: 3932)

Fetching Species:  87%|████████▋ | 11872/13683 [8:07:07<1:27:01,  2.88s/it]

Added new genus: BeAn (ID: 3933)

Fetching Species:  87%|████████▋ | 11873/13683 [8:07:10<1:25:36,  2.84s/it]

Added new genus: Cotia (ID: 3934)

Fetching Species:  87%|████████▋ | 11874/13683 [8:07:13<1:24:36,  2.81s/it]

Added new genus: unidentified (ID: 3935)

Fetching Species:  87%|████████▋ | 11876/13683 [8:07:17<1:16:08,  2.53s/it]

Added new genus: Grey (ID: 3936)

Fetching Species:  87%|████████▋ | 11878/13683 [8:07:23<1:19:27,  2.64s/it]

Added new genus: Pseudocowpox (ID: 3937)

Fetching Species:  87%|████████▋ | 11879/13683 [8:07:25<1:15:01,  2.50s/it]

Added new genus: Orf (ID: 3938)

Fetching Species:  87%|████████▋ | 11882/13683 [8:07:33<1:20:23,  2.68s/it]

Added new genus: Melanoplus (ID: 3939)

Fetching Species:  87%|████████▋ | 11884/13683 [8:07:39<1:23:55,  2.80s/it]

Added new genus: Squirrelpox (ID: 3940)

Fetching Species:  87%|████████▋ | 11886/13683 [8:07:45<1:22:47,  2.76s/it]

Added new genus: Tanapox (ID: 3941)

Fetching Species:  87%|████████▋ | 11887/13683 [8:07:47<1:21:03,  2.71s/it]

Added new genus: Yaba (ID: 3942)

Fetching Species:  87%|████████▋ | 11889/13683 [8:07:53<1:23:56,  2.81s/it]

Added new genus: Mule (ID: 3943)

Fetching Species:  87%|████████▋ | 11890/13683 [8:07:56<1:23:06,  2.78s/it]

Added new genus: Myxoma (ID: 3944)

Fetching Species:  87%|████████▋ | 11892/13683 [8:08:01<1:20:47,  2.71s/it]

Added new genus: Eptesipox (ID: 3945)

Fetching Species:  87%|████████▋ | 11893/13683 [8:08:04<1:23:37,  2.80s/it]

Added new genus: Molluscum (ID: 3946)

Fetching Species:  87%|████████▋ | 11894/13683 [8:08:06<1:18:32,  2.63s/it]

Added new genus: Linepithema (ID: 3947)

Fetching Species:  87%|████████▋ | 11898/13683 [8:08:16<1:15:56,  2.55s/it]

Added new genus: Ostreococcus (ID: 3948)

Fetching Species:  87%|████████▋ | 11905/13683 [8:08:36<1:21:12,  2.74s/it]

Added new genus: Bathycoccus (ID: 3949)

Fetching Species:  87%|████████▋ | 11911/13683 [8:08:53<1:22:00,  2.78s/it]

Added new genus: Dishui (ID: 3950)

Fetching Species:  87%|████████▋ | 11913/13683 [8:08:59<1:24:03,  2.85s/it]

Added new genus: Emiliania (ID: 3951)

Fetching Species:  87%|████████▋ | 11914/13683 [8:09:01<1:23:12,  2.82s/it]

Added new genus: Feldmannia (ID: 3952)

Fetching Species:  87%|████████▋ | 11915/13683 [8:09:04<1:21:03,  2.75s/it]

Added new genus: Ectocarpus (ID: 3953)

Fetching Species:  87%|████████▋ | 11918/13683 [8:09:13<1:22:44,  2.81s/it]

Added new genus: Paramecium (ID: 3954)

Fetching Species:  87%|████████▋ | 11923/13683 [8:09:26<1:20:12,  2.73s/it]

Added new genus: Only (ID: 3955)

Fetching Species:  87%|████████▋ | 11927/13683 [8:09:38<1:24:05,  2.87s/it]

Added new genus: Orpheovirus (ID: 3956)

Fetching Species:  87%|████████▋ | 11928/13683 [8:09:41<1:27:52,  3.00s/it]

Added new genus: Phaeocystis (ID: 3957)

Fetching Species:  87%|████████▋ | 11929/13683 [8:09:45<1:31:46,  3.14s/it]

Added new genus: Chrysochromulina (ID: 3958)

Fetching Species:  87%|████████▋ | 11931/13683 [8:09:51<1:28:52,  3.04s/it]

Added new genus: Invertebrate (ID: 3959)

Fetching Species:  87%|████████▋ | 11937/13683 [8:10:08<1:21:57,  2.82s/it]

Added new genus: Lymphocystis (ID: 3960)

Fetching Species:  87%|████████▋ | 11945/13683 [8:10:29<1:14:34,  2.57s/it]

Added new genus: Singapore (ID: 3961)

Fetching Species:  87%|████████▋ | 11946/13683 [8:10:32<1:16:01,  2.63s/it]

Added new genus: Short-finned (ID: 3962)

Fetching Species:  87%|████████▋ | 11947/13683 [8:10:34<1:15:34,  2.61s/it]

Added new genus: Santee-Cooper (ID: 3963)

Fetching Species:  87%|████████▋ | 11949/13683 [8:10:41<1:22:46,  2.86s/it]

Added new genus: Scale (ID: 3964)

Fetching Species:  87%|████████▋ | 11950/13683 [8:10:43<1:21:39,  2.83s/it]

Added new genus: Infectious (ID: 3965)

Fetching Species:  87%|████████▋ | 11953/13683 [8:10:51<1:14:29,  2.58s/it]

Added new genus: Cherax (ID: 3966)

Fetching Species:  87%|████████▋ | 11959/13683 [8:11:08<1:20:51,  2.81s/it]

Added new genus: Tunisvirus (ID: 3967)

Fetching Species:  87%|████████▋ | 11960/13683 [8:11:11<1:20:56,  2.82s/it]

Added new genus: Senegalvirus (ID: 3968)

Fetching Species:  87%|████████▋ | 11962/13683 [8:11:16<1:19:06,  2.76s/it]

Added new genus: Brazilian (ID: 3969)

Fetching Species:  87%|████████▋ | 11963/13683 [8:11:19<1:21:58,  2.86s/it]

Added new genus: Noumeavirus (ID: 3970)

Fetching Species:  87%|████████▋ | 11964/13683 [8:11:22<1:22:01,  2.86s/it]

Added new genus: Melbournevirus (ID: 3971)

Fetching Species:  87%|████████▋ | 11966/13683 [8:11:27<1:21:17,  2.84s/it]

Added new genus: Tokyovirus (ID: 3972)

Fetching Species:  87%|████████▋ | 11967/13683 [8:11:31<1:23:38,  2.92s/it]

Added new genus: Lausannevirus (ID: 3973)

Fetching Species:  88%|████████▊ | 11993/13683 [8:12:47<1:04:08,  2.28s/it]

Added new genus: Wenzhou (ID: 3974)

Fetching Species:  88%|████████▊ | 12001/13683 [8:13:06<1:09:17,  2.47s/it]

Added new genus: Acidianus (ID: 3975)

Fetching Species:  88%|████████▊ | 12010/13683 [8:13:28<1:02:53,  2.26s/it]

Added new genus: Chlamydia (ID: 3976)

Fetching Species:  88%|████████▊ | 12012/13683 [8:13:32<1:02:29,  2.24s/it]

Added new genus: Microviridae (ID: 3977)

Fetching Species:  88%|████████▊ | 12033/13683 [8:14:21<1:05:34,  2.38s/it]

Added new genus: Gokushovirinae (ID: 3978)

Fetching Species:  88%|████████▊ | 12038/13683 [8:14:32<1:04:50,  2.37s/it]

Added new genus: Parabacteroides (ID: 3979)

Fetching Species:  88%|████████▊ | 12046/13683 [8:14:51<1:02:03,  2.27s/it]

Added new genus: Eel (ID: 3980)

Fetching Species:  88%|████████▊ | 12047/13683 [8:14:53<1:02:08,  2.28s/it]

Added new genus: Lynx (ID: 3981)

Fetching Species:  88%|████████▊ | 12068/13683 [8:15:43<1:05:52,  2.45s/it]

Added new genus: Spodoptera (ID: 3982)

Fetching Species:  88%|████████▊ | 12070/13683 [8:15:49<1:14:02,  2.75s/it]

Added new genus: Euproctis (ID: 3983)

Fetching Species:  88%|████████▊ | 12093/13683 [8:16:52<1:14:00,  2.79s/it]

Added new genus: Anticarsia (ID: 3984)

Fetching Species:  88%|████████▊ | 12094/13683 [8:16:55<1:13:31,  2.78s/it]

Added new genus: Malacosoma (ID: 3985)

Fetching Species:  88%|████████▊ | 12098/13683 [8:17:06<1:13:00,  2.76s/it]

Added new genus: Adoxophyes (ID: 3986)

Fetching Species:  88%|████████▊ | 12099/13683 [8:17:09<1:14:31,  2.82s/it]

Added new genus: Peridroma (ID: 3987)

Fetching Species:  89%|████████▊ | 12127/13683 [8:18:27<1:14:29,  2.87s/it]

Added new genus: Apocheima (ID: 3988)

Fetching Species:  89%|████████▉ | 12187/13683 [8:21:06<52:42,  2.11s/it]

Added new genus: Ash (ID: 3989)

Fetching Species:  89%|████████▉ | 12193/13683 [8:21:20<53:33,  2.16s/it]

Added new genus: Whitefly (ID: 3990)

Fetching Species:  89%|████████▉ | 12194/13683 [8:21:22<53:29,  2.16s/it]

Added new genus: Nanovirus-like (ID: 3991)

Fetching Species:  89%|████████▉ | 12203/13683 [8:21:42<53:39,  2.18s/it]

Added new genus: Sunflower (ID: 3992)

Fetching Species:  89%|████████▉ | 12219/13683 [8:22:17<51:40,  2.12s/it]

Added new genus: Coconut (ID: 3993)

Fetching Species:  89%|████████▉ | 12223/13683 [8:22:26<53:52,  2.21s/it]

Added new genus: Bhindi (ID: 3994)

Fetching Species:  89%|████████▉ | 12228/13683 [8:22:38<55:28,  2.29s/it]

Added new genus: Parthenium (ID: 3995)

Fetching Species:  89%|████████▉ | 12234/13683 [8:22:51<55:00,  2.28s/it]

Added new genus: Verbesina (ID: 3996)

Fetching Species:  89%|████████▉ | 12237/13683 [8:22:58<53:54,  2.24s/it]

Added new genus: Guar (ID: 3997)

Fetching Species:  90%|████████▉ | 12254/13683 [8:23:37<55:08,  2.32s/it]

Added new genus: Sulfolobales (ID: 3998)

Fetching Species:  90%|████████▉ | 12258/13683 [8:23:46<55:23,  2.33s/it]

Added new genus: Changjiang (ID: 3999)

Fetching Species:  90%|████████▉ | 12259/13683 [8:23:48<55:02,  2.32s/it]

Added new genus: Fly (ID: 4000)

Fetching Species:  90%|████████▉ | 12263/13683 [8:23:58<55:32,  2.35s/it]

Added new genus: Penicillum (ID: 4001)

Fetching Species:  90%|████████▉ | 12267/13683 [8:24:06<52:42,  2.23s/it]

Added new genus: Botryoshaeria (ID: 4002)

Fetching Species:  90%|████████▉ | 12285/13683 [8:24:48<57:17,  2.46s/it]

Added new genus: Fobrovirus (ID: 4003)

Fetching Species:  90%|████████▉ | 12304/13683 [8:25:34<54:03,  2.35s/it]

Added new genus: Uncultured (ID: 4004)

Fetching Species:  90%|█████████ | 12333/13683 [8:26:43<51:57,  2.31s/it]

Added new genus: Shahe (ID: 4005)

Fetching Species:  90%|█████████ | 12335/13683 [8:26:48<52:28,  2.34s/it]

Added new genus: Diaporthe (ID: 4006)

Fetching Species:  90%|█████████ | 12337/13683 [8:26:52<52:05,  2.32s/it]

Added new genus: Halastavi (ID: 4007)

Fetching Species:  90%|█████████ | 12343/13683 [8:27:06<51:11,  2.29s/it]

Added new genus: Anopheline-associated (ID: 4008)

Fetching Species:  90%|█████████ | 12345/13683 [8:27:11<51:07,  2.29s/it]

Added new genus: Hepatitis (ID: 4009)

Fetching Species:  90%|█████████ | 12346/13683 [8:27:13<50:43,  2.28s/it]

Added new genus: Termite (ID: 4010)

Fetching Species:  90%|█████████ | 12351/13683 [8:27:24<49:45,  2.24s/it]

Added new genus: Fish (ID: 4011)

Fetching Species:  90%|█████████ | 12353/13683 [8:27:28<48:56,  2.21s/it]

Added new genus: Daletvirus (ID: 4012)

Fetching Species:  90%|█████████ | 12354/13683 [8:27:30<48:32,  2.19s/it]

Added new genus: Daazvirus (ID: 4013)

Fetching Species:  90%|█████████ | 12355/13683 [8:27:33<48:17,  2.18s/it]

Added new genus: Dobrovirus (ID: 4014)

Fetching Species:  90%|█████████ | 12369/13683 [8:28:06<53:11,  2.43s/it]

Added new genus: Xingshan (ID: 4015)

Fetching Species:  90%|█████████ | 12372/13683 [8:28:12<50:36,  2.32s/it]

Added new genus: Osedax (ID: 4016)

Fetching Species:  90%|█████████ | 12380/13683 [8:28:31<50:30,  2.33s/it]

Added new genus: Changping (ID: 4017)

Fetching Species:  90%|█████████ | 12382/13683 [8:28:36<51:59,  2.40s/it]

Added new genus: Sierra (ID: 4018)

Fetching Species:  91%|█████████ | 12387/13683 [8:28:47<48:06,  2.23s/it]

Added new genus: Halhan (ID: 4019)

Fetching Species:  91%|█████████ | 12389/13683 [8:28:51<48:19,  2.24s/it]

Added new genus: Symphysodon (ID: 4020)

Fetching Species:  91%|█████████ | 12392/13683 [8:28:58<47:59,  2.23s/it]

Added new genus: Wallerfield (ID: 4021)

Fetching Species:  91%|█████████ | 12393/13683 [8:29:00<48:46,  2.27s/it]

Added new genus: Andrena (ID: 4022)

Fetching Species:  91%|█████████ | 12394/13683 [8:29:02<48:52,  2.27s/it]

Added new genus: Piura (ID: 4023)

Fetching Species:  91%|█████████ | 12395/13683 [8:29:05<50:50,  2.37s/it]

Added new genus: Ying (ID: 4024)

Fetching Species:  91%|█████████ | 12396/13683 [8:29:07<50:21,  2.35s/it]

Added new genus: Brejeira (ID: 4025)

Fetching Species:  91%|█████████ | 12397/13683 [8:29:10<49:58,  2.33s/it]

Added new genus: Loreto (ID: 4026)

Fetching Species:  91%|█████████ | 12398/13683 [8:29:12<49:37,  2.32s/it]

Added new genus: Negev (ID: 4027)

Fetching Species:  91%|█████████ | 12399/13683 [8:29:14<50:12,  2.35s/it]

Added new genus: Castlerea (ID: 4028)

Fetching Species:  91%|█████████ | 12400/13683 [8:29:17<49:51,  2.33s/it]

Added new genus: Trifolium-associated (ID: 4029)

Fetching Species:  91%|█████████ | 12413/13683 [8:29:46<47:47,  2.26s/it]

Added new genus: Zhejiang (ID: 4030)

Fetching Species:  91%|█████████ | 12479/13683 [8:32:27<45:28,  2.27s/it]

Added new genus: Wilkie (ID: 4031)

Fetching Species:  91%|█████████ | 12481/13683 [8:32:32<46:16,  2.31s/it]

Added new genus: False (ID: 4032)

Fetching Species:  91%|█████████ | 12484/13683 [8:32:39<46:16,  2.32s/it]

Added new genus: Arhar (ID: 4033)

Fetching Species:  91%|█████████▏| 12488/13683 [8:32:48<44:48,  2.25s/it]

Added new genus: Stipagrostis (ID: 4034)

Fetching Species:  91%|█████████▏| 12490/13683 [8:32:52<45:25,  2.28s/it]

Added new genus: Odonata-associated (ID: 4035)

Fetching Species:  91%|█████████▏| 12492/13683 [8:32:56<43:58,  2.22s/it]

Added new genus: Mizyes (ID: 4036)

Fetching Species:  91%|█████████▏| 12495/13683 [8:33:04<47:08,  2.38s/it]

Added new genus: Circular (ID: 4037)

Fetching Species:  91%|█████████▏| 12498/13683 [8:33:10<45:32,  2.31s/it]

Added new genus: Pacmanvirus (ID: 4038)

Fetching Species:  91%|█████████▏| 12499/13683 [8:33:13<49:01,  2.48s/it]

Added new genus: Pyrococcus (ID: 4039)

Fetching Species:  91%|█████████▏| 12503/13683 [8:33:23<46:49,  2.38s/it]

Added new genus: Arctopus (ID: 4040)

Fetching Species:  92%|█████████▏| 12522/13683 [8:34:06<44:28,  2.30s/it]

Added new genus: Chimeric (ID: 4041)

Fetching Species:  92%|█████████▏| 12526/13683 [8:34:15<44:30,  2.31s/it]

Added new genus: Cyanoramphus (ID: 4042)

Fetching Species:  92%|█████████▏| 12528/13683 [8:34:20<43:26,  2.26s/it]

Added new genus: Shayang (ID: 4043)

Fetching Species:  92%|█████████▏| 12536/13683 [8:34:40<47:20,  2.48s/it]

Added new genus: Diabrotica (ID: 4044)

Fetching Species:  92%|█████████▏| 12543/13683 [8:34:56<45:22,  2.39s/it]

Added new genus: Kaumoebavirus (ID: 4045)

Fetching Species:  92%|█████████▏| 12582/13683 [8:36:36<41:59,  2.29s/it]

Added new genus: Basavirus (ID: 4046)

Fetching Species:  92%|█████████▏| 12583/13683 [8:36:38<41:56,  2.29s/it]

Added new genus: Boiling (ID: 4047)

Fetching Species:  92%|█████████▏| 12587/13683 [8:36:48<43:01,  2.36s/it]

Added new genus: Wuchang (ID: 4048)

Fetching Species:  92%|█████████▏| 12616/13683 [8:37:58<41:19,  2.32s/it]

Added new genus: Acheta (ID: 4049)

Fetching Species:  92%|█████████▏| 12618/13683 [8:38:02<40:46,  2.30s/it]

Added new genus: Aeropyrum (ID: 4050)

Fetching Species:  92%|█████████▏| 12629/13683 [8:38:29<40:40,  2.32s/it]

Added new genus: Point-Douro (ID: 4051)

Fetching Species:  92%|█████████▏| 12638/13683 [8:38:50<41:16,  2.37s/it]

Added new genus: Rasavirus (ID: 4052)

Fetching Species:  92%|█████████▏| 12649/13683 [8:39:15<39:07,  2.27s/it]

Added new genus: Bole (ID: 4053)

Fetching Species:  92%|█████████▏| 12655/13683 [8:39:29<38:26,  2.24s/it]

Added new genus: Hudisavirus (ID: 4054)

Fetching Species:  93%|█████████▎| 12667/13683 [8:39:56<39:02,  2.31s/it]

Added new genus: Bromus-associated (ID: 4055)

Fetching Species:  93%|█████████▎| 12668/13683 [8:39:59<38:55,  2.30s/it]

Added new genus: McMurdo (ID: 4056)

Fetching Species:  93%|█████████▎| 12700/13683 [8:41:14<38:01,  2.32s/it]

Added new genus: Rudphi (ID: 4057)

Fetching Species:  93%|█████████▎| 12713/13683 [8:41:43<36:28,  2.26s/it]

Added new genus: Tentweb (ID: 4058)

Fetching Species:  93%|█████████▎| 12724/13683 [8:42:09<37:13,  2.33s/it]

Added new genus: Hyperthermophilic (ID: 4059)

Fetching Species:  93%|█████████▎| 12726/13683 [8:42:13<37:07,  2.33s/it]

Added new genus: Diaphorina (ID: 4060)

Fetching Species:  93%|█████████▎| 12727/13683 [8:42:16<37:36,  2.36s/it]

Added new genus: Bradson (ID: 4061)

Fetching Species:  93%|█████████▎| 12744/13683 [8:42:55<35:41,  2.28s/it]

Added new genus: Diplodia (ID: 4062)

Fetching Species:  93%|█████████▎| 12777/13683 [8:44:10<34:33,  2.29s/it]

Added new genus: Hydrogenobaculum (ID: 4063)

Fetching Species:  93%|█████████▎| 12778/13683 [8:44:13<35:58,  2.38s/it]

Added new genus: Phormidium (ID: 4064)

Fetching Species:  93%|█████████▎| 12786/13683 [8:44:31<34:40,  2.32s/it]

Added new genus: Metallosphaera (ID: 4065)

Fetching Species:  94%|█████████▎| 12803/13683 [8:45:12<34:37,  2.36s/it]

Added new genus: Cordoba (ID: 4066)

Fetching Species:  94%|█████████▎| 12806/13683 [8:45:19<34:38,  2.37s/it]

Added new genus: Jingmen (ID: 4067)

Fetching Species:  94%|█████████▎| 12811/13683 [8:45:31<33:52,  2.33s/it]

Added new genus: Chronic (ID: 4068)

Fetching Species:  94%|█████████▎| 12826/13683 [8:46:05<32:48,  2.30s/it]

Added new genus: Oyster (ID: 4069)

Fetching Species:  94%|█████████▍| 12832/13683 [8:46:19<33:53,  2.39s/it]

Added new genus: Holcus (ID: 4070)

Fetching Species:  94%|█████████▍| 12845/13683 [8:46:48<31:55,  2.29s/it]

Added new genus: Arceuthobium (ID: 4071)

Fetching Species:  94%|█████████▍| 12863/13683 [8:47:30<31:47,  2.33s/it]

Added new genus: Circulifer (ID: 4072)

Fetching Species:  94%|█████████▍| 12866/13683 [8:47:37<31:17,  2.30s/it]

Added new genus: Gastropod (ID: 4073)

Fetching Species:  94%|█████████▍| 12869/13683 [8:47:44<30:26,  2.24s/it]

Added new genus: Tanay (ID: 4074)

Fetching Species:  94%|█████████▍| 12881/13683 [8:48:11<31:33,  2.36s/it]

Added new genus: Wabat (ID: 4075)

Fetching Species:  94%|█████████▍| 12882/13683 [8:48:14<31:17,  2.34s/it]

Added new genus: Gopherus (ID: 4076)

Fetching Species:  94%|█████████▍| 12884/13683 [8:48:18<30:24,  2.28s/it]

Added new genus: Longjawed (ID: 4077)

Fetching Species:  94%|█████████▍| 12890/13683 [8:48:32<30:07,  2.28s/it]

Added new genus: Acanthamoeba (ID: 4078)

Fetching Species:  94%|█████████▍| 12891/13683 [8:48:35<32:34,  2.47s/it]

Added new genus: Rhynchobatus (ID: 4079)

Fetching Species:  94%|█████████▍| 12897/13683 [8:48:49<31:06,  2.37s/it]

Added new genus: Burke-Gilman (ID: 4080)

Fetching Species:  94%|█████████▍| 12918/13683 [8:49:37<29:34,  2.32s/it]

Added new genus: Pimoid (ID: 4081)

Fetching Species:  95%|█████████▍| 12950/13683 [8:50:52<28:09,  2.31s/it]

Added new genus: Nepavirus (ID: 4082)

Fetching Species:  95%|█████████▍| 12969/13683 [8:51:36<26:20,  2.21s/it]

Added new genus: Corey (ID: 4083)

Fetching Species:  95%|█████████▍| 12982/13683 [8:52:07<28:59,  2.48s/it]

Added new genus: Ubei (ID: 4084)

Fetching Species:  95%|█████████▍| 12984/13683 [8:52:11<27:46,  2.38s/it]

Added new genus: Circo-like (ID: 4085)

Fetching Species:  95%|█████████▌| 13019/13683 [8:53:32<25:29,  2.30s/it]

Added new genus: Ctenophore-associated (ID: 4086)

Fetching Species:  95%|█████████▌| 13042/13683 [8:54:24<23:54,  2.24s/it]

Added new genus: Mycoplasma (ID: 4087)

Fetching Species:  95%|█████████▌| 13054/13683 [8:54:51<23:46,  2.27s/it]

Added new genus: Pansavirus (ID: 4088)

Fetching Species:  95%|█████████▌| 13056/13683 [8:54:55<23:44,  2.27s/it]

Added new genus: Swagivirus (ID: 4089)

Fetching Species:  96%|█████████▌| 13085/13683 [8:56:02<22:59,  2.31s/it]

Added new genus: Cryphonectria (ID: 4090)

Fetching Species:  96%|█████████▌| 13097/13683 [8:56:30<23:01,  2.36s/it]

Added new genus: Chamois (ID: 4091)

Fetching Species:  96%|█████████▌| 13131/13683 [8:57:50<20:33,  2.23s/it]

Added new genus: Kelp (ID: 4092)

Fetching Species:  96%|█████████▌| 13145/13683 [8:58:22<21:05,  2.35s/it]

Added new genus: Acyrthosiphon (ID: 4093)

Fetching Species:  96%|█████████▋| 13170/13683 [8:59:20<20:20,  2.38s/it]

Added new genus: Cybaeus (ID: 4094)

Fetching Species:  96%|█████████▋| 13176/13683 [8:59:35<20:24,  2.42s/it]

Added new genus: Gamboa (ID: 4095)

Fetching Species:  96%|█████████▋| 13184/13683 [8:59:54<20:22,  2.45s/it]

Added new genus: Thermococcus (ID: 4096)

Fetching Species:  96%|█████████▋| 13204/13683 [9:00:38<17:35,  2.20s/it]

Added new genus: Varidnaviria (ID: 4097)

Fetching Species:  97%|█████████▋| 13207/13683 [9:00:45<17:57,  2.26s/it]

Added new genus: Yado-nushi (ID: 4098)

Fetching Species:  97%|█████████▋| 13212/13683 [9:00:57<18:11,  2.32s/it]

Added new genus: Wuchan (ID: 4099)

Fetching Species:  97%|█████████▋| 13245/13683 [9:02:12<16:18,  2.23s/it]

Added new genus: Millipede (ID: 4100)

Fetching Species:  97%|█████████▋| 13250/13683 [9:02:24<16:12,  2.25s/it]

Added new genus: Cedratvirus (ID: 4101)

Fetching Species:  97%|█████████▋| 13255/13683 [9:02:36<16:31,  2.32s/it]

Added new genus: Cragig (ID: 4102)

Fetching Species:  97%|█████████▋| 13272/13683 [9:03:16<16:11,  2.36s/it]

Added new genus: Salisaeta (ID: 4103)

Fetching Species:  97%|█████████▋| 13278/13683 [9:03:30<15:42,  2.33s/it]

Added new genus: Llama (ID: 4104)

Fetching Species:  97%|█████████▋| 13290/13683 [9:04:09<29:48,  4.55s/it]

Added new genus: Lodeiro (ID: 4105)

Fetching Species:  97%|█████████▋| 13324/13683 [9:05:28<14:26,  2.41s/it]

Added new genus: Spinybacked (ID: 4106)

Fetching Species:  97%|█████████▋| 13327/13683 [9:05:35<13:21,  2.25s/it]

Added new genus: Daeseongdong (ID: 4107)

Fetching Species:  97%|█████████▋| 13339/13683 [9:06:03<13:13,  2.31s/it]

Added new genus: Picalivirus (ID: 4108)

Fetching Species:  98%|█████████▊| 13363/13683 [9:06:59<12:00,  2.25s/it]

Added new genus: Fisavirus (ID: 4109)

Fetching Species:  98%|█████████▊| 13403/13683 [9:08:33<10:42,  2.29s/it]

Added new genus: Torulaspora (ID: 4110)

Fetching Species:  98%|█████████▊| 13407/13683 [9:08:42<10:20,  2.25s/it]

Added new genus: Woodlouse (ID: 4111)

Fetching Species:  98%|█████████▊| 13418/13683 [9:09:07<10:28,  2.37s/it]

Added new genus: Shinobi (ID: 4112)

Fetching Species:  98%|█████████▊| 13472/13683 [9:11:11<07:56,  2.26s/it]

Added new genus: Fire (ID: 4113)

Fetching Species:  99%|█████████▊| 13481/13683 [9:11:31<07:27,  2.21s/it]

Added new genus: narna-like (ID: 4114)

Fetching Species:  99%|█████████▊| 13491/13683 [9:11:54<07:36,  2.38s/it]

Added new genus: Goutanap (ID: 4115)

Fetching Species:  99%|█████████▊| 13503/13683 [9:12:22<06:59,  2.33s/it]

Added new genus: Elicom (ID: 4116)

Fetching Species:  99%|█████████▉| 13514/13683 [9:12:46<06:13,  2.21s/it]

Added new genus: Mollivirus (ID: 4117)

Fetching Species:  99%|█████████▉| 13521/13683 [9:13:04<06:24,  2.37s/it]

Added new genus: Adelphocoris (ID: 4118)

Fetching Species:  99%|█████████▉| 13536/13683 [9:13:39<05:50,  2.39s/it]

Added new genus: Thika (ID: 4119)

Fetching Species:  99%|█████████▉| 13556/13683 [9:14:27<05:22,  2.54s/it]

Added new genus: Biratnagar (ID: 4120)

Fetching Species:  99%|█████████▉| 13562/13683 [9:14:41<04:44,  2.35s/it]

Added new genus: Ancient (ID: 4121)

Fetching Species: 100%|█████████▉| 13616/13683 [9:16:47<02:36,  2.34s/it]

Added new genus: Planaria (ID: 4122)

Fetching Species: 100%|█████████▉| 13621/13683 [9:16:58<02:25,  2.35s/it]

Added new genus: Duwamo (ID: 4123)

Fetching Species: 100%|█████████▉| 13629/13683 [9:17:18<02:12,  2.45s/it]

Added new genus: Abisko (ID: 4124)

Fetching Species: 100%|█████████▉| 13634/13683 [9:17:29<01:54,  2.34s/it]

Added new genus: Leshenault (ID: 4125)

Fetching Species: 100%|█████████▉| 13650/13683 [9:18:07<01:16,  2.32s/it]

Added new genus: Egaro (ID: 4126)

Fetching Species: 100%|██████████| 13683/13683 [9:19:21<00:00,  2.45s/it]

Processing Complete!
Updated Genus Table:
                  genus    id
0      Alphafusarivirus     1
1       Betafusarivirus     2
2      Gammafusarivirus     3
3      Betapartitivirus     4
4     Gammapartitivirus     5
...                 ...   ...
4121           Planaria  4122
4122             Duwamo  4123
4123             Abisko  4124
4124         Leshenault  4125
4125              Egaro  4126

[4126 rows x 2 columns]

Final Sequence Table:
                                            sequence  species_id  genus_id
0  CCGGGGTGTTAAAGATAACGTTAATATGTGTTATCCAGTATGTCAT...           1         1
1  CCGGGGTGTTAAAGATAACGTTAATATGTGTTATCCAGTATGTCAT...           1         1
2  AATCCCAATCGCACCCACCCAGCACCGCTCTGAGTGCTATTAAGAA...           2         1
3  AATCCCAATCGCACCCACCCAGCACCGCTCTGAGTGCTATTAAGAA...           2         1
4  CTCACATAGAGAACCACGGGCTTCTTTCTTTTGCCCTTTTTCCACT...           3         1

In [5]:
genus_labels.to_csv("raw_database/genus_new_labels.csv")
final_df.to_csv("raw_database/final.csv")

In [6]:
df_labels_genus = pd.read_csv("raw_database/genus_new_labels.csv")
final_df = pd.read_csv("raw_database/final.csv")

In [7]:
df_labels_genus.columns

Index(['Unnamed: 0', 'genus', 'id'], dtype='object')

In [8]:
final_df.columns

Index(['Unnamed: 0', 'sequence', 'species_id', 'genus_id'], dtype='object')

In [ ]:
import pandas as pd
from Bio import Entrez, SeqIO
from tqdm import tqdm
import time

# 2. CONFIGURATION
Entrez.email = "matheuslimaaa13@gmail.com"  # <--- REPLACE THIS

def get_ncbi_taxonomy_genus(species_name):
    """
    Fetches the taxonomic lineage. 
    Priority 1: Find a node with Rank='genus'.
    Priority 2 (Viruses): If no genus, take the immediate parent (last item in lineage).
    """
    try:
        # Search for the species ID
        # Using [All Fields] helps find names that might be synonyms or isolates
        search_handle = Entrez.esearch(db="taxonomy", term=f"{species_name}", retmode="xml")
        search_results = Entrez.read(search_handle)
        search_handle.close()
        
        if not search_results['IdList']:
            return None, "Search Failed"
            
        # Use the first ID found
        tax_id = search_results['IdList'][0]
        
        # Fetch taxonomy details
        fetch_handle = Entrez.efetch(db="taxonomy", id=tax_id, retmode="xml")
        data = Entrez.read(fetch_handle)
        fetch_handle.close()
        
        if not data:
            return None, "No Data"

        record = data[0]
        lineage = record.get('LineageEx', [])
        
        # 1. Try to find explicit Genus rank
        for tax_node in lineage:
            if tax_node['Rank'] == 'genus':
                return tax_node['ScientificName'], "Found Genus"
        
        # 2. Fallback: If it's a Virus and no Genus found, take the immediate parent
        # Check if 'Viruses' is in the lineage to confirm it's viral
        is_virus = any(node['ScientificName'] == 'Viruses' for node in lineage)
        
        if is_virus and lineage:
            # The last item in LineageEx is the direct parent
            parent_name = lineage[-1]['ScientificName']
            return parent_name, f"Fallback to Parent ({lineage[-1]['Rank']})"
            
        return None, "No Genus or Parent found"

    except Exception as e:
        return None, f"Error: {str(e)}"

# 3. PROCESSING
unique_species_ids = final_df['species_id'].unique()
print(f"Processing {len(unique_species_ids)} unique species...")

for sp_id in tqdm(unique_species_ids, desc="Repairing Lineage"):
    
    # Get the Species Name
    sp_row = species_labels[species_labels['id'] == sp_id]
    if sp_row.empty:
        continue
    species_name = sp_row.iloc[0]['species']
    
    # Get True Genus from NCBI
    true_genus_name, status = get_ncbi_taxonomy_genus(species_name)
    
    if not true_genus_name:
        # If it fails, we keep the original (or you can mark it 'Unknown')
        # tqdm.write(f"FAILED: {species_name} -> {status}")
        continue
    
    # Update/Find Genus in df_labels_genus
    genus_match = df_labels_genus[df_labels_genus['genus'] == true_genus_name]
    
    if genus_match.empty:
        # Create new ID
        new_id = df_labels_genus['id'].max() + 1 if not df_labels_genus.empty else 1
        new_row = pd.DataFrame([{'genus': true_genus_name, 'id': new_id}])
        df_labels_genus = pd.concat([df_labels_genus, new_row], ignore_index=True)
        correct_genus_id = new_id
    else:
        correct_genus_id = genus_match.iloc[0]['id']
        
    # Fix final_df
    final_df.loc[final_df['species_id'] == sp_id, 'genus_id'] = correct_genus_id
    
    # Optional: Print updates for the previously failing ones to verify
    if "Fallback" in status:
        tqdm.write(f"Fixed: {species_name} -> {true_genus_name} ({status})")
    
    time.sleep(0.5) # Rate limit

# 4. CLEANUP (Remove unused genus labels)
print("\nCleaning up unused Genus labels...")
valid_genus_ids = final_df['genus_id'].unique()
df_labels_genus = df_labels_genus[df_labels_genus['id'].isin(valid_genus_ids)].copy()
df_labels_genus.reset_index(drop=True, inplace=True)

# 5. SAVE OR VIEW
print("Repair Complete.")
print(df_labels_genus.head())
print(final_df.head())

Processing 13592 unique species...

Repairing Lineage:   0%|          | 34/13592 [00:57<5:57:52,  1.58s/it]

Fixed: Nigrospora oryzae fusarivirus 1 -> unclassified Fusariviridae (Fallback to Parent (no rank))

Repairing Lineage:   0%|          | 35/13592 [00:59<6:26:46,  1.71s/it]

Fixed: Sodiomyces alkalinus fusarivirus 1 -> unclassified Fusariviridae (Fallback to Parent (no rank))

Repairing Lineage:   0%|          | 54/13592 [01:29<5:57:34,  1.58s/it]

Fixed: Verticillium dahliae partitivirus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   0%|          | 55/13592 [01:31<6:43:13,  1.79s/it]

Fixed: Spinach cryptic virus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   0%|          | 56/13592 [01:32<6:23:38,  1.70s/it]

Fixed: Rhizoctonia solani dsRNA virus 2 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   0%|          | 57/13592 [01:34<6:12:06,  1.65s/it]

Fixed: Dill cryptic virus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 88/13592 [02:24<5:59:19,  1.60s/it]

Fixed: Pseudogymnoascus destructans partitivirus-pa -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 89/13592 [02:26<6:25:48,  1.71s/it]

Fixed: Fragaria chiloensis cryptic virus -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 90/13592 [02:27<6:13:23,  1.66s/it]

Fixed: Raphanus sativus cryptic virus 3 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 91/13592 [02:29<6:04:37,  1.62s/it]

Fixed: Sclerotinia sclerotiorum partitivirus S -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 92/13592 [02:30<6:08:05,  1.64s/it]

Fixed: Botryotinia fuckeliana partitivirus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 93/13592 [02:32<6:00:12,  1.60s/it]

Fixed: Bipolaris maydis partitivirus 2 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 94/13592 [02:34<5:57:29,  1.59s/it]

Fixed: Penicillium aurantiogriseum partitivirus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 95/13592 [02:35<5:58:42,  1.59s/it]

Fixed: Ustilaginoidea virens partitivirus 2 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 96/13592 [02:37<5:58:09,  1.59s/it]

Fixed: Sophora japonica powdery mildew-associated partitivirus -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 97/13592 [02:38<5:51:14,  1.56s/it]

Fixed: Sinapis alba cryptic virus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 98/13592 [02:40<5:45:25,  1.54s/it]

Fixed: Raphanus sativus cryptic virus 2 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 99/13592 [02:41<5:43:11,  1.53s/it]

Fixed: Raphanus sativus cryptic virus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 100/13592 [02:43<5:45:23,  1.54s/it]

Fixed: Red clover cryptic virus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 101/13592 [02:45<6:06:54,  1.63s/it]

Fixed: Rose cryptic virus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 102/13592 [02:46<5:59:07,  1.60s/it]

Fixed: Aspergillus fumigatus partitivirus 2 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 103/13592 [02:48<5:56:20,  1.59s/it]

Fixed: Melon partitivirus -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 104/13592 [02:51<5:55:19,  1.58s/it]

Fixed: Persimmon cryptic virus -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 105/13592 [02:53<8:21:34,  2.23s/it]

Fixed: Carnation cryptic virus 3 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 106/13592 [02:55<7:45:27,  2.07s/it]

Fixed: Bipolaris maydis partitivirus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 107/13592 [02:57<7:14:32,  1.93s/it]

Fixed: Fusarium poae partitivirus 2 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 108/13592 [02:59<7:43:49,  2.06s/it]

Fixed: Rosellinia necatrix partitivirus 8 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 109/13592 [03:00<7:07:33,  1.90s/it]

Fixed: Rhizoctonia solani dsRNA virus 4 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 111/13592 [03:03<6:26:16,  1.72s/it]

Fixed: Arabidopsis halleri partitivirus 1 -> unclassified Partitiviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|          | 163/13592 [04:27<6:05:15,  1.63s/it]

Fixed: Festuca pratensis amalgavirus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 173/13592 [04:43<5:46:59,  1.55s/it]

Fixed: Camellia oleifera amalgavirus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 174/13592 [04:44<5:44:00,  1.54s/it]

Fixed: Capsicum annuum amalgavirus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 176/13592 [04:48<5:45:54,  1.55s/it]

Fixed: Salvia hispanica RNA virus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 177/13592 [04:49<5:48:05,  1.56s/it]

Fixed: Erigeron breviscapus amalgavirus 2 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 178/13592 [04:51<5:45:50,  1.55s/it]

Fixed: Anthoxanthum odoratum amalgavirus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 179/13592 [04:52<5:43:46,  1.54s/it]

Fixed: Phalaenopsis equestris amalgavirus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 180/13592 [04:54<5:45:47,  1.55s/it]

Fixed: Festuca pratensis amalgavirus 2 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 181/13592 [04:55<5:42:29,  1.53s/it]

Fixed: Antonospora locustae virus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 182/13592 [04:57<5:39:46,  1.52s/it]

Fixed: Erigeron breviscapus amalgavirus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 183/13592 [04:59<6:02:41,  1.62s/it]

Fixed: Medicago sativa amalgavirus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 184/13592 [05:00<5:55:40,  1.59s/it]

Fixed: Cleome droserifolia amalgavirus 1 -> unclassified Amalgaviridae (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 185/13592 [05:02<5:50:53,  1.57s/it]

Fixed: Sanxia atyid shrimp virus 3 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   1%|▏         | 200/13592 [05:26<6:07:04,  1.64s/it]

Fixed: Goose calicivirus -> unclassified Caliciviridae (Fallback to Parent (no rank))

Repairing Lineage:   2%|▏         | 204/13592 [05:33<6:13:33,  1.67s/it]

Fixed: Calicivirus isolate TCG -> unclassified Caliciviridae (Fallback to Parent (no rank))

Repairing Lineage:   2%|▏         | 210/13592 [05:43<5:52:38,  1.58s/it]

Fixed: St-Valerien swine virus -> unclassified Caliciviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 373/13592 [10:05<5:31:54,  1.51s/it]

Fixed: Ovine picornavirus -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 374/13592 [10:07<5:33:42,  1.51s/it]

Fixed: Aimelvirus 2 -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 382/13592 [10:19<5:37:07,  1.53s/it]

Fixed: Bat picornavirus 1 -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 394/13592 [10:38<5:32:26,  1.51s/it]

Fixed: GV -> Baculoviridae (Fallback to Parent (family))

Repairing Lineage:   3%|▎         | 406/13592 [10:57<5:49:47,  1.59s/it]

Fixed: Chicken picornavirus 1 -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 431/13592 [11:36<5:31:18,  1.51s/it]

Fixed: Washington bat picornavirus -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 437/13592 [11:46<6:21:37,  1.74s/it]

Fixed: Rhimavirus A -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 438/13592 [11:48<6:34:23,  1.80s/it]

Fixed: Tortoise rafivirus A -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 441/13592 [11:53<6:01:37,  1.65s/it]

Fixed: Falcon picornavirus -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 448/13592 [12:04<5:42:47,  1.56s/it]

Fixed: Bat picornavirus 2 -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 449/13592 [12:05<5:37:22,  1.54s/it]

Fixed: Fur seal picorna-like virus -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 460/13592 [12:22<5:26:32,  1.49s/it]

Fixed: Bat picornavirus 3 -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 467/13592 [12:33<5:37:46,  1.54s/it]

Fixed: Feline picornavirus -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 468/13592 [12:34<5:35:26,  1.53s/it]

Fixed: Pigeon picornavirus B -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 472/13592 [12:40<5:30:04,  1.51s/it]

Fixed: Cyprivirus A -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   3%|▎         | 475/13592 [12:45<5:30:46,  1.51s/it]

Fixed: Picornaviridae sp. -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▎         | 476/13592 [12:46<5:34:15,  1.53s/it]

Fixed: Chicken picornavirus 4 -> unclassified Picornaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▎         | 504/13592 [13:31<5:51:01,  1.61s/it]

Fixed: Halyomorpha halys virus -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▎         | 505/13592 [13:33<5:41:29,  1.57s/it]

Fixed: Chequa iflavirus -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▎         | 506/13592 [13:34<5:41:28,  1.57s/it]

Fixed: Culex Iflavi-like virus 1 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▎         | 507/13592 [13:36<5:35:40,  1.54s/it]

Fixed: Euscelidius variegatus virus 1 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▎         | 508/13592 [13:37<5:37:17,  1.55s/it]

Fixed: Culex Iflavi-like virus 4 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▎         | 509/13592 [13:40<5:40:07,  1.56s/it]

Fixed: Thaumetopoea pityocampa iflavirus 1 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 510/13592 [13:41<6:27:18,  1.78s/it]

Fixed: King virus -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 511/13592 [13:43<6:16:52,  1.73s/it]

Fixed: La Jolla virus -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 512/13592 [13:44<6:05:35,  1.68s/it]

Fixed: Laodelphax striatella honeydew virus 1 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 513/13592 [13:46<5:55:46,  1.63s/it]

Fixed: Nesidiocoris tenuis iflavirus 1 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 514/13592 [13:47<5:48:26,  1.60s/it]

Fixed: Laodelphax striatellus picorna-like virus 2 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 515/13592 [13:49<5:43:19,  1.58s/it]

Fixed: Nilaparvata lugens honeydew virus-2 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 516/13592 [13:51<5:36:28,  1.54s/it]

Fixed: Opsiphanes invirae iflavirus 1 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 517/13592 [13:52<5:58:14,  1.64s/it]

Fixed: Pityohyphantes rubrofasciatus iflavirus -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 518/13592 [13:55<6:04:39,  1.67s/it]

Fixed: Graminella nigrifrons virus 1 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 519/13592 [13:57<7:13:40,  1.99s/it]

Fixed: Nilaparvata lugens honeydew virus-3 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 520/13592 [13:58<6:41:53,  1.84s/it]

Fixed: Yongsan iflavirus 1 -> unclassified Iflaviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 550/13592 [14:44<5:41:53,  1.57s/it]

Fixed: Lasius neglectus virus 2 -> unclassified Orthornavirae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 553/13592 [14:49<5:33:29,  1.53s/it]

Fixed: Biomphalaria virus 1 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 554/13592 [14:51<5:53:09,  1.63s/it]

Fixed: Picorna-like virus AWando15 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 555/13592 [14:52<5:45:26,  1.59s/it]

Fixed: Antarctic picorna-like virus 4 -> environmental samples (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 558/13592 [14:57<5:30:35,  1.52s/it]

Fixed: Suncus murinus picornavirus -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 577/13592 [15:27<5:38:11,  1.56s/it]

Fixed: Bivalve RNA virus G5 -> unclassified Dicistroviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 578/13592 [15:28<5:32:43,  1.53s/it]

Fixed: Formica exsecta virus 1 -> unclassified Dicistroviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 579/13592 [15:30<5:28:15,  1.51s/it]

Fixed: Centovirus -> unclassified Dicistroviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 580/13592 [15:31<5:34:22,  1.54s/it]

Fixed: Apis dicistrovirus -> unclassified Dicistroviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 581/13592 [15:33<5:30:38,  1.52s/it]

Fixed: Big Sioux River virus -> unclassified Dicistroviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 582/13592 [15:35<5:39:59,  1.57s/it]

Fixed: Bivalve RNA virus G1 -> unclassified Dicistroviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 583/13592 [15:36<5:41:14,  1.57s/it]

Fixed: Macrobrachium rosenbergii Taihu virus -> unclassified Dicistroviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 584/13592 [15:38<5:47:53,  1.60s/it]

Fixed: Goose dicistrovirus -> unclassified Dicistroviridae (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 585/13592 [15:40<5:41:50,  1.58s/it]

Fixed: Yongsan picorna-like virus 4 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 586/13592 [15:41<5:48:54,  1.61s/it]

Fixed: Nephila clavipes virus 2 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 587/13592 [15:43<5:39:12,  1.56s/it]

Fixed: Sanxia picorna-like virus 9 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 588/13592 [15:44<5:33:04,  1.54s/it]

Fixed: Biomphalaria virus 3 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 589/13592 [15:46<5:28:46,  1.52s/it]

Fixed: Antarctic picorna-like virus 2 -> environmental samples (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 592/13592 [15:50<5:25:47,  1.50s/it]

Fixed: Riptortus pedestris virus-1 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 593/13592 [15:51<5:23:28,  1.49s/it]

Fixed: Picornavirales Bu-3 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 595/13592 [15:54<5:25:27,  1.50s/it]

Fixed: Tioga picorna-like virus 1 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 596/13592 [15:56<5:24:18,  1.50s/it]

Fixed: Cherry virus Trakiya -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 597/13592 [15:58<5:36:29,  1.55s/it]

Fixed: Apodemus agrarius picornavirus -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 598/13592 [16:00<5:37:00,  1.56s/it]

Fixed: Delisea pulchra RNA virus -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 599/13592 [16:01<6:00:18,  1.66s/it]

Fixed: Yili teratoscincus roborowskii picornavirus 2 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 600/13592 [16:03<5:47:51,  1.61s/it]

Fixed: Bivalve RNA virus G2 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 601/13592 [16:04<5:38:53,  1.57s/it]

Fixed: Picornavirales Tottori-HG1 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 602/13592 [16:06<5:36:58,  1.56s/it]

Fixed: Bivalve RNA virus G3 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 603/13592 [16:07<5:32:12,  1.53s/it]

Fixed: Picornavirales sp. -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 604/13592 [16:09<5:29:46,  1.52s/it]

Fixed: Antarctic picorna-like virus 3 -> environmental samples (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 605/13592 [16:10<5:27:03,  1.51s/it]

Fixed: Sugar beet cyst nematode virus 1 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 606/13592 [16:12<5:29:36,  1.52s/it]

Fixed: Pingu picornavirus -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 607/13592 [16:13<5:43:59,  1.59s/it]

Fixed: Antarctic picorna-like virus 1 -> environmental samples (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 608/13592 [16:15<5:37:30,  1.56s/it]

Fixed: Nephila clavipes virus 1 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 609/13592 [16:16<5:32:16,  1.54s/it]

Fixed: Guangdong chinese water snake picornavirus -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 610/13592 [16:18<5:32:44,  1.54s/it]

Fixed: Blackbird arilivirus -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   4%|▍         | 611/13592 [16:19<5:28:15,  1.52s/it]

Fixed: Kilifi Virus -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   5%|▍         | 612/13592 [16:21<5:31:45,  1.53s/it]

Fixed: Biomphalaria virus 2 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   5%|▍         | 613/13592 [16:23<5:33:42,  1.54s/it]

Fixed: Yongsan picorna-like virus 3 -> unclassified Picornavirales (Fallback to Parent (no rank))

Repairing Lineage:   5%|▍         | 624/13592 [16:40<5:29:11,  1.52s/it]

Fixed: Shrew coronavirus -> unclassified Orthocoronavirinae (Fallback to Parent (no rank))

Repairing Lineage:   5%|▍         | 666/13592 [17:44<5:28:07,  1.52s/it]

Fixed: Rodent coronavirus -> unclassified Orthocoronavirinae (Fallback to Parent (no rank))

Repairing Lineage:   5%|▍         | 667/13592 [17:46<5:30:55,  1.54s/it]

Fixed: Bat coronavirus -> unclassified Orthocoronavirinae (Fallback to Parent (no rank))

Repairing Lineage:   5%|▍         | 673/13592 [17:56<5:57:10,  1.66s/it]

Fixed: Serpentovirinae sp. -> unclassified Serpentovirinae (Fallback to Parent (no rank))

Repairing Lineage:   5%|▌         | 701/13592 [18:41<5:37:20,  1.57s/it]

Fixed: Rodent arterivirus -> unclassified Arteriviridae (Fallback to Parent (no rank))

Repairing Lineage:   5%|▌         | 705/13592 [18:47<5:27:19,  1.52s/it]

Fixed: Southwest baboon virus 1 -> unclassified Arteriviridae (Fallback to Parent (no rank))

Repairing Lineage:   5%|▌         | 720/13592 [19:10<5:48:28,  1.62s/it]

Fixed: Aplysia californica nido-like virus -> unclassified Nidovirales (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 803/13592 [21:23<5:33:50,  1.57s/it]

Fixed: Porcine astrovirus 5 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 804/13592 [21:24<5:29:26,  1.55s/it]

Fixed: Bastrovirus BAS-3 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 805/13592 [21:26<5:24:17,  1.52s/it]

Fixed: Murine astrovirus -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 836/13592 [22:13<5:16:08,  1.49s/it]

Fixed: Astrovirus VA4 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 837/13592 [22:15<5:28:58,  1.55s/it]

Fixed: Sichuan takin astrovirus -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 843/13592 [22:24<5:23:40,  1.52s/it]

Fixed: Astrovirus MLB3 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 844/13592 [22:25<5:21:38,  1.51s/it]

Fixed: Astrovirus MLB2 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 845/13592 [22:27<5:24:38,  1.53s/it]

Fixed: Culex Bastrovirus-like virus -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 846/13592 [22:28<5:24:18,  1.53s/it]

Fixed: Human astrovirus -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 847/13592 [22:30<5:20:26,  1.51s/it]

Fixed: Bovine astrovirus CH13 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 848/13592 [22:31<5:19:52,  1.51s/it]

Fixed: Bastrovirus BAS-1 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▌         | 849/13592 [22:33<5:18:19,  1.50s/it]

Fixed: Bastrovirus BAS-2 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   6%|▋         | 850/13592 [22:34<5:16:23,  1.49s/it]

Fixed: Astrovirus VA3 -> unclassified Astroviridae (Fallback to Parent (no rank))

Repairing Lineage:   8%|▊         | 1046/13592 [27:43<5:16:27,  1.51s/it]

Fixed: Hubei Poty-like virus 1 -> unclassified Potyviridae (Fallback to Parent (no rank))

Repairing Lineage:   8%|▊         | 1047/13592 [27:45<5:34:32,  1.60s/it]

Fixed: Longan witches broom-associated virus -> unclassified Potyviridae (Fallback to Parent (no rank))

Repairing Lineage:   8%|▊         | 1049/13592 [27:49<5:22:40,  1.54s/it]

Fixed: Reed chlorotic stripe virus -> unclassified Potyviridae (Fallback to Parent (no rank))

Repairing Lineage:   8%|▊         | 1123/13592 [29:46<5:40:50,  1.64s/it]

Fixed: Inner Mongolia sediment arena-like virus -> unclassified Arenaviridae (Fallback to Parent (no rank))

Repairing Lineage:  10%|▉         | 1335/13592 [35:24<5:19:55,  1.57s/it]

Fixed: Mulberry vein banding virus -> unclassified Peribunyaviridae (Fallback to Parent (no rank))

Repairing Lineage:  11%|█         | 1524/13592 [40:19<5:21:42,  1.60s/it]

Fixed: Saesbyeol virus -> unclassified Phasmaviridae (Fallback to Parent (no rank))

Repairing Lineage:  11%|█         | 1527/13592 [40:24<5:10:42,  1.55s/it]

Fixed: Insect inshuvirus -> unclassified Phasmaviridae (Fallback to Parent (no rank))

Repairing Lineage:  12%|█▏        | 1584/13592 [41:56<5:16:52,  1.58s/it]

Fixed: Groundnut ringspot and Tomato chlorotic spot virus reassortant -> Tospovirus reassortants (Fallback to Parent (clade))

Repairing Lineage:  12%|█▏        | 1595/13592 [42:13<5:09:12,  1.55s/it]

Fixed: Yongsan bunyavirus 1 -> unclassified Elliovirales (Fallback to Parent (no rank))

Repairing Lineage:  12%|█▏        | 1597/13592 [42:16<5:09:07,  1.55s/it]

Fixed: Athtab bunya-like virus -> unclassified Elliovirales (Fallback to Parent (no rank))

Repairing Lineage:  12%|█▏        | 1663/13592 [43:59<5:00:30,  1.51s/it]

Fixed: Chrysanthemum yellow dwarf virus -> unclassified Betarhabdovirinae (Fallback to Parent (no rank))

Repairing Lineage:  12%|█▏        | 1676/13592 [44:19<5:00:26,  1.51s/it]

Fixed: Actinidia cytorhabdovirus JS27 -> unclassified Betarhabdovirinae (Fallback to Parent (no rank))

Repairing Lineage:  13%|█▎        | 1769/13592 [46:46<5:17:10,  1.61s/it]

Fixed: Tacheng Tick Virus 3 -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  13%|█▎        | 1827/13592 [48:18<5:04:59,  1.56s/it]

Fixed: Red clover varicosavirus -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▎        | 1858/13592 [49:07<5:24:46,  1.66s/it]

Fixed: Farmington virus -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▎        | 1859/13592 [49:08<5:20:19,  1.64s/it]

Fixed: Rhabdoviridae sp. -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▎        | 1866/13592 [49:19<5:07:34,  1.57s/it]

Fixed: Wuhan Insect virus 7 -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▍        | 1875/13592 [49:34<5:15:42,  1.62s/it]

Fixed: Hymenopteran rhabdo-related virus -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▍        | 1876/13592 [49:36<5:07:13,  1.57s/it]

Fixed: Merida-like virus KE-2017a -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▍        | 1892/13592 [50:01<5:15:36,  1.62s/it]

Fixed: Xinjiang varicosa-like virus -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▍        | 1896/13592 [50:07<5:03:42,  1.56s/it]

Fixed: Wuhan Ant Virus -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▍        | 1897/13592 [50:09<4:59:16,  1.54s/it]

Fixed: Diachasmimorpha longicaudata rhabdovirus -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▍        | 1902/13592 [50:17<5:04:03,  1.56s/it]

Fixed: Maize associated rhabdovirus -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  14%|█▍        | 1908/13592 [50:26<5:10:20,  1.59s/it]

Fixed: Sanxia Water Strider Virus 5 -> unclassified Rhabdoviridae (Fallback to Parent (no rank))

Repairing Lineage:  15%|█▍        | 1981/13592 [52:21<5:10:18,  1.60s/it]

Fixed: Goose paramyxovirus SF02 -> unclassified Avulavirinae (Fallback to Parent (no rank))

Repairing Lineage:  15%|█▍        | 2004/13592 [52:59<5:20:13,  1.66s/it]

Fixed: Feline paramyxovirus 163 -> unclassified Paramyxoviridae (Fallback to Parent (no rank))

Repairing Lineage:  16%|█▌        | 2146/13592 [56:45<5:01:32,  1.58s/it]

Fixed: Lepeophtheirus virus LS24 -> unclassified Mononegavirales (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2281/13592 [1:00:20<4:47:22,  1.52s/it]

Fixed: Armigeres subalbatus virus SaX06-AK20 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2310/13592 [1:01:06<5:27:38,  1.74s/it]

Fixed: Diatom colony associated dsRNA virus 7 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2311/13592 [1:01:08<5:15:46,  1.68s/it]

Fixed: Diatom colony associated dsRNA virus 3 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2326/13592 [1:01:31<4:45:38,  1.52s/it]

Fixed: Diatom colony associated dsRNA virus 4 genome type B -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2327/13592 [1:01:32<4:46:36,  1.53s/it]

Fixed: Phlebiopsis gigantea mycovirus dsRNA 1 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2328/13592 [1:01:34<4:46:57,  1.53s/it]

Fixed: Diatom colony associated dsRNA virus 8 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2330/13592 [1:01:38<5:55:07,  1.89s/it]

Fixed: Diatom colony associated dsRNA virus 13 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2331/13592 [1:01:40<5:36:46,  1.79s/it]

Fixed: Piscine myocarditis virus AL V-708 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2332/13592 [1:01:41<5:20:41,  1.71s/it]

Fixed: Diatom colony associated dsRNA virus 10 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2342/13592 [1:01:57<5:14:26,  1.68s/it]

Fixed: Diatom colony associated dsRNA virus 9 genome type A -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2343/13592 [1:01:58<5:04:34,  1.62s/it]

Fixed: Pythium polare RNA virus 2 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2346/13592 [1:02:04<5:53:00,  1.88s/it]

Fixed: Diatom colony associated dsRNA virus 12 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2348/13592 [1:02:07<5:20:48,  1.71s/it]

Fixed: Culex tritaeniorhynchus totivirus -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2351/13592 [1:02:12<5:10:24,  1.66s/it]

Fixed: Red clover powdery mildew-associated totivirus 9 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2353/13592 [1:02:15<4:54:13,  1.57s/it]

Fixed: Diatom colony associated dsRNA virus 5 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2354/13592 [1:02:17<4:53:10,  1.57s/it]

Fixed: Penicillium aurantiogriseum totivirus 1 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2355/13592 [1:02:18<4:55:14,  1.58s/it]

Fixed: Maize-associated totivirus 2 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2356/13592 [1:02:20<5:05:42,  1.63s/it]

Fixed: Golden shiner totivirus -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2357/13592 [1:02:21<4:59:47,  1.60s/it]

Fixed: Eimeria brunetti RNA virus 1 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2358/13592 [1:02:23<4:57:11,  1.59s/it]

Fixed: Eimeria stiedai RNA virus 1 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2359/13592 [1:02:25<4:54:16,  1.57s/it]

Fixed: Diatom colony associated dsRNA virus 6 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2361/13592 [1:02:28<4:46:29,  1.53s/it]

Fixed: Maize-associated totivirus 3 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2362/13592 [1:02:29<4:48:27,  1.54s/it]

Fixed: Trichomonas vaginalis virus -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2366/13592 [1:02:35<4:44:50,  1.52s/it]

Fixed: Tianjin totivirus -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2367/13592 [1:02:37<4:45:17,  1.52s/it]

Fixed: Diatom colony associated dsRNA virus 4 genome type A -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2369/13592 [1:02:40<4:49:10,  1.55s/it]

Fixed: Diatom colony associated dsRNA virus 11 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2373/13592 [1:02:46<4:51:25,  1.56s/it]

Fixed: Papaya meleira virus -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2374/13592 [1:02:48<4:49:06,  1.55s/it]

Fixed: Drosophila melanogaster totivirus SW-2009a -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  17%|█▋        | 2375/13592 [1:02:49<4:49:55,  1.55s/it]

Fixed: Saccharomyces kudriavzevii virus L-A1 -> unclassified Orthototiviridae (Fallback to Parent (no rank))

Repairing Lineage:  18%|█▊        | 2423/13592 [1:04:05<4:58:04,  1.60s/it]

Fixed: Chiqui virus -> unclassified Spinareovirinae (Fallback to Parent (no rank))

Repairing Lineage:  18%|█▊        | 2469/13592 [1:05:15<4:38:45,  1.50s/it]

Fixed: Grapevine Cabernet Sauvignon reovirus -> unclassified Reovirales (Fallback to Parent (no rank))

Repairing Lineage:  18%|█▊        | 2470/13592 [1:05:17<4:52:56,  1.58s/it]

Fixed: Cimodo virus -> unclassified Reovirales (Fallback to Parent (no rank))

Repairing Lineage:  18%|█▊        | 2471/13592 [1:05:18<4:48:40,  1.56s/it]

Fixed: Lutzomyia reovirus 1 -> unclassified Reovirales (Fallback to Parent (no rank))

Repairing Lineage:  18%|█▊        | 2472/13592 [1:05:20<4:43:49,  1.53s/it]

Fixed: Operophtera brumata reovirus -> unclassified Reovirales (Fallback to Parent (no rank))

Repairing Lineage:  18%|█▊        | 2474/13592 [1:05:23<4:38:24,  1.50s/it]

Fixed: Spissistilus festinus reovirus -> unclassified Reovirales (Fallback to Parent (no rank))

Repairing Lineage:  18%|█▊        | 2475/13592 [1:05:24<4:50:49,  1.57s/it]

Fixed: Nephila clavipes virus 6 -> unclassified Reovirales (Fallback to Parent (no rank))

Repairing Lineage:  18%|█▊        | 2476/13592 [1:05:26<4:46:53,  1.55s/it]

Fixed: Raspberry latent virus -> unclassified Reovirales (Fallback to Parent (no rank))

Repairing Lineage:  20%|██        | 2778/13592 [1:13:29<4:31:01,  1.50s/it]

Fixed: Leviviridae sp. -> unclassified Fiersviridae (Fallback to Parent (no rank))

Repairing Lineage:  26%|██▌       | 3521/13592 [1:32:52<4:17:00,  1.53s/it]

Fixed: Botryosphaeria dothidea Ourmia-like virus -> unclassified Botourmiaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3634/13592 [1:35:48<4:15:51,  1.54s/it]

Fixed: Diatom colony associated ssRNA virus 2 -> unclassified Narnaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3645/13592 [1:36:06<4:49:54,  1.75s/it]

Fixed: Leptomonas seymouri Narna-like virus 1 -> unclassified Narnaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3646/13592 [1:36:08<4:39:38,  1.69s/it]

Fixed: Penicillium digitatum narna-like virus 1 -> unclassified Narnaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3647/13592 [1:36:09<4:35:22,  1.66s/it]

Fixed: Neofusicoccum luteum mitovirus 1 -> unclassified Narnaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3648/13592 [1:36:11<4:26:08,  1.61s/it]

Fixed: Phytophthora infestans RNA virus 4 -> unclassified Narnaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3649/13592 [1:36:12<4:19:27,  1.57s/it]

Fixed: Macrobrachium rosenbergii nodavirus -> unclassified Nodaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3650/13592 [1:36:14<4:21:22,  1.58s/it]

Fixed: Penaeus vannamei nodavirus -> unclassified Nodaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3656/13592 [1:36:23<4:09:24,  1.51s/it]

Fixed: Le Blanc nodavirus -> unclassified Nodaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3661/13592 [1:36:30<4:06:16,  1.49s/it]

Fixed: Santeuil nodavirus -> unclassified Nodaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3662/13592 [1:36:32<4:07:56,  1.50s/it]

Fixed: Orsay virus -> unclassified Nodaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3735/13592 [1:38:26<4:09:52,  1.52s/it]

Fixed: Lagenaria siceraria endornavirus-Hubei -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  27%|██▋       | 3736/13592 [1:38:28<4:07:28,  1.51s/it]

Fixed: Diatom colony associated dsRNA virus 15 -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3744/13592 [1:38:41<4:15:06,  1.55s/it]

Fixed: Ceratobasidium endornavirus C -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3745/13592 [1:38:42<4:45:29,  1.74s/it]

Fixed: Ceratobasidium endornavirus D -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3746/13592 [1:38:44<4:32:51,  1.66s/it]

Fixed: Rhizoctonia solani endornavirus 1 -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3747/13592 [1:38:46<4:23:23,  1.61s/it]

Fixed: Cluster bean endornavirus 1 -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3748/13592 [1:38:47<4:44:18,  1.73s/it]

Fixed: Ceratobasidium endornavirus B -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3749/13592 [1:38:49<4:33:34,  1.67s/it]

Fixed: Ceratobasidium endornavirus G -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3750/13592 [1:38:50<4:26:24,  1.62s/it]

Fixed: Ceratobasidium endornavirus A -> unclassified Endornaviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3852/13592 [1:41:34<4:16:40,  1.58s/it]

Fixed: Carnation yellow fleck virus -> unclassified Closteroviridae (Fallback to Parent (no rank))

Repairing Lineage:  28%|██▊       | 3853/13592 [1:41:36<4:11:24,  1.55s/it]

Fixed: Carrot closterovirus -> unclassified Closteroviridae (Fallback to Parent (no rank))

Repairing Lineage:  29%|██▉       | 3915/13592 [1:43:14<4:18:53,  1.61s/it]

Fixed: Macrophomina phaseolina tobamo-like virus -> unclassified Virgaviridae (Fallback to Parent (no rank))

Repairing Lineage:  29%|██▉       | 3918/13592 [1:43:19<4:14:04,  1.58s/it]

Fixed: Nephila clavipes virus 4 -> unclassified Virgaviridae (Fallback to Parent (no rank))

Repairing Lineage:  29%|██▉       | 3919/13592 [1:43:20<4:13:34,  1.57s/it]

Fixed: Nephila clavipes virus 3 -> unclassified Virgaviridae (Fallback to Parent (no rank))

Repairing Lineage:  30%|███       | 4113/13592 [1:48:23<3:57:12,  1.50s/it]

Fixed: Salvia divinorum RNA virus 1 -> unclassified Betaflexiviridae (Fallback to Parent (no rank))

Repairing Lineage:  30%|███       | 4115/13592 [1:48:26<3:55:33,  1.49s/it]

Fixed: Panax ginseng flexivirus 1 -> unclassified Betaflexiviridae (Fallback to Parent (no rank))

Repairing Lineage:  30%|███       | 4120/13592 [1:48:34<4:07:08,  1.57s/it]

Fixed: Banana virus X -> unclassified Quinvirinae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4154/13592 [1:49:28<4:05:47,  1.56s/it]

Fixed: Bombyx mori latent virus -> unclassified Tymoviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4168/13592 [1:49:50<4:03:53,  1.55s/it]

Fixed: Poinsettia mosaic virus -> unclassified Tymoviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4169/13592 [1:49:52<4:00:29,  1.53s/it]

Fixed: Bee Macula-like virus -> unclassified Tymoviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4171/13592 [1:49:55<3:56:34,  1.51s/it]

Fixed: Varroa Tymo-like virus -> unclassified Tymoviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4172/13592 [1:49:57<3:57:45,  1.51s/it]

Fixed: Sclerotinia sclerotiorum debilitation-associated RNA virus 2 -> unclassified Tymovirales (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4181/13592 [1:50:11<3:55:04,  1.50s/it]

Fixed: Rhizoctonia solani flexivirus 1 -> unclassified Tymovirales (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4182/13592 [1:50:12<3:54:02,  1.49s/it]

Fixed: Bat tymo-like virus -> unclassified Tymovirales (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4183/13592 [1:50:14<3:54:31,  1.50s/it]

Fixed: Grapevine associated tymo-like virus -> unclassified viruses (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4184/13592 [1:50:15<3:54:49,  1.50s/it]

Fixed: Fusarium graminearum mycotymovirus 1 -> unclassified Tymovirales (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4187/13592 [1:50:20<4:07:37,  1.58s/it]

Fixed: Sogatella furcifera hepe-like virus -> unclassified Hepeviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4191/13592 [1:50:27<4:36:02,  1.76s/it]

Fixed: Rana hepevirus -> unclassified Hepeviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4196/13592 [1:50:36<4:24:53,  1.69s/it]

Fixed: Wheat stripe mosaic virus -> unclassified Benyviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4203/13592 [1:50:47<4:09:39,  1.60s/it]

Fixed: Sarawak virus -> unclassified Alphatetraviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4205/13592 [1:50:50<4:11:37,  1.61s/it]

Fixed: Culex Tetra-like virus -> unclassified Alphatetraviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4218/13592 [1:51:10<4:07:54,  1.59s/it]

Fixed: Culex-associated Tombus-like virus -> unclassified Tombusviridae (Fallback to Parent (no rank))

Repairing Lineage:  31%|███       | 4233/13592 [1:51:33<3:51:39,  1.49s/it]

Fixed: Rice virus A -> unclassified Tombusviridae (Fallback to Parent (no rank))

Repairing Lineage:  32%|███▏      | 4297/13592 [1:53:12<3:55:08,  1.52s/it]

Fixed: Yongsan tombus-like virus 1 -> unclassified Tombusviridae (Fallback to Parent (no rank))

Repairing Lineage:  32%|███▏      | 4412/13592 [1:56:14<4:26:41,  1.74s/it]

Fixed: Mac Peak virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  32%|███▏      | 4413/13592 [1:56:16<4:42:27,  1.85s/it]

Fixed: Xishuangbanna aedes flavivirus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  32%|███▏      | 4414/13592 [1:56:17<4:24:58,  1.73s/it]

Fixed: Mogiana tick virus -> Jingmenvirus group (Fallback to Parent (clade))

Repairing Lineage:  32%|███▏      | 4415/13592 [1:56:19<4:13:10,  1.66s/it]

Fixed: Karumba virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  32%|███▏      | 4416/13592 [1:56:20<4:04:25,  1.60s/it]

Fixed: Ilomantsi virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  32%|███▏      | 4417/13592 [1:56:22<3:59:03,  1.56s/it]

Fixed: Culex Flavi-like virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4418/13592 [1:56:23<3:54:23,  1.53s/it]

Fixed: Bamaga virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4419/13592 [1:56:25<3:51:46,  1.52s/it]

Fixed: Diatom colony associated ssRNA virus 1 -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4420/13592 [1:56:26<3:49:54,  1.50s/it]

Fixed: Menghai flavivirus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4421/13592 [1:56:27<3:48:33,  1.50s/it]

Fixed: Nienokoue virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4422/13592 [1:56:29<3:47:48,  1.49s/it]

Fixed: Lumpfish flavivirus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4423/13592 [1:56:31<3:50:08,  1.51s/it]

Fixed: Culiseta flavivirus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4424/13592 [1:56:32<3:49:49,  1.50s/it]

Fixed: Nakiwogo virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4425/13592 [1:56:34<3:48:58,  1.50s/it]

Fixed: Soybean cyst nematode virus 5 -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4426/13592 [1:56:35<4:11:28,  1.65s/it]

Fixed: Macrosiphum euphorbiae virus 1 -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4427/13592 [1:56:37<4:03:35,  1.59s/it]

Fixed: Lammi virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4428/13592 [1:56:38<4:00:05,  1.57s/it]

Fixed: Nhumirim virus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4429/13592 [1:56:40<3:55:54,  1.54s/it]

Fixed: Apis flavivirus -> unclassified Flaviviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4442/13592 [1:57:00<3:57:28,  1.56s/it]

Fixed: Drosophila melanogaster birnavirus SW-2009a -> unclassified Birnaviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4443/13592 [1:57:02<3:54:17,  1.54s/it]

Fixed: Espirito Santo virus -> unclassified Birnaviridae (Fallback to Parent (no rank))

Repairing Lineage:  33%|███▎      | 4495/13592 [1:58:22<3:52:50,  1.54s/it]

In [13]:
df_labels_genus.to_csv("raw_database/genus_new_labels.csv")
final_df.to_csv("raw_database/final.csv")

In [ ]:
!touch raw_database/fim.txt